### ISSUE TITLE
管理员启动mklink后并没有效果

### ISSUE THREAD

**Issue by 414dxD** [LorisYounger/VPet#1]
cmd提示
![微信图片_20230307150134](https://user-images.githubusercontent.com/70002326/223348301-a0fe7f0b-e4a6-410a-8d37-083fb8feea4f.png)

**Comment by LorisYounger** [comment]
你没生成Release, 找不到路径正常, 你可以试试用DEBUGX64跑, 应该已经能正常运行了

**Comment by 414dxD** [comment]
> 你没生成Release， 找不到路径正常， 你可以试试用DEBUGX64跑， 应该已经能正常运行了

x64 debug
![微信图片_20230307150815](https://user-images.githubusercontent.com/70002326/223349981-20eba1fa-184c-4a75-9d9a-0e93a01f45ab.png)

**Comment by LorisYounger** [comment]
看报错是 生成失败,你生成的时候没有显示报错啥的吗
另外你Visualstudio版本是多少? 我用的2022版,2019应该也能用,再早点估计不一定兼容
