### ISSUE TITLE
桌面切换桌宠无法跟随显示

### ISSUE THREAD

**Issue by lalala123987** [LorisYounger/VPet#100]
windows系统下进行桌面切换操作后桌宠无法在新桌面显示，桌宠只能在其中一个桌面进行显示，能否让桌宠不随桌面切换而消失？

**Comment by LorisYounger** [comment]
不知道咋整, 切换桌面是系统层面的, 搜了下并没有找到方法能够实现.

**Comment by zhufengning** [comment]
这个已经解决了吗？要怎么设置呢？
