### ISSUE TITLE
进食动画被打断后，更好买遮罩不会消失

### ISSUE THREAD

**Issue by BWMaple** [LorisYounger/VPet#102]
更好买勾上“购买后不自动关闭窗口”的情况下，购买道具后，打断进食动画，黑色遮罩不会消失，需要重新打开商店
![image](https://github.com/LorisYounger/VPet/assets/43632268/e2070d09-c373-4676-be4c-984c4bbca8a3)

**Comment by LorisYounger** [comment]
已在 https://github.com/LorisYounger/VPet/commit/550398dedd2269bf12af9dce82b5f54a3659e9d9 修复
