### ISSUE TITLE
打开新手教程时出现的问题

### ISSUE THREAD

**Issue by JOZA-ORANGE** [LorisYounger/VPet#103]
第一次打开游戏时，如果在之前指定了其他的程序(默认程序)来打开html，比如记事本
那么游戏打开的也会是记事本的形式
![image](https://github.com/LorisYounger/VPet/assets/61607246/a06c781f-57f6-41d6-8074-0230f9848046)

**Comment by wubostc** [comment]
你得手动用浏览器打开了

**Comment by JOZA-ORANGE** [comment]
> 你得手动用浏览器打开了

确实是手动打开的（）

**Comment by LorisYounger** [comment]
默认是用默认打开html的打开
这个我也没法判断你打开工具是浏览器还是编辑器
不过一般用编辑器打开的人都比较懂,应该会自己用浏览器打开, 就懒得修了
