### ISSUE TITLE
如何接入自己部署的API

### ISSUE THREAD

**Issue by rong-xiaoli** [LorisYounger/VPet#105]
服务器上有个ChatGLM2-6B，我希望将VPet接入这个API。

ChatGLM2-6B有一个openai格式的接口，但是有问题。正在调试。

**Comment by rong-xiaoli** [comment]
![image](https://github.com/LorisYounger/VPet/assets/58361774/bb45c571-02ae-4754-8b4e-2f9844170341)
不知道是不是因为响应缺了什么东西导致的。

**Comment by rong-xiaoli** [comment]
历史有显示回显，但是消息显示NullReferenceException。稍后给出截图。

**Comment by LorisYounger** [comment]
见 #79
