### ISSUE TITLE
【讨论】GPT相关

### ISSUE THREAD

**Issue by woshiop1337** [LorisYounger/VPet#107]
你好，我最近在开发一个关于GPT程序，但不知道如何连续对话，看到桌宠可以连续对话便想来请教一下
请问桌宠的连续对话是怎么实现的？

**Comment by sushi3085** [comment]
將過去的對話紀錄一併傳送給模型即可，舉例來說：
如果只將最近的一句"問題"丟給模型，那麼模型看到的是這樣：
使用者：`那藍色呢？`
這個時候，模型可能就會變成這樣回答
模型回答：`我不太清楚您的意思，可以請您多提供一些上下文(context)嗎？`

所以我們只需要將過去所有的紀錄傳給模型，比方說這樣：
使用者：
`我最喜歡的顏色是粉紅色，你呢？`　　　　←這個是使用者當初的輸入
`我也喜歡粉紅色！`　　　　　　　　　　 ←這個是模型當初的回答
`那藍色呢？`　　　　　　　　　　　　　←這個是使用者接下去的提問

這個時候模型因為看到過去的訊息而知道現在的對話脈絡，所以便會依循脈絡回答：
模型回答：`歐！那是我第二喜歡的顏色！`

**Comment by xmbhjQAQ** [comment]
将所有历史对话一起和最新对话打包
格式大概是这样的
system:
assistant:
user:
assistant:
user:
......
