### ISSUE TITLE
“说话”功能有http 接口可调用吗

### ISSUE THREAD

**Issue by Kylin93CN** [LorisYounger/VPet#108]
想通过http请求去触发，让桌宠讲话，有可以实现的方法吗

**Comment by kylinZhang-pr** [comment]
宠物聊天功能本来用的好好的，更新之后无法使用，更新明明说的是修复400问题，但是这次更新修没修复我不知道，但是原来能用的用不了了，我刚跟身边的朋友推荐这游戏就很尴尬

**Comment by LorisYounger** [comment]
> 宠物聊天功能本来用的好好的，更新之后无法使用，更新明明说的是修复400问题，但是这次更新修没修复我不知道，但是原来能用的用不了了，我刚跟身边的朋友推荐这游戏就很尴尬

发下聊天内容给我,我研究下看看
