### ISSUE TITLE
建议：多屏系统内判断当前所在屏幕并以此决定运动路线和显示方向

### ISSUE THREAD

**Issue by YukkuriC** [LorisYounger/VPet#109]
目前的实现，对于多屏系统（尤其是我这种一横一竖的），桌宠很容易爬到不可见区域，很难受

--------

```c#
using System.Windows.Forms;
using System.Windows.Interop;

    // ...
    WindowInteropHelper windowInteropHelper = new WindowInteropHelper(mw);
    var currentScreen = Screen.FromHandle(windowInteropHelper.Handle);
    var currentScreenBorder = currentScreen.Bounds;
```
[搜了下](https://learn.microsoft.com/en-us/answers/questions/957775/wpf-c-get-the-top-left-point-of-the-current-screen)，是可以做到直接定位当前屏幕外包矩形的，然后理论上只要每次位置更新缓存一下新的外包矩形就行了，比如在MoveWindows里面

**Comment by Hakoyu** [comment]
已在 bceb769 实现

**Comment by YukkuriC** [comment]
就是那个跑不通我才修的啊，你看这个pr的位置
不说右下两个的具体算式，很简单的问题：左上距离不用区分屏幕吗？
