### ISSUE TITLE
有计划提供.net core版本的nuget吗？

### ISSUE THREAD

**Issue by tracyma-05** [LorisYounger/VPet#11]
发现目前的nuget只支持 framework 4.8，并没有提供.net core版本的，希望能够提供.net core版本的代码或者nuget。

**Comment by LorisYounger** [comment]
有计划提供,不过不会这么快,估计得等到正式版发布后才会出core版本

**Comment by December-Bai** [comment]
mklink 不会用，能否告诉我一下要怎么使用这个命令才能运行程序

**Comment by LorisYounger** [comment]
已在 v1.10 完成
