### ISSUE TITLE
自动购买和允许移动的配置项冲突

### ISSUE THREAD

**Issue by YukkuriC** [LorisYounger/VPet#110]
autobuy选项在设置时写入的是!allowmove
https://github.com/LorisYounger/VPet/blob/17d2577456d2c73af27900a2c38e1e1545ccf4e8/VPet-Simulator.Windows.Interface/Setting.cs#L429

**Comment by YukkuriC** [comment]
顺便，我不太理解为什么allowmove自己在读写的时候都要取反

**Comment by LorisYounger** [comment]
已修复, 因为取值默认是值是false
