### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kylinZhang-pr** [LorisYounger/VPet#111]
更新到最新版，原来可以正常使用的CHAT聊天机器人报出了API调用失败400的错误，请求更正

**Comment by LorisYounger** [comment]
请发聊天记录给我研究下, 我这边什么问题都没有
![image](https://github.com/LorisYounger/VPet/assets/34806646/c5da2aaf-37a5-4584-ac97-a8c29842501b)

**Comment by kylinZhang-pr** [comment]
不好意思，不经常看邮件，现在已经没有能连接openai的梯子了无法复现问题

在 2023年8月26日星期六，ZouJin ***@***.***> 写道：
