### ISSUE TITLE
开发体验修改建议：通过Msbuild任务来创建mod软链接

### ISSUE THREAD

**Issue by MJEdwin** [LorisYounger/VPet#114]
### 建议：
可以通过Msbuild任务来自动创建mod软链接，可以让开发人员即使在删除bin目录时不需要再运行bat文件
### 缺陷：
由于mklink命令需要windows管理员运行，所以需要用管理员身份启动visual studio

**Comment by LorisYounger** [comment]
用管理员身份启动visual studio太麻烦了,还是运行下bat算了,方便
谁没事管理员跑vs(
