### ISSUE TITLE
PR: sdk风格csproj

### ISSUE THREAD

**Issue by MJEdwin** [LorisYounger/VPet#116]
作者你好，不好意思提前提了pr给你，希望可以review一下(pr: #115)
该pr使用了.net upgrade assistant将原有旧风格的csproj转换为新sdk style csproj，该风格csproj好处很多，我列举一下几点：
1. 使用新的roslyn编译器而非旧的编译器，项目编译速度有效提升
2. vs编译无关，旧风格的csproj与vs和msbuild深度绑定，新csproj则与ide无关，可以在vscode上进行开发
3. csproj文件简洁易懂，内容可读，能有效剔除不需要的功能包，减少包体积，(pr中移除了对System.Data.DataSetExtensions的引用)
4. 为升级.net core铺平道路，有了sdk风格csproj，可以指定多目标框架编译，直接完成nuget包兼容.net core
5. 为未来pet跨平台铺平道路

**Comment by LorisYounger** [comment]
你这新风格支持分开x86/64版本引用不同包吗
我之所以用旧版本，就是为了这个功能

**Comment by LorisYounger** [comment]
我看你的pr并没有分开x64/x86的样子

**Comment by LorisYounger** [comment]
![image](https://github.com/LorisYounger/VPet/assets/34806646/3b0b106a-4fd6-4945-ac97-9abce353ba0e)

**Comment by MJEdwin** [comment]
嗯，支持的

**Comment by MJEdwin** [comment]
这里可以通过condition来区分平台
![Uploading IMG_2504.jpeg…]()

**Comment by MJEdwin** [comment]
这里可以通过condition来区分平台
![IMG_2504](https://github.com/LorisYounger/VPet/assets/19172456/086afbc3-6093-4160-a155-8d255040fefb)

**Comment by LorisYounger** [comment]
另外还是有问题, 
![image](https://github.com/LorisYounger/VPet/assets/34806646/9360a09b-16cc-4ab0-b0ae-58ef32848b4e)
虽然说能跑,但是不跑的时候似乎和xaml的连接断开了,看起来挺难受的

**Comment by LorisYounger** [comment]
> 另外还是有问题, ![image](https://user-images.githubusercontent.com/34806646/263446205-9360a09b-16cc-4ab0-b0ae-58ef32848b4e.png) 虽然说能跑,但是不跑的时候似乎和xaml的连接断开了,看起来挺难受的

修好了在 https://github.com/LorisYounger/VPet/commit/64277af6abeaeefce7da975d1fe4c021d24c058a

**Comment by MJEdwin** [comment]
我在指定为x64运行时没有出现过这些错误信息

**Comment by LorisYounger** [comment]
应该是你给全部指定了x64/x86的原因
只有[VPet-Simulator.Windows](https://github.com/LorisYounger/VPet/tree/main/VPet-Simulator.Windows)需要指定x64/x86, 其他的不需要

**Comment by LorisYounger** [comment]
没事,反正已经修好了
