### ISSUE TITLE
[讨论]  部分mod会将其动画插入到其他的工作行为中

### ISSUE THREAD

**Issue by lalala123987** [LorisYounger/VPet#117]
在进行某些互动时经常会有来自于其他mod的动画插入（类似于进行工作时随机会变成睡觉状态），这种插入与不插入应该怎么进行设置？希望出一个对这种插入行为进行管理的功能，因为在某些互动时并不希望动画改变，或者是并不希望某段动画插入到其他的互动当中。例如：工作时一直是工作动画，而出现睡觉动画（这种举例情况并不突兀，但在某些mod的情形下动画转换会莫名其妙）

**Comment by LorisYounger** [comment]
这种默认会被插入.
因为工作来来回回就几个动画,而要工作几个小时, 如果不允许其他动画插入会显得很单调
你就当做桌宠在摸鱼就行
