### ISSUE TITLE
生成vpet.sln错误

### ISSUE THREAD

**Issue by Patientrookie** [LorisYounger/VPet#12]
![image](https://github.com/LorisYounger/VPet/assets/41469795/03e6631e-6e04-4974-9bc2-4b7e3cd8ce57)
麻烦看一下这是什么问题呢

**Comment by LorisYounger** [comment]
使用的Visual Studio 版本太老, 推荐VS版本 2022
如果不想更改VS版本,请参考互联网上方法 https://www.codenong.com/5694/
