### ISSUE TITLE
运行代码报错“...\net462\VPet-simulator.Windows.exe"”不存在

### ISSUE THREAD

**Issue by Kylin93CN** [LorisYounger/VPet#120]
![image](https://github.com/LorisYounger/VPet/assets/18496145/5b22283f-6b58-4fea-b7c6-0399463af798)

另外问下，我想实现一些主播用的一些功能， 比如我监听弹幕送X个礼物，我就发个http请求到Vpet，然后vpet去执行某个动作，这样的 插件可以实现吗？

**Comment by Kylin93CN** [comment]
“xxxx不存在”是因为windows的sdk没有安装，已解决

**Comment by LorisYounger** [comment]
这个报错应该是生成的时候出问题了，不是主要原因，建议看下日志记录之类的找下真正的原因，我好看看
可以代码插件可以实现，调用imw.main.display...等功能就行
我以前也想和弹幕姬一起整个联动，桌宠说弹幕啥的，不过事物繁忙后面没整
用imw.main.sayrnd可以说话
具体怎么做代码插件可以参考我另一个 vpet.plugin.demo库

**Comment by LorisYounger** [comment]
之前有邮件回复过,感觉不靠谱,没有评论上来,重新补充下
