### ISSUE TITLE
我的桌寵不會跳舞

### ISSUE THREAD

**Issue by Opkli** [LorisYounger/VPet#121]
如題，我的音樂識別不是呈現-1，且數值跳動也都大於觸發數值，但她都不跳舞，有人知道發生了甚麼問題嗎?

**Comment by LorisYounger** [comment]
可能是你的主要播放设备并不是你的音乐播放设备, 搞音乐的可能会遇到这种问题
可以通过创意工坊里的mod修复, 我就不抄他们代码了 https://steamcommunity.com/sharedfiles/filedetails/?id=3022006959&searchtext=
