### ISSUE TITLE
[建议] 为Mod提供简单的编程模式

### ISSUE THREAD

**Issue by Paimon-Kawaii** [LorisYounger/VPet#124]
不得不说目前的插件功能确实能覆盖所有需求，但是对一些Modder而言可能过于繁琐。倘若Modder并未接触过.net开发，学习成本或许较高，且配置环境、运行与调试也略显繁琐。

我的想法是为VPet集成一个轻量脚本引擎，例如使用：[Jint](https://github.com/sebastienros/jint)，并编写相应的API以供调用。
比方说提供某些事件调用(饿/渴/睡觉/跳舞/点击/滑动/拖拽/...)，以及其他API(创建、删除食品/修改金钱/创建对话/创建互动/...)

这样在开发时无需配置环境，并且对于不熟悉C#的Modders而言学习成本会低很多。

虽然我有这个想法，但是我目前没什么时间写代码，大概率不会提交PR。
如果作者认同这个想法，但是没有精力的话，我大概年底会有时间做这些工作；
或者作者有兴趣的话，自己编写相应功能也可以ww.

**Comment by LorisYounger** [comment]
的确可以整,但是我估计我只会用C#的runtime编译代替这个功能
其实你都写代码了,是啥语言已经不重要了

**Comment by chinoll** [comment]
> 的确可以整,但是我估计我只会用C#的runtime编译代替这个功能 其实你都写代码了,是啥语言已经不重要了

或许提供http API的方式会更加友好点？

**Comment by LorisYounger** [comment]
> > 的确可以整,但是我估计我只会用C#的runtime编译代替这个功能 其实你都写代码了,是啥语言已经不重要了
> 
> 或许提供http API的方式会更加友好点？

那岂不是更难,httpapi还需要会点http相关的操作啥的
而且既然都httpapi了,其实可以让社区自己支持

**Comment by half-nothing** [comment]
> > > 的确可以整,但是我估计我只会用C#的runtime编译代替这个功能 其实你都写代码了,是啥语言已经不重要了
> > 
> > 
> > 或许提供http API的方式会更加友好点？
> 
> 那岂不是更难,httpapi还需要会点http相关的操作啥的 而且既然都httpapi了,其实可以让社区自己支持

说的很对，既然写插件了，那么代码是绕不过去的，那为什么不交给社区呢

**Comment by chinoll** [comment]
写了一个Http API，欢迎来debug，https://github.com/chinoll/VPet-API

**Comment by LorisYounger** [comment]
编程模式后面没搞了, 还是直接代码插件比较方便,没必要为一种功能加两种
实在不行社区也会自己长出来的(eg: 前面的httpapi), 我就不做这方面了
