### ISSUE TITLE
是否可以调用第三方gpt的api？

### ISSUE THREAD

**Issue by Joackk** [LorisYounger/VPet#125]
似乎只有这两个可以选
![image](https://github.com/LorisYounger/VPet/assets/45162558/d97c2f17-e573-41f2-a860-111eb857ea04)
这里我在chatGPT设置里使用gpt4free搭建的接口，他会提示api调用失败
![image](https://github.com/LorisYounger/VPet/assets/45162558/93b655d6-78a4-4743-b0c9-287df393d7b8)
但是在脚本和其他软体中调用是正常的
![image](https://github.com/LorisYounger/VPet/assets/45162558/e1b677c2-95ca-44cc-82ef-36945b30690b)
这是什么情况哇？

**Comment by LorisYounger** [comment]
一般出现这种问题,是你的格式和chatgpt的官方api对不上
我用的是一对一一一对应的, 如果有不同的参数和值, 就会报错坏掉.
参见 #79
