### ISSUE TITLE
模組的格式文檔支持

### ISSUE THREAD

**Issue by xiao-e-yun** [LorisYounger/VPet#129]
我想為 VPet 提供一個模組製作工具，但缺少相關的格式和命名規則(關於Core/Pet的資料夾)，能否提供簡易的文檔來供臨時參考。

**Comment by LorisYounger** [comment]
在steam社区指南里面有简单的文档参考
不过mod制作器正在制作中,见 https://github.com/LorisYounger/VPet.Plugin.Demo

**Comment by xiao-e-yun** [comment]
可以將steam指南標注在README.md上嗎，這應該會讓更多人看到
