### ISSUE TITLE
System.NullReferenceException: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by zhuhiki** [LorisYounger/VPet#133]
### ************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 VPet_Simulator.Core.Main.Display(IGraph graph, Action EndAction)
   在 VPet_Simulator.Core.Main.DisplayNomal()
   在 VPet_Simulator.Windows.MainWindow.<>c__DisplayClass118_0.<GameLoad>b__25(Object x, EventArgs y)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

###  启动后人物不会立刻出现在屏幕上。似乎在人物做出第一个动作时才会出现

**Comment by LorisYounger** [comment]
没看懂, 是如何触发的吗?

**Comment by zhuhiki** [comment]
就是一开始人物不会出现，然后我就点击重置状态的时候会弹出这个报错，然后等他播放动作时人物才会出来(比如下蹲，爬行)或者在开发控制台播放时会出现

> 没看懂, 是如何触发的吗?

**Comment by LorisYounger** [comment]
经过复盘,我觉得不是等待导致的问题,而是另一种系统Fips缺失导致的问题
![UE`}KD1HL0%`VWW1$DCGLC8](https://github.com/LorisYounger/VPet/assets/34806646/339b5f84-0cca-4414-a7ad-28eecd837c9b)
![)P LGNDJ%9{3U2C0SBK{K4R](https://github.com/LorisYounger/VPet/assets/34806646/e1204b97-bc3d-4ae9-bedd-09be099fd32b)
![DJ9D}J)F_59$%_{FTA(%K`2](https://github.com/LorisYounger/VPet/assets/34806646/40b0d774-24f7-4740-a542-309bc9160c7a)
https://blog.csdn.net/m0_46868092/article/details/117436852
操作到第五部分就行
