### ISSUE TITLE
[bug]生病后仍然继续工作

### ISSUE THREAD

**Issue by LingShi991123** [LorisYounger/VPet#138]
可以看到，我家桌宠非常努力，即使生病了还在坚持直播（正巧在玩缺氧（雾））
![1](https://github.com/LorisYounger/VPet/assets/96658974/ea18bd1b-dd2e-4b62-9c28-c7355d007358)

**Comment by LingShi991123** [comment]
另外，桌宠在生病的情况下还会做出其他动作，例如坐下，不知道是不是bug

**Comment by zhangjingxian1998** [comment]
令人感叹

**Comment by Naduw** [comment]
我的是在工作的时候睡觉，很好，我养的孩子跟我一个样啊

**Comment by wubostc** [comment]
怎么生病啊？？

**Comment by yhs233** [comment]
不能买药自己吃吗
