### ISSUE TITLE
變數名稱不好

### ISSUE THREAD

**Issue by xiao-e-yun** [LorisYounger/VPet#139]
https://github.com/LorisYounger/VPet/blob/351d1e59b11a5854d8c998abe5ffb2b5a7ceaf7c/VPet-Simulator.Windows.Interface/Mod/ClickText.cs#L53

**Comment by LorisYounger** [comment]
不是, 只是整两个DayTime会冲突的, 也懒得整Daytime,太迷惑性了, 所以另外造的词
