### ISSUE TITLE
有计划支持其他语言大模型的api接入嘛

### ISSUE THREAD

**Issue by NekoMirra** [LorisYounger/VPet#14]
有计划支持其他语言大模型的api接入嘛，比如国内的讯飞星火，文心一言，国外的claude等等

**Comment by LorisYounger** [comment]
目前没有相关计划,以开发桌宠本体为主.
不过桌宠支持创意工坊和mod插件,开发者可以自己添加更多API

**Comment by LorisYounger** [comment]
计划使用一种通用的JSON读取来适应和接入所有API

**Comment by LorisYounger** [comment]
提供预设/创意工坊预设,就算不会写接入方法/看不到API结构的玩家也可以通过使用预设使用其他模型

**Comment by LorisYounger** [comment]
已添加代码插件方式添加API接口,剩下的创意工坊会自己长出来的

**Comment by NekoMirra** [comment]
好棒，感谢大佬！

**Comment by Talentjoe** [comment]
> 已添加代码插件方式添加API接口,剩下的创意工坊会自己长出来的

回旋镖打到我了（
果然是会长出来的：）

快加聊天的流式传输接口
