### ISSUE TITLE
info.lps 的 PetName 無法被正確使用

### ISSUE THREAD

**Issue by xiao-e-yun** [LorisYounger/VPet#140]
https://github.com/LorisYounger/VPet/blob/1611b6c5eb68a5845f36b89200dbdca110199b08/VPet-Simulator.Windows/WinDesign/winGameSetting.xaml.cs#L816
isChangeName 應該從 `==` 換為 `!=`
導致下方代碼只在名字相同才執行
https://github.com/LorisYounger/VPet/blob/1611b6c5eb68a5845f36b89200dbdca110199b08/VPet-Simulator.Windows/WinDesign/winGameSetting.xaml.cs#L822-L828

**Comment by LorisYounger** [comment]
PetName 一直被使用过, 比如说默认的那个萝莉斯, 以及切换的时候自动换名字
![image](https://github.com/LorisYounger/VPet/assets/34806646/a9a1b014-2751-4ead-9f21-2c21a6794417)

**Comment by xiao-e-yun** [comment]
ischangename 寫錯了，我在測試時都沒切換成功過 (切換成petname#胡桃)
![image](https://github.com/LorisYounger/VPet/assets/67814228/f4c5e1bc-9c82-43c8-b716-ca7d67c4277d)

**Comment by LorisYounger** [comment]
的确有这个bug, 不过错误不是 ischangename, 是没应用到最新皮肤名字导致的, 现已修复 https://github.com/LorisYounger/VPet/commit/2e16fa04b1d41adbb13c430e14991fbe15aefe6b

**Comment by xiao-e-yun** [comment]
那應該改成 isDefaultName 吧
