### ISSUE TITLE
工作超模檢測在極端數值下似乎會失效

### ISSUE THREAD

**Issue by xiao-e-yun** [LorisYounger/VPet#143]
![image](https://github.com/LorisYounger/VPet/assets/67814228/10d931d0-c95c-4f5a-845f-2f4817a97a73)

https://github.com/LorisYounger/VPet/blob/a80681683c711a3c86c5834d544661a561c3ceb0/VPet-Simulator.Windows.Interface/ExtensionFunction.cs#L17-L28

**Comment by LorisYounger** [comment]
之前有个负数会失效,这个后面会修,见 #126   極端數值有哪些?

**Comment by LorisYounger** [comment]
不小心按错了, 如果极端数值是正数,我再研究下看看

**Comment by xiao-e-yun** [comment]
應該重複 #126 了，rel  > 2 ||  rel < 0 就可以解決了
![image](https://github.com/LorisYounger/VPet/assets/67814228/39830f19-305b-4a9e-936d-074090729425)
