### ISSUE TITLE
希望能给出LPS更具体的文法定义

### ISSUE THREAD

**Issue by cactusBalll** [LorisYounger/VPet#145]
比如eBNF文法？文档好像和实际情况不太一致，现在不太能看出什么样的文件被parse进来会是什么样的结构，也不太清楚具体应该怎么写，只能照着已有的文件抄。这大概不利于Plugin使用LPS。

**Comment by LorisYounger** [comment]
可以简单参考下 https://github.com/LorisYounger/LinePutScript 的ReadMe
