### ISSUE TITLE
使用时的问题

### ISSUE THREAD

**Issue by anheye** [LorisYounger/VPet#149]
爬行问题：我是习惯把桌宠放屏幕边缘，但遗憾的是，桌宠爬行结束后，有时会导致桌宠一部分在屏幕内，一部分在屏幕外，偶尔甚至会出现由于鼠标点不到头，以至于无法拎起来移动的情况，只能关闭重开的情况，建议设置一个移动边界，
打字问题：聊天框打字很容易打到一半消失，
购买食物翻页问题：当我购买食物时，点到正餐第三页，然后，切换到药品，此时处于药品的第三页而非第一页（前提时药品有第三页）。

**Comment by Guess560** [comment]
您好，右键管理员运行后显示系统找不到指定目录。这样怎么办呢？

**Comment by anheye** [comment]
> 您好，右键管理员运行后显示系统找不到指定目录。这样怎么办呢？

抱歉，您似乎问错人了。我没遇到过这个问题，不太清楚

**Comment by Guess560** [comment]
好的，谢谢哈

**Comment by anheye** [comment]
> 菜单栏中有个桌宠的菜单,右键选择重置位置就可以居中 打字消失修复过了,只要有字就不会消失,我回头检查下有没有给API用上 翻页 见#87

打字时还是，会消失

**Comment by LorisYounger** [comment]
> > 菜单栏中有个桌宠的菜单,右键选择重置位置就可以居中 打字消失修复过了,只要有字就不会消失,我回头检查下有没有给API用上 翻页 见#87
> 
> 打字时还是，会消失

刚刚才推上去的程序

**Comment by LorisYounger** [comment]
其实打字本来就不会消失,我也不知道为啥会消失,可能和不同输入法有关系. 我用搜狗的输入法是不会消失的
不过之前打了个补丁, 如果聊天框里面有字,就不会触发消失

**Comment by anheye** [comment]
> 其实打字本来就不会消失,我也不知道为啥会消失,可能和不同输入法有关系. 我用搜狗的输入法是不会消失的 不过之前打了个补丁, 如果聊天框里面有字,就不会触发消失

了解，我还以为是之前的那个更新，我是用微软自带的双排输入法的
