### ISSUE TITLE
【编译错误】“IGraph.IRunImage”: 接口不能声明类型

### ISSUE THREAD

**Issue by Mundi-Xu** [LorisYounger/VPet#15]
错误	CS0524	“IGraph.IRunImage”: 接口不能声明类型	VPet-Simulator.Core	VPet\VPet-Simulator.Core\Graph\IGraph.cs	57

引入commit: 3a5ac776
https://github.com/LorisYounger/VPet/blob/b92d0280bd750d70410b8281d4e255166dd34d02/VPet-Simulator.Core/Graph/IGraph.cs#L57

**Comment by LorisYounger** [comment]
请使用最新版本的 VisualStudio 2022
可能是旧版本VS导致的不兼容问题, 我这边编译没有问题
