### ISSUE TITLE
鼠标无法拖动宠物

### ISSUE THREAD

**Issue by EXarchive** [LorisYounger/VPet#151]
刚购买打开时可以拖动，后来逐渐不灵敏，最后长按鼠标没有任何反应，重启安装和设置没有用

**Comment by LorisYounger** [comment]
设置里可以设置长按时间
另外拖动是有区域范围的,大概在头,脖子,衣领哪一块

**Comment by EXarchive** [comment]
不行

**Comment by LorisYounger** [comment]
那估计是订阅了啥mod乱动把抚摸范围改了,建议取消mod再试试

**Comment by EXarchive** [comment]
已经试过把所有mod卸载并且重装软件了

**Comment by LorisYounger** [comment]
拖动时间设置的是多少,默认是0.5秒拖动,设置里可以设置长按时间

**Comment by EXarchive** [comment]
设置的0.05，但是这个不影响拖动问题吧

**Comment by EXarchive** [comment]
已经解决了，原因是一个创意工坊的AI补帧mod的bug并且卸载后还有残留
