### ISSUE TITLE
[BUG] 宠物向屏幕边缘移动会跑出屏幕外，只能重置状态

### ISSUE THREAD

**Issue by ESOU666** [LorisYounger/VPet#152]
1.3版本新bug：宠物向屏幕边缘移动会跑出屏幕外，只能重置状态

**Comment by LorisYounger** [comment]
我这边简单测试了下没啥问题, 是多屏幕吗? 是哪一个动作? 方向是什么?

**Comment by ESOU666** [comment]
单个屏幕，我把萝莉丝放在右上角没做互动，一段时间后她慢慢向右爬，爬出了屏幕

**Comment by ESOU666** [comment]
我看到steam上也有许多人报告了这个bug，就来github提一下，麻烦作者大大啦~

**Comment by LorisYounger** [comment]
你确定是1.3?
1.3是刚刚推上去的最新版本,已经修好了多屏幕等爬出屏幕外的问题了
而且我刚刚试了下,也没复现成功

**Comment by ESOU666** [comment]
是刚刚更新的1.3，我在两分钟前又触发这个bug了，我是win11 beta版，开了两个桌面，萝莉丝向右爬爬出了桌面1，但我也没在桌面2看到她。1.2版本她爬到屏幕边缘会顺着边缘攀爬下来的

**Comment by LorisYounger** [comment]
我检查了下设置相关代码应该是没问题的, 
@Hakoyu @YukkuriC 你们修的好像有问题, 群里也有反馈爬出去了, 大概都在右边的时候爬出去了, 单个屏幕

**Comment by YukkuriC** [comment]
试了下，屏幕缩放倍率不是100%的时候取的四边距离会错乱
应该是
* 萝莉自己的top跟left坐标乘以所在屏幕的倍率
* 屏幕外包矩形要除以自己的缩放倍率
以上两种可能之一

等周末俺有空再去查点文档pr一波
（莫非原来那个api已经计入了UI缩放）

**Comment by LorisYounger** [comment]
> 试了下，屏幕缩放倍率不是100%的时候取的四边距离会错乱 应该是
> 
> * 萝莉自己的top跟left坐标乘以所在屏幕的倍率
> * 屏幕外包矩形要除以自己的缩放倍率
>   以上两种可能之一
> 
> 等周末俺有空再去查点文档pr一波 （莫非原来那个api已经计入了UI缩放）

因为默认的那些API是包括了缩放倍率参数的

**Comment by LorisYounger** [comment]
不小心按错了

**Comment by LorisYounger** [comment]
> 试了下，屏幕缩放倍率不是100%的时候取的四边距离会错乱 应该是
> 
> * 萝莉自己的top跟left坐标乘以所在屏幕的倍率
> * 屏幕外包矩形要除以自己的缩放倍率
>   以上两种可能之一
> 
> 等周末俺有空再去查点文档pr一波 （莫非原来那个api已经计入了UI缩放）

我先滚回了, 后面你修的时候记得加回来

**Comment by YukkuriC** [comment]
坏消息：这问题还有点离谱
桌宠启动时屏幕缩放已经是150%跟启动后修改显示设置到150%是两个表现，而且前者还会影响排在它旁边的100%缩放屏幕的定位
我再查一波文档罢（悲

**Comment by LorisYounger** [comment]
已修复
