### ISSUE TITLE
有考虑做Mac版吗

### ISSUE THREAD

**Issue by justaLoli** [LorisYounger/VPet#153]
她真的好可爱，想在Mac上拥有
如果没有的话，我在试着边学边做
卑微的苹果用户要学会自己写喜欢的程序（哭

**Comment by fanxitong** [comment]
或许可以尝试提供一个Avalonia版本的 :)

**Comment by ColdRain-Moro** [comment]
试着用 wine 跑了一下 能跑但效果比较差😂
<img width="1512" alt="image" src="https://github.com/LorisYounger/VPet/assets/69996135/99ffc5e6-46d4-4b7e-abfc-aaf0f2903efa">

**Comment by freeze-dolphin** [comment]
使用Steam自带的Proton尝试跑在linuxmint上，也是出现了黑边的情况
貌似其他功能都挺好的，就这一个问题
![image](https://github.com/LorisYounger/VPet/assets/40729044/fe17bcbc-e6c4-454c-b450-4e71df22ae46)

**Comment by justaLoli** [comment]
如果有办法直接移植就太好了qaq
我在试着自己写，不过没有经验，写的特别混乱...
https://github.com/justaLoli/VPet-Mac
<img width="1299" alt="CleanShot 2023-09-03 at 18 11 50" src="https://github.com/LorisYounger/VPet/assets/92238102/24d33f54-2439-40f7-858e-71981c8838e2">
