### ISSUE TITLE
[建议] 互动栏执行动作时希望隐藏储物柜按键，等鼠标移到桌宠附近时再显现

### ISSUE THREAD

**Issue by ESOU666** [LorisYounger/VPet#155]
进行互动栏中的动作时，软件左边会出现一个储物柜按键，每次点击后会轮换显示当前互动时长，剩余时间，累计收益，不显示信息。但当它不显示信息的时候，这个按钮仍然会在屏幕上，非常影响观感。希望可以在不显示信息时，鼠标离开桌宠模拟器后就隐藏按钮，等鼠标移动到桌宠模拟器上时再显示该按钮。

**Comment by ESOU666** [comment]
就是这个按钮
![image](https://github.com/LorisYounger/VPet/assets/104335768/13b313a5-fa50-40d2-b9e7-ed6b01fa6e6c)

**Comment by LorisYounger** [comment]
不显示岂不是后面就找不到了,下次我可以更新下让这个按钮变透明

**Comment by ESOU666** [comment]
鼠标离开桌宠时隐藏按钮，鼠标移到桌宠程序上方时显示按钮，这样就不怕找不到了
