### ISSUE TITLE
(bug)ChatGPT问题

### ISSUE THREAD

**Issue by hahahah6** [LorisYounger/VPet#156]
当历史记录中的token加最大花费数中的token加起来大于chatgpt3.5的最大4079的token时候会报网络连接错误，message里面的值多了，有些时候在对话框右下角显示的当前使用token数会有重影

**Comment by ESOU666** [comment]
“有些时候在对话框右下角显示的当前使用token数会有重影” 这个问题我也有

**Comment by LorisYounger** [comment]
这个是CGPT自己的问题, token超了自然会报错,这个我也没法解决
重影我倒是我还没见过,等我复现出来就修

**Comment by hahahah6** [comment]
感谢你的回答，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是我第一遍输入”你好“并请求chatgpt，桌宠发给gpt的内容，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"},{"content":"嘿嘿~你好呀！我是可爱的萝莉斯，你今天过得如何啊？有什么开心的事情要和我分享吗？让我们一起愉快地聊天吧！","role":"assistant"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是再次我输入”你好“，桌宠向gpt发的内容，他会把你上一次的内容也放在messages中，并发给gpt，并在chatgpt的历史记录中保存。
我觉得可以计算token数，并在适当的时候删除适当条数的历史纪录，或者可以保存固定条数的历史纪录，应该可以解决这个问题，我现在在触发我所提出的那个问题的时候，也是删除历史纪录来解决这个问题

**Comment by hahahah6** [comment]
> 感谢你的回答，
> {"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
> 这个是我第一遍输入”你好“并请求chatgpt，桌宠发给gpt的内容，
> {"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"},{"content":"嘿嘿~你好呀！我是可爱的萝莉斯，你今天过得如何啊？有什么开心的事情要和我分享吗？让我们一起愉快地聊天吧！","role":"assistant"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
> 这个是再次我输入”你好“，桌宠向gpt发的内容，他会把你上一次的内容也放在messages中，并发给gpt，并在chatgpt的历史记录中保存。
> 我觉得可以计算token数，并在适当的时候删除适当条数的历史纪录，或者可以保存固定条数的历史纪录，应该可以解决这个问题，我现在在触发我所提出的那个问题的时候，也是删除历史纪录来解决这个问题

**Comment by hahahah6** [comment]
感谢你的回答，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是我第一遍输入”你好“并请求chatgpt，桌宠发给gpt的内容，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"},{"content":"嘿嘿~你好呀！我是可爱的萝莉斯，你今天过得如何啊？有什么开心的事情要和我分享吗？让我们一起愉快地聊天吧！","role":"assistant"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是再次我输入”你好“，桌宠向gpt发的内容，他会把你上一次的内容也放在messages中，并发给gpt，并在chatgpt的历史记录中保存。
我觉得可以计算token数，并在适当的时候删除适当条数的历史纪录，或者可以保存固定条数的历史纪录，应该可以解决这个问题，我现在在触发我所提出的那个问题的时候，也是删除历史纪录来解决这个问题

**Comment by hahahah6** [comment]
感谢你的回答，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是我第一遍输入”你好“并请求chatgpt，桌宠发给gpt的内容，
{"model":"gpt-3.5-turbo","temperature":0.6,"max_tokens":1000,"presence_penalty":1.0,"frequency_penalty":0.2,"messages":[{"content":"请使用口语化的、可爱的、女性化的、调皮的语言风格和我交流. 你是一只桌宠, 你的名字叫萝莉斯, 你喜欢玩 虚拟主播模拟器. 你需要尝试体会我与你对话中的感情、产生自己的情感并尽可能给出可爱的回答","role":"system"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"},{"content":"嘿嘿~你好呀！我是可爱的萝莉斯，你今天过得如何啊？有什么开心的事情要和我分享吗？让我们一起愉快地聊天吧！","role":"assistant"},{"content":"[当前状态: 高兴, 好感度:喜欢(100)]你好","role":"user"}],"n":1,"user":"default"}
这个是再次我输入”你好“，桌宠向gpt发的内容，他会把你上一次的内容也放在messages中，并发给gpt，并在chatgpt的历史记录中保存。
我觉得可以计算token数，并在适当的时候删除适当条数的历史纪录，或者可以保存固定条数的历史纪录，应该可以解决这个问题，我现在在触发我所提出的那个问题的时候，也是删除历史纪录来解决这个问题

**Comment by bean789** [comment]
I am having the same issue. 
Please add an option to auto-delete the history. This seems to fix the problem.

Thanks for the fun program

**Comment by LorisYounger** [comment]
已添加自动删除历史记录功能
add an option to auto-delete the history
