### ISSUE TITLE
[BUG] 退出重进后动画失效，人物变扁向右平移

### ISSUE THREAD

**Issue by ESOU666** [LorisYounger/VPet#157]
很多动画都会变成这样，
![image](https://github.com/LorisYounger/VPet/assets/104335768/ca89553a-e315-48bd-992a-0c42ca56bca2)
![image](https://github.com/LorisYounger/VPet/assets/104335768/297b7e6a-e9ac-440e-a75f-1b81f44b2b29)
![image](https://github.com/LorisYounger/VPet/assets/104335768/bc2bfbe0-22ba-48bd-a426-073716621bcb)
无论怎么重启应用都没用

**Comment by hahahah6** [comment]
更新一下，已经好了
