### ISSUE TITLE
 语言

### ISSUE THREAD

**Issue by uwu00jr** [LorisYounger/VPet#16]
有支持其他语言的计划吗？

**Comment by uwu00jr** [comment]
对于翻译，我指的是文本

**Comment by LorisYounger** [comment]
有, 预计会出个文本点对点替换的方式进行软件翻译,支持MOD和创意工坊

**Comment by LorisYounger** [comment]
不过光UI还好,如果是说话啥的文本量就比较大比较麻烦

**Comment by FunJoo** [comment]
> 不过光UI还好,如果是说话啥的文本量就比较大比较麻烦

用chatgpt翻译一步到位 (x
说到chatgpt，倒是可以用chatgpt给桌宠赋予新生命 (x

**Comment by LorisYounger** [comment]
语言支持已经完成, 请参见翻译文档
https://github.com/LorisYounger/VPet/tree/main/VPet-Simulator.Windows/mod/0000_core/lang
