### ISSUE TITLE
[建议]能否支持智谱ai的chatglm以稳定连接

### ISSUE THREAD

**Issue by gb16001** [LorisYounger/VPet#161]
本来想自己改的，但是仔细研究了一番感觉我做不到。
[chatglm API文档](https://open.bigmodel.cn/dev/api#http)

个人认为，改chatglm API的难点就在于
1.目前它没有直接支持.net的包，现在只对python支持良好
2.他的鉴权方式是加密密钥，好像是要把密钥关联时间加密成一次性密码

所以能不能请大佬们考虑考虑？

**Comment by LorisYounger** [comment]
计划使用一种通用的JSON读取来适应和接入所有API, 见 #14
