### ISSUE TITLE
建議, 能不能兼容POE?

### ISSUE THREAD

**Issue by zelda0079** [LorisYounger/VPet#162]
大陸和香港都被禁了CHATGPT
更別說CHATGPT ACCOUNT去申請API
而且API用量好像還要錢
能不能兼容POE?
像數位夥伴就能做到
https://store.steampowered.com/app/2488350/
而且穩定性也高
比FAKEGPT這類然後配不知道什麼的集合KEY穩定太多

**Comment by LorisYounger** [comment]
计划使用一种通用的JSON读取来适应和接入所有API, 见 #14
