### ISSUE TITLE
聊天框位置问题

### ISSUE THREAD

**Issue by MooseDK** [LorisYounger/VPet#163]
当前使用时，选项式对话框会在人物形象的头部出现，会对人物造成遮挡，比较影响美观
可否添加设置，选择对话框的出现位置

**Comment by LorisYounger** [comment]
对话框位置已经是顶部了,再往上整就会把桌宠顶下去
可以在设置里关掉对话框显示,以及再次右键对话框也会自行关闭

**Comment by MooseDK** [comment]
感谢回复(●'◡'●)
