### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by liao128** [LorisYounger/VPet#166]
建议增加动作，长按拖动时，晃几下桌宠会晕

**Comment by StarWishNya** [comment]
+1+1刚刚想上来提一个的喵

**Comment by LorisYounger** [comment]
加起来好麻烦的说,还需要做更多检测和新动画啥的,好麻烦的说
提起动画是强制要做的,这里内容加多了mod开发者做起来就太麻烦了. 就不加了
