### ISSUE TITLE
[bug]桌宠原地走动

### ISSUE THREAD

**Issue by kinglingmk1** [LorisYounger/VPet#168]
这是我的桌宠，开机自启不久就原地攀爬甚至原地自由落体。

https://github.com/LorisYounger/VPet/assets/128010679/6418ec14-6e5c-49a3-abbb-684b96539beb

**Comment by kinglingmk1** [comment]
话说我的设定已经关闭启用桌宠移动，不知道为什么还会触发这个动画

**Comment by LorisYounger** [comment]
关了移动也会有动画的,只是不动而已
