### ISSUE TITLE
我在Stream 上安装使用了,我现在不知道如何在windows桌面上 拖拽人物到任意地方

### ISSUE THREAD

**Issue by goodluckily** [LorisYounger/VPet#17]

**Comment by LorisYounger** [comment]
可以在图标栏右键查看操作教程
![image](https://github.com/LorisYounger/VPet/assets/34806646/a442009a-d26c-41ac-95d4-0f6a9014f484)
或查看 [虚拟桌宠模拟器 使用教程
](https://github.com/LorisYounger/VPet/blob/main/Tutorial.md)

**长按头/身子 提起进行移动**
可在设置中长按时间
![tut5](https://github.com/LorisYounger/VPet/raw/main/Tutorial.assets/tut5.gif)
