### ISSUE TITLE
[建议]让宠物在无聊的时候自动随机学习/工作/玩耍，或给爬、蹲下等状态添加描述

### ISSUE THREAD

**Issue by TizzureOne** [LorisYounger/VPet#170]
学习工作玩耍都行，感觉不给他安排事就一直发呆好呆啊
倒是会动，但状态会显示在无所事事或者在闲逛，感觉就很呆

**Comment by LorisYounger** [comment]
无聊的时候会自己乱动的,例如爬,蹲下等等
状态显示啥的我后续看看要不加点行动的时候切下描述

**Comment by Joackk** [comment]
希望后续能再多加点会自动触发的动作

**Comment by wubostc** [comment]
支持支持。

**Comment by LorisYounger** [comment]
最新更新已添加更多描述, 至于自己工作干活啥的我不会去实现的, 有自动吃饭送礼就行了
https://github.com/LorisYounger/VPet/commit/b3c34106a05ecbf3e7cfdb0f27c340fb89df25c6
