### ISSUE TITLE
触摸板使用快捷小标左键无法点击

### ISSUE THREAD

**Issue by Joackk** [LorisYounger/VPet#172]
具体情况就是在开启一会后，触摸板点左键，切换鼠标穿透点击无效，但是点两下它又可以他会切换穿透又切回来，点一下就不行，这种状态下用触摸板点右键，再点左键会正常，鼠标状态一切正常

**Comment by LorisYounger** [comment]
可能是触摸板不灵敏或者兼容驱动等导致的,我用触摸板玩PRC的时候也会需要点两下当1下点
