### ISSUE TITLE
开启鼠标穿透后不置顶

### ISSUE THREAD

**Issue by Joackk** [LorisYounger/VPet#173]
那个快捷图标的左键单击后，开启鼠标穿透，但是并没有右键点击取消置顶的情况，会出现下图中这样
![image](https://github.com/LorisYounger/VPet/assets/45162558/4f5f3152-0923-4f95-bd3c-62c9a6a2a90b)
我的任务栏设置了自动隐藏模式，不开鼠标穿透状态是这样的，正常置顶
![image](https://github.com/LorisYounger/VPet/assets/45162558/504186d7-514f-4470-aef0-9bf2d36f1493)
此外还遇到了开启鼠标穿透后置顶也跟着关闭了，但是后续都没有遇到

**Comment by LorisYounger** [comment]
鼠标穿透的代码实现比较玄学,我自己也看不到咋做到的, 能用就行, 小bug不需要在意这些细节(
