### ISSUE TITLE
能否简单描述一下图片文件的命名和路径规则

### ISSUE THREAD

**Issue by xiaodiyun** [LorisYounger/VPet#176]
我在尝试用python在mac端做简单复刻，这意味着我必须依照这个项目的规则来读取图片。
比如ABC分别对应循环开始，循环中间，循环结束之类的。那图片名字有什么意义吗？比如 _000_250.png 意思是序号0的图片持续250毫秒？"~"前缀是什么意思？
能否提供更多类似逻辑上的说明，来方便其他平台做复刻或者迁移

<img width="859" alt="image" src="https://github.com/LorisYounger/VPet/assets/18534962/0e7fbffd-fdc7-4fb3-9c40-2212d35285a3">

**Comment by LorisYounger** [comment]
任意名称_顺序_持续时间(毫秒).png
详情可以参见这个 https://steamcommunity.com/sharedfiles/filedetails/?id=3021412497
