### ISSUE TITLE
启动后卡在CGPT

### ISSUE THREAD

**Issue by chunyukanhai** [LorisYounger/VPet#18]

**Comment by LorisYounger** [comment]
那就是连不上我的服务器,那你只能用自己的API了,一般显示在加载中,就是没连上我的服务器,卡住了
![3{QO8{(5%7O}{N8H26NO3J0](https://github.com/LorisYounger/VPet/assets/34806646/065a9d4f-cb1e-4207-880a-c0aca7f19012)
如果要使用自己的API,可以在设置里设置->使用从ChatGPT申请的API接口
![image](https://github.com/LorisYounger/VPet/assets/34806646/839be802-6def-4022-b260-5b242a17e55f)

**Comment by LorisYounger** [comment]
经测试,是自动备份引发的错误,现已修复, 请更新后重试看看还有没有卡在启动界面的错误
> 原来你们说的卡在加载cgpt是这个,我还以为是弹窗里的那个呢
> 反馈的时候可以附个图(
> 功能太多不知道是说哪里的
