### ISSUE TITLE
宠物在部分时候突然置顶失效

### ISSUE THREAD

**Issue by Xbaishu** [LorisYounger/VPet#182]
宠物在部分时候突然置顶失效，或者被隐藏，需要在托盘打开设置等窗口类选项才能将宠物显示出来，否则无宠物本体，但是tts生成的语音有效且会发声
设备
Win10专业版 22H2
操作系统内部版本 19045.3324
体验 Windows Feature Experience Pack 1000.19041.1000.0
处理器i9 10900kf
GPU1 1080
GPU2 1070
RAM 48G

**Comment by LorisYounger** [comment]
打开桌宠附带的其他页面时会自动关掉桌宠的置顶防止挡住,见 #20
