### ISSUE TITLE
关于买买买食物之后有效度显示的问题

### ISSUE THREAD

**Issue by YukkuriC** [LorisYounger/VPet#186]
1. 没有即时刷新，需手动触发列表刷新（翻页/切分类等）
![img1](https://github.com/LorisYounger/VPet/assets/34098703/336ce8a4-4588-4307-ad03-fcdcab13633d)
这边能查到有触发food的状态更改事件
![img2](https://github.com/LorisYounger/VPet/assets/34098703/0b417a18-a03e-44d1-80eb-da3c69edd6cb)
但是项目中妹有响应这个事件的地方
2. 实际生效有效度和显示有效度有差别
https://github.com/LorisYounger/VPet/blob/ad5d40e57b2876950b5869eabe0a3f17647304f8/VPet-Simulator.Windows.Interface/Mod/Food.cs#L197-L199
https://github.com/LorisYounger/VPet/blob/ad5d40e57b2876950b5869eabe0a3f17647304f8/VPet-Simulator.Windows/MainWindow.cs#L430

**Comment by LorisYounger** [comment]
如果你搞懂了,那就PR吧

**Comment by YukkuriC** [comment]
搞不懂（悲
第一个俺还没找到渲染食物元素的xaml在哪，以及需要考量一些关于释放、重复更新、etc.乱七八糟的事情
第二个得staff来拍板是哪边向哪边同步

**Comment by Mochengvia** [comment]
@YukkuriC 我看到了这句代码
```
item.NotifyOfPropertyChange("Eattime");
```
但是Food类里面并没有Eattime这个属性，没懂是要做什么

**Comment by LorisYounger** [comment]
> @YukkuriC 我看到了这句代码
> 
> ```
> item.NotifyOfPropertyChange("Eattime");
> ```
> 
> 但是Food类里面并没有Eattime这个属性，没懂是要做什么

这个Eattime是外置的参数, 指的是喜好度/有效度, 使用在

https://github.com/LorisYounger/VPet/blob/main/VPet-Simulator.Windows/WinDesign/winBetterBuy.xaml.cs#L50-79

要更新的是 `public string Description` 内容,

https://github.com/LorisYounger/VPet/blob/main/VPet-Simulator.Windows.Interface/Mod/Food.cs#L115-138

**Comment by LorisYounger** [comment]
> 另外，我看Food这个类里面的属性似乎都没实现NotifyPropertyChange，所以不会自动更新前端 要手动更新的话这样调用：
> 
> ```
> item.NotifyOfPropertyChange(() => nameof(Food.Desc));
> 或者
> item.NotifyOfPropertyChange("Desc");
> ```
> 
> 只能调用里面有的属性

用 `item.NotifyOfPropertyChange(() => nameof(Food.Desc));` 修好了
用`item.NotifyOfPropertyChange("Desc");`和`item.NotifyOfPropertyChange(nameof(Food.Desc));`这两个都不行

WPF真神奇

**Comment by YukkuriC** [comment]
WPF真神奇
