### ISSUE TITLE
希望兼容wine或者直接支持Linux

### ISSUE THREAD

**Issue by CleMooling** [LorisYounger/VPet#187]
Linux的Steam上无法通过Proton兼容工具运行游戏。

**Comment by LorisYounger** [comment]
理论上是支持wine的, 都是微软原生库和亲儿子
至于支持linux, 我并不会这方面开发

**Comment by CleMooling** [comment]
很抱歉并不兼容wine（在Linux版Steam wine proton和原生wine下均不能启动，原生wine不能启动不知道是不是因为绕过了Steam的原因）另外wine是Linux下运行Windows应用的一个开源兼容层，因此使用微软原生库并不代表能正常在wine下启动。
已经尝试在原生wine环境下安装了.NET 6.0-8.0，VC运行库，不知道可能还缺什么组件





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月8日(周五) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LorisYounger/VPet] 希望兼容wine或者直接支持Linux (Issue #187)




 
理论上是支持wine的, 都是微软原生库和亲儿子
 至于支持linux, 我并不会这方面开发

**Comment by freeze-dolphin** [comment]
Steam用Proton Experimental可以跑
但是会有黑背景

**Comment by heipiao233** [comment]
实测用Proton Experimental也跑不了，但是Wine安装wine-mono后可以跑

**Comment by freeze-dolphin** [comment]
> 实测用Proton Experimental也跑不了，但是Wine安装wine-mono后可以跑

还会有黑边吗 (类似 #153 里的)

**Comment by heipiao233** [comment]
> > 实测用Proton Experimental也跑不了，但是Wine安装wine-mono后可以跑
> 
> 还会有黑边吗 (类似 #153 里的)

有
