### ISSUE TITLE
身体触摸判定无法达成

### ISSUE THREAD

**Issue by saigouizayoi** [LorisYounger/VPet#189]
如题，摸头很容易触发。

但是身体的判定区域始终没有反应，从肩膀一路到鞋子，所有位置都点过，但是触摸判定数量没有增加。
（观察次数是在steam成就统计上看的）

**Comment by SakuraiFang** [comment]
我也是，触摸能消耗体力恢复心情，但是team成就不再涨了，之前也没注意，现在发现不涨了。

**Comment by LorisYounger** [comment]
如果丢失/损毁过设置,也会导致不涨, 统计储存在设置里,并不是在统计里

**Comment by SakuraiFang** [comment]
我纯绿色玩家啊，无mod无任何修改，但是好像是重装过一次系统之后就这样了。是只重装了系统，steam和游戏都是原来的。让我非常困惑，其他的成就都能增长，比如等级好感度。

**Comment by LorisYounger** [comment]
设置丢了导致的, 未来会吧统计做到存档里和存档一起备份

**Comment by SakuraiFang** [comment]
麻烦您了，非常感谢，还请您尽快修复哦。

**Comment by LorisYounger** [comment]
新存档系统已经实现 统计挪到存档里 功能

**Comment by SakuraiFang** [comment]
> 新存档系统已经实现 统计挪到存档里 功能
 感谢大佬修复，steam上看到大佬身体抱恙，还请大佬多保重身体！
一点小小的变化，之前steam成就的触摸身体数值是353，刚才触摸了一下再看steam成就，成171，也就是降了之后再触摸会上升，虽然无伤大雅还是和您报告一下。
