### ISSUE TITLE
建议桌宠移动的时候鼠标移到桌宠上时停止移动

### ISSUE THREAD

**Issue by qiuzilu** [LorisYounger/VPet#19]
我知道，标题很长，不好断句，来构建一个情景吧：
桌宠口渴了，她语音提示您：太郎~啊不，主人~该喝药~不，该喝水了~
但是，由于您开了“桌宠移动”这个功能。
而她恰好在移动。
她飞啊飞，飞完又在地上爬，爬完又走了几圈。
而您，由于手速不够快，无法够到移动的菜单，不能买饮料给她喝
您，只能默默地等她爬完走完飞完，再给她喂。

**Comment by qiuzilu** [comment]
x这个波浪线怎么变成删除线了

**Comment by qiuzilu** [comment]
只是暂停动画就行，就像桌宠在偷偷摸摸做事突然被发现的那种感觉

**Comment by qiuzilu** [comment]
刚刚发现了一个bug，在爬行动画执行的时候无法进行拖拽动作

**Comment by heerheer** [comment]
> 只是暂停动画就行，就像桌宠在偷偷摸摸做事突然被发现的那种感觉

然后做一个摸鱼被发现的动画！爬着爬着被吓了一跳（

**Comment by LorisYounger** [comment]
点击桌宠桌宠时会自动从移动状态打断退出
