### ISSUE TITLE
希望能够添加Mac版

### ISSUE THREAD

**Issue by st-small-shao** [LorisYounger/VPet#194]
正在尝试和开发者取得Mac版本的开发申请

**Comment by LorisYounger** [comment]
原来那个邮件是你发的,你邮箱有问题,我根本没法给你发邮件
> ![image](https://github.com/LorisYounger/VPet/assets/34806646/44e8b425-b2a5-4f97-8cba-4367a05c4eb0)

回信内容如下

你好, 邵纪铭

开发mac版等各种版本并不需要我授权, 我目前也不会授权任何版本为官方版本
未来我可能会为开发/维护比较好的版本进行推荐, 但是并没有指定谁谁谁才能开发不同版本

感谢你对虚拟桌宠模拟器的支持
洛里斯杨远
