### ISSUE TITLE
可否將觸摸頭/身體的判斷次數間隔時間縮短?

### ISSUE THREAD

**Issue by zelda0079** [LorisYounger/VPet#198]
可否將觸摸頭/身體的判斷次數間隔時間縮短?

因為發現如果連點頭, 例如-40體力+20心情
系統只判斷為1次
如果等到-2體力+1心情消失才繼續點那就應該會算作是第2次
但這樣等真的很累很浪費時間

**Comment by LorisYounger** [comment]
没有必要其实,因为这个只算一次摸头
成就统计本来就是慢慢涨上去好看的, 一口气刷掉反而没意思
要改这个成就次数等等一起都要改的更多,不然一次性把所有摸头成就做完了,所以反而没差别
