### ISSUE TITLE
[Bug]在关闭桌宠并重新启动后，存档的哈希校验必然会失败，在读取其他存档再读取回来后恢复正常

### ISSUE THREAD

**Issue by NONAME-2121237** [LorisYounger/VPet#199]
如标题
![image](https://github.com/LorisYounger/VPet/assets/104999550/cc850721-f272-464e-b129-3f90dfd2ea5d)
就是这个校验（会影响非作弊者徽章）

**Comment by LorisYounger** [comment]
是统计检查到你之前用过负数钱之类的mod,给你删了hash验证了
但是没在读备份的时候加验证负数钱, 算是个中立的小漏洞,就懒得修了

**Comment by NONAME-2121237** [comment]
明白了（不过那个搬砖的mod真的好玩，这可不可以加个白名单的啥的）（我自己把数值改成一毛钱了）
![image](https://github.com/LorisYounger/VPet/assets/104999550/2b9e3452-efcc-412a-8c1b-65333b814c5d)
