### ISSUE TITLE
选项栏会遮挡说话栏

### ISSUE THREAD

**Issue by WinlCheng** [LorisYounger/VPet#201]
能把说话栏往上提一下吗，说话时左键点到就看不到桌宠说什么了

**Comment by LorisYounger** [comment]
没听懂,有附图吗

**Comment by WinlCheng** [comment]
> 没听懂,有附图吗

![屏幕截图 2023-09-13 115009](https://github.com/LorisYounger/VPet/assets/105507018/67b9335f-e3f0-4567-bb86-5ec48d2b2c48)

右键菜单点出来无法直接点击其他地点消失，这时候桌宠说话就挡住了

**Comment by LorisYounger** [comment]
再次右键就消失了,另外设置里可以把说话框置于下方
![image](https://github.com/LorisYounger/VPet/assets/34806646/4e38b3da-4c33-41b8-8115-067e2b0edeb4)
