### ISSUE TITLE
[Suggestions] 关于宠物状态的一些建议

### ISSUE THREAD

**Issue by YerongAI** [LorisYounger/VPet#202]
### 关于程序中数值的合理性

> 程序版本：v1.5

宠物中的心情、饱腹、口渴等状态应该优化一下。

就是说，个人觉得这里可以参考现实生活进行调整，现在是低于 80 后，饱腹、口渴就会显示为黄条，这怎么感觉都是不合理的。所谓干饭七分饱，个人觉得在 50 以上都应该是绿条，30-50 是黄条，低于 30 是红条比较合理。

要不作为强迫症真的每十几二十多分钟就要投喂一次，这个真的太频繁了。**不过可能也和我用的 MOD 有关系，这点会单独反馈给 MOD 作者**。

除了这个之外，还有就是心情，现阶段应该也是差不多的设置吧。个人感觉的话 60 以上都应该是好心情才对，现在好像低于 70 就给我嘟嘟嘴巴看得也是很不得劲。

希望作者大大能考虑一下这些建议啦，关于数值之类的合理性。要不养个赛博宠物比养个真的还难养 ಥ_ಥ

**Comment by chulianyuang** [comment]
小白表示认同

**Comment by ChaojuWang** [comment]
强烈赞同，另外，看代码打开自己买东西功能后饱食度口渴度低于75就开炫了，时时刻刻保持自己摘吃撑的状态，感觉有点不合理。

另建议增加吃撑的状态，饱食度超过阈值反而影响健康

**Comment by LorisYounger** [comment]
在1.10版本已经修过了,忘记关问题了
