### ISSUE TITLE
没有成功启动

### ISSUE THREAD

**Issue by Diend2023** [LorisYounger/VPet#203]
启动后宠物不显示：
![屏幕截图 2023-09-14 090425](https://github.com/LorisYounger/VPet/assets/103641773/e9a0a7e0-44c6-4f11-b781-2d913790fab9)

重置位置与状态或者退出桌宠：
![屏幕截图 2023-09-14 085735](https://github.com/LorisYounger/VPet/assets/103641773/1cd8e742-1d86-4867-8435-0fb3911402cf)

详细信息：
_有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentNullException: 值不能为 null。
参数名: uriString
   在 System.Uri..ctor(String uriString)
   在 VPet_Simulator.Core.PNGAnimation.<>c__DisplayClass33_0.<Run>b__1()
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 VPet_Simulator.Core.PNGAnimation.Run(Border parant, Action EndAction)
   在 VPet_Simulator.Core.Main.Display(IGraph graph, Action EndAction)
   在 VPet_Simulator.Core.Main.Display(String name, AnimatType animat, Action EndAction)
   在 VPet_Simulator.Core.Main.Display(GraphType Type, AnimatType animat, Action EndAction)
   在 VPet_Simulator.Core.Main.DisplayNomal()
   在 VPet_Simulator.Core.Main.DisplayToNomal()
   在 VPet_Simulator.Windows.MainWindow.<>c__DisplayClass125_0.<GameLoad>b__27(Object x, EventArgs y)
   在 System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.MenuItem.MenuItemData.Execute()
   在 System.Windows.Forms.Command.Invoke()
   在 System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
VPet-Simulator.Windows
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/VPet-Simulator.Windows.exe
----------------------------------------
PresentationFramework
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9176.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
VPet-Simulator.Windows.Interface
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/VPet-Simulator.Windows.Interface.DLL
----------------------------------------
VPet-Simulator.Core
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/VPet-Simulator.Core.DLL
----------------------------------------
Panuon.WPF
    程序集版本:1.0.2.0
    Win32 版本:1.0.2
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/Panuon.WPF.DLL
----------------------------------------
Panuon.WPF.UI
    程序集版本:1.1.15.8
    Win32 版本:1.1.15.8
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/Panuon.WPF.UI.DLL
----------------------------------------
LinePutScript
    程序集版本:1.5.0.0
    Win32 版本:1.5.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/LinePutScript.DLL
----------------------------------------
LinePutScript.Localization.WPF
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/LinePutScript.Localization.WPF.DLL
----------------------------------------
Facepunch.Steamworks.Win64
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/Facepunch.Steamworks.Win64.DLL
----------------------------------------
Microsoft.CSharp
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
PresentationFramework.Aero2
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationFramework-SystemXml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9037.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PresentationCore.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
UIAutomationTypes
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
PresentationFramework.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.8.9186.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
CSCore
    程序集版本:1.2.1.2
    Win32 版本:
    基本代码:file:///C:/Users/Admin/Desktop/VPet-main/VPet-Simulator.Windows/bin/x64/Debug/net462/CSCore.DLL
----------------------------------------
WindowsBase.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/WindowsBase.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。
_

使用steam启动或者Visual Studio运行结果相同

**Comment by Diend2023** [comment]
![屏幕截图 2023-09-14 090425](https://github.com/LorisYounger/VPet/assets/103641773/4e868500-669b-4269-9bb5-1937ccf6b220)

**Comment by LorisYounger** [comment]
参见 https://store.steampowered.com/news/app/1920960/view/3681184905256253202
报错: FIPS/uriString

**Comment by Diend2023** [comment]
成功了，非常感谢！！
