### ISSUE TITLE
[建议]可以加点后期的内容,后期没有啥想干的事

### ISSUE THREAD

**Issue by CyRusyyx** [LorisYounger/VPet#204]
钱太多了没地方用, 等级很高也没啥用, 可以加点高等级才能解锁的学习或者工作`(不过, 这样的话, 貌似后期更容易膨胀了)`

总之现在就是把钱买礼物花掉, 然后继续工作赚钱😂, 啥都不干感觉怪无聊的

成就的话, 害, 其实我也想变成成就党, 大脑不允许😂

**Comment by LorisYounger** [comment]
旅行桌宠dlc在做了, 后续支持桌宠出去旅行带CG和东西之类的东西回来
