### ISSUE TITLE
[Suggestion] Any way to improve built-in English translation 改进内置英文翻译

### ISSUE THREAD

**Issue by imhe6** [LorisYounger/VPet#208]
目前的英语翻译有一些不一致和错漏之处（比如设置里的**超模的mod**被翻译成 **supermodel MOD**...），本人有一定的翻译软件文本等的经验，因此想自己对目前的英翻（以及中文原文，如果可以的话）做一些改善（也是更方便英语玩家游玩）。
另外，目前更改官方英文翻译的途径除了直接修改源码提交 PR 和做 mod 之外还有其他方法么？我看到创意工坊上有许多玩家自制语言包，作者可以开一个翻译平台（比如 Crowdin，对开源项目免费，不过要求项目创建时间在三个月以上），这样也更方便玩家对官方本地化做出贡献。

**Comment by LorisYounger** [comment]
Crowdin我之前试了试,不会用, 不知道咋把LPS映射成id和翻译内容,整到最后就没整了, 还是等创意工坊自己长出来个betterEnglish之类的mod吧
附:翻译工具
[TranslatorTool.zip](https://github.com/LorisYounger/VPet/files/12620146/TranslatorTool.zip)
