### ISSUE TITLE
[Suggestions] 关于数值计算触发的一些建议

### ISSUE THREAD

**Issue by ChaojuWang** [LorisYounger/VPet#209]
现在是按照计算间隔触发一次计算，更新一次状态。在修改计算间隔之后会影响各种数据在现实时间流动下的增减速度，会改变用户的体验，而且用户不能很直观的感受或者计算这个变化。建议以现实时间为基础锚定数值变化，且在面板统计里按照分钟来统计数据。另建议能够预览各种互动的对应的状态变化量。

**Comment by LorisYounger** [comment]
面板里面已经有很详细的写了每分钟进行几次计算
![image](https://github.com/LorisYounger/VPet/assets/34806646/11c19d63-cae6-404c-893a-f44705a38919)
鼠标放上去也会弹提示
![image](https://github.com/LorisYounger/VPet/assets/34806646/5091c473-3105-404c-a093-ec6d16e08bc7)
教程里也说了
![image](https://github.com/LorisYounger/VPet/assets/34806646/7cfe709a-5322-4df2-b3f7-22213d3dc95b)
