### ISSUE TITLE
当桌宠执行特定动画时，无法进行拖拽以移动位置

### ISSUE THREAD

**Issue by qiuzilu** [LorisYounger/VPet#21]
![image](https://github.com/LorisYounger/VPet/assets/64822124/6b014a40-4ab2-4516-adf7-23ceae719e15)
嗯，这是我的桌宠，她现在在躺着，很安详。
我无法拖拽她。
另外，在执行其他部分动画时（滑翔、爬行、睡觉等）也会出现无法拖拽的情况。

**Comment by MacieSerenity** [comment]
哈哈哈哈

**Comment by kinglingmk1** [comment]
我觉得可以把拖拽这个功能可以中断目前动画或操作然后执行拖拽功能应该可以了

我的现在自闭在角落无法动弹
![未命名](https://github.com/LorisYounger/VPet/assets/128010679/eb1cf02c-6f5c-4fc3-a570-47e6551cefdf)

**Comment by CERN391** [comment]
你可以试试重置状态这个功能 我的只是拖拽不动然后不到一分钟就开始鬼畜 只能通过重置状态来让她正常

**Comment by kinglingmk1** [comment]
刚刚发现一个规律了...
按住一会儿(一兩秒左右)才触发被拽起的动画无论动画正在做什么
不可以一按下去就直接拖拽
无论动画正在做什么

**Comment by Johnserf-Seed** [comment]
想知道如何把右下角的短日期设置为hh:mm:ss长日期的格式又或者是可以切换成长时间显示，我找了设置没有发现

**Comment by Johnserf-Seed** [comment]
> 想知道如何把右下角的短日期设置为hh:mm:ss长日期的格式又或者是可以切换成长时间显示，我找了设置没有发现

找到了办法了

> 修改注册表的这个位置 ```HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced```
> 添加一个名称为 ```ShowSecondsInSystemClock``` 的 ```DWORD16位``` 键
> 值为 ```1```，```16进制```
> 重新启动explorer即可
> 😸

**Comment by wzqvip** [comment]
应该是判定点的问题，点击原本头部的位置（空气），我可以在睡觉的时候拖动

**Comment by hehe-minecraft** [comment]
这个代码像是检测鼠标是否在一个固定区域中，而不是检测鼠标是不是在脑袋上面，拖拽一下稍微偏上一点的位置，看看行不行，看起来他的代码没有实时监测脑袋在哪里

**Comment by akhzzcn** [comment]
> 想知道如何把右下角的短日期设置为hh:mm:ss长日期的格式又或者是可以切换成长时间显示，我找了设置没有发现

你意思是任务栏那里显示秒嘛，设置里面就有，如果你的设置里面没有，那可能是你系统没更新（或者是预览版的？我记得这功能已经有了很久了，正式版应该也更了吧）
![Snipaste_2023-09-01_18-10-50](https://github.com/LorisYounger/VPet/assets/52377847/bd0464eb-0d4c-462a-9d91-882de17966fe)

**Comment by Johnserf-Seed** [comment]
> 

原来11可以直接设置了，我的是10 22h2，我通过改注册表实现了。

**Comment by Johnserf-Seed** [comment]
> > 想知道如何把右下角的短日期设置为hh:mm:ss长日期的格式又或者是可以切换成长时间显示，我找了设置没有发现
> 
> 你意思是任务栏那里显示秒嘛，设置里面就有，如果你的设置里面没有，那可能是你系统没更新（或者是预览版的？我记得这功能已经有了很久了，正式版应该也更了吧） ![Snipaste_2023-09-01_18-10-50](https://user-images.githubusercontent.com/52377847/264993817-bd0464eb-0d4c-462a-9d91-882de17966fe.png)

原来11可以直接设置了，我的是10 22h2，我通过改注册表实现了。

**Comment by LorisYounger** [comment]
应该已经在先前版本修复了
