### ISSUE TITLE
[bug]在星空全屏幕模式下，桌宠无法自动隐藏

### ISSUE THREAD

**Issue by DavidLogic** [LorisYounger/VPet#212]
在其他游戏中桌宠都能正常隐藏，不知道是杯赛的锅还是bug😭

复现次数：总是出现
系统：windows 11 23h2
桌宠版本：v1.5（105）
<img width="1280" alt="屏幕截图 2023-09-16 210605" src="https://github.com/LorisYounger/VPet/assets/58322362/eebb48e6-cd89-4b98-ac73-634005105fc8">

**Comment by LorisYounger** [comment]
游戏设置成全屏桌宠就不会出现了, 如果还出现,可以试试把桌宠的置顶关掉
