### ISSUE TITLE
奥义，双开之术！

### ISSUE THREAD

**Issue by Hinata-official** [LorisYounger/VPet#213]
![image](https://github.com/LorisYounger/VPet/assets/61258915/3b80a345-1ead-4ce4-9bcd-f9fc9c7cab36)
![image](https://github.com/LorisYounger/VPet/assets/61258915/c2140593-bbd8-46f4-9e70-840c1c079754)
我也不知道干嘛了，就这样了

**Comment by LorisYounger** [comment]
开机自启偶尔抽风会开2次, steam开一次, 无steam开一次, 关掉任意一个即可
多开可能会导致bug, 未来会做官方支持多开
