### ISSUE TITLE
有关 音乐识别 的问题

### ISSUE THREAD

**Issue by shizuku-neko** [LorisYounger/VPet#216]
![Cache_-634ace2fdb035fcb](https://github.com/LorisYounger/VPet/assets/58767404/8a60d291-1f72-4372-9412-5ba3d7db63f2)
![Cache_7a83fea5a0343e7d](https://github.com/LorisYounger/VPet/assets/58767404/a52dfa1e-bedb-495c-961e-b05a13f13d66)
当声音输出设置为非物理音频设备时，软件无法获取当前音量
软件版本 V1.6

**Comment by LorisYounger** [comment]
创意工坊有修复MOD, https://steamcommunity.com/sharedfiles/filedetails/?id=3022006959&searchtext=
