### ISSUE TITLE
重新安裝後所有腳本相關插件停止工作

### ISSUE THREAD

**Issue by UnKinSeong** [LorisYounger/VPet#217]
重新安裝沒有用
![image](https://github.com/LorisYounger/VPet/assets/58870474/1c65a772-8492-4208-8a56-f7d8c33dfc00)
![image](https://github.com/LorisYounger/VPet/assets/58870474/23b23d07-5eca-440e-85db-6b50967837d6)
![image](https://github.com/LorisYounger/VPet/assets/58870474/0bbceb9c-f6de-4f88-8532-c4caa4751185)
![image](https://github.com/LorisYounger/VPet/assets/58870474/0c0b9e27-e006-4de4-b950-76ea0916e6a1)

**Comment by LorisYounger** [comment]
自己编译一个呢, 看看具体报错
