### ISSUE TITLE
程序启动后自动退出

### ISSUE THREAD

**Issue by acgloli** [LorisYounger/VPet#218]
双击运行后有出现程序加载的页面，但是加载一段时间后程序就退出了；尝试了管理员运行，也是无法启动。
运行的环境如下：
系统：Windows10 Ltsc 2021
CPU：AMD Ryzen 7 2700X
显卡：GTX 1080
内存：64G
![UninstallTool_YOLOqvVk9P](https://github.com/LorisYounger/VPet/assets/59498164/da99f26a-da03-4989-b32c-d8d4c9dd7193)

https://github.com/LorisYounger/VPet/assets/59498164/59120ef6-66ea-4f6d-8d4a-e3110fbcc3f9

**Comment by LorisYounger** [comment]
参见这个自己编译下试试看看报错
