### ISSUE TITLE
[Suggestion] 可以考虑移植linux或mac么

### ISSUE THREAD

**Issue by pieceof** [LorisYounger/VPet#223]
作为linux开发者，希望可以考虑移植到linux。我对c#一窍不通，如果您觉得这样做的成本不算太高，希望可以回复我，我也希望有机会可以加入开发，将项目移植到linux。

**Comment by pieceof** [comment]
确切的说，我对游戏相关开发一窍不通，是个纯开发后端的。希望可以告诉我开发的难度，我再决定是否上手

**Comment by LorisYounger** [comment]
因为我并不会跨平台UI语言, 所以并不会移植到linux, 至于其他开发者正在做的跨平台,可以参考 https://github.com/LorisYounger/VPet/discussions
