### ISSUE TITLE
[Suggestion] Add Discord Rich-Presence integration

### ISSUE THREAD

**Issue by the-eduardo** [LorisYounger/VPet#224]
But my idea is have a Discord Rich Presence integration that shows the current status of VPet, as example: VPet/ Working for xx minutes, or idling, etc

![example](https://i.imgur.com/16Qrugj.png)

I don't know C# but I know is possible to integrate it using the discord API or some C# library like this one: https://github.com/Lachee/discord-rpc-csharp

Also here is the official docs from Discord: https://discord.com/developers/docs/rich-presence/how-to

If you like the idea, I can code some base for it, however due to my lack of knowledge, more developers would be needed to make the final version.

**Comment by LorisYounger** [comment]
I will not add status displays other than Steam
But the steam workshop seems to already have similar modules, see https://steamcommunity.com/sharedfiles/filedetails/?id=3024377317&searchtext=Discord
