### ISSUE TITLE
存档自动倒退

### ISSUE THREAD

**Issue by a492219408** [LorisYounger/VPet#228]
我的宠物本来是67级9万块钱的，现在突然变成了45级4万块钱；名字也在最近改过一次，现在变成了旧的名字

**Comment by LorisYounger** [comment]
读备份, 一般是网络不好 steam的云同步给你同步了旧版本的存档导致的

**Comment by a492219408** [comment]
> 读备份，一般是网络不好的流的云同步给你同步旧版本的文件结果

/BackUP目录下吗？这里的存档只有最后一个是比较新的，Save_2208.lps，其他的从Save_999.lps开始往前都是很久以前的，但最新的Save_2208.lps也是错误的数据

**Comment by LorisYounger** [comment]
> > 读备份，一般是网络不好的流的云同步给你同步旧版本的文件结果
> 
> /BackUP目录下吗？这里的存档只有最后一个是比较新的，Save_2208.lps，其他的从Save_999.lps开始往前都是很久以前的，但最新的Save_2208.lps也是错误的数据

设置里自带读备份的功能, 另外看你描述感觉的确丢存档了, 你那个还有个问题是备份功能删除了错误的最新存档, 这个bug在之前1.4版本就修复了, 你这边看上去没更新的样子

如果你有开诊断, 你也可以告诉我你的steam64id,我可以帮你从你的诊断系统中找数据

**Comment by LorisYounger** [comment]
TMD, 居然真的有这种非常严重的bug, 我当初修bug修了一半,可能被叫走或者忙去了, 就没写完整
就缺一行, 会导致 备份功能删除了错误的最新存档 这个bug 一直在

**Comment by a492219408** [comment]
> > > 读取备份，一般是网络不好的流的云同步给你同步旧版本的文件结果
> > 
> > 
> > /BackUP目录下吗？这里的文档只有最后一个是比较新的，Save_2208.lps，其他的从Save_999.lps开始往前都是很久以前的，但最新的Save_2208.lps也是错误的数据
> 
> 设置里自带读取描述备份的功能，另外看看你感觉没丢文档了，你那个还有问题是备份功能删除了有错误的最新文档，这个bug在1.4版本之前就修复了，你这篇报告没更新的样子
> 
> 如果您有诊断，您也可以告诉我您的 steam64id，我可以从您的诊断系统中查找数据

我也是自己观察了下存档文件，发现没办法恢复了才发的反馈。就是现在我希望能通过修改存档的方式来恢复到大致的状态，具体的数值我也不记得了。但是存档中有个hash值，我猜这个值是用来数据校验的，防止直接修改。我是Java开发者，没接触过C#，看了下源码想找到hash是如何生成的，但我不懂语法，只能看懂小部分逻辑，能不能提供一种代替解决方案，或者告诉我该怎么做才能正确修改存档。没有打开诊断，把这个问题解决了，后续我打开诊断吧

**Comment by LorisYounger** [comment]
删除Hash哪一行后把文本做个md5就行

**Comment by a492219408** [comment]
> 删除Hash哪一行后把文本做个md5就行

我在Sub.cs里的`GetHashCode(string text)`发现 先把string进行UTF-8编码，然后计算MD5，再把MD5的结果进行某种转换`BitConverter.ToInt64()`，我想在Java中复现这一过程，UTF-8编码和MD5计算都可以实现，但Java并没有`BitConverter.ToInt64()`这一种方法和工具。

我在GameSave_v2.cs中把`HashCheck = vpet.GetLongHashCode() == hash;`改成`HashCheck = true;`，就可以无视hash检测了。

现在问题已解决，我可以把存档数值大致修改成之前的状态了，感谢开发者积极回应反馈，如后续有其他BUG或反馈，我会再来反馈。
