### ISSUE TITLE
[备忘]自动进食

### ISSUE THREAD

**Issue by qiuzilu** [LorisYounger/VPet#23]
![3276bbe991ad8e12304ec1f40cbce740](https://github.com/LorisYounger/VPet/assets/64822124/e18da000-4354-49e3-95d6-080cbfa16dd6)
![image](https://github.com/LorisYounger/VPet/assets/64822124/ca103820-6b24-4634-957e-4ae670ce68a0)

**Comment by XGH2333** [comment]
可以考虑考虑背包功能, 食物保鲜费或者背包另付费
