### ISSUE TITLE
[建议]可以加入ban食物的机制

### ISSUE THREAD

**Issue by CyRusyyx** [LorisYounger/VPet#231]
主要是不希望赛博女儿乱买东西吃,尤其是在加入了一些mod的情况下

**Comment by LorisYounger** [comment]
本来就不会乱吃东西, 有任何负面效果食物, 小于$10的食物, 都不会吃
至于会不会买到非常贵的增益食物, 就无所谓啦, 毕竟这个功能最初目的就是花掉中后期太多的没用的钱

**Comment by CyRusyyx** [comment]
了解了解😂😂
