### ISSUE TITLE
连续触发身体触摸时,统计数据是否应与状态数值变更统一

### ISSUE THREAD

**Issue by Fantasy-Dash** [LorisYounger/VPet#241]
按目前逻辑 如果鼠标多次移动 多次触发身体触摸DisplayTouchBody()时,如果之前的动画没有播放完毕,则只计算状态,并不触发统计数据的更改.
我觉得这有些不合理,以下是我对反复触发身体触摸事件的两种修改建议:
1.和状态更改同步多次触发统计数据更改.
2.多次触发只延长动画播放时间 不触发属性更改.

**Comment by Fantasy-Dash** [comment]
如果需要的话 我可以提交Pr

**Comment by LorisYounger** [comment]
多次移动触发只会继续动画和提供数据修改, 但是成就里摸身子次数只算一次
摸头同理
本来统计就是慢慢养成的, 不可能给你一次性整完
至于属性更改,官方回复心情的途径就是通过摸头摸身子和互动恢复心情和重置心情掉落指数计数的, 并不是通过礼物或者吃东西回复
