### ISSUE TITLE
关于“触发跳舞”的新成就

### ISSUE THREAD

**Issue by rutu1924578939** [LorisYounger/VPet#246]
播放音乐时多次触发跳舞仍无法达成成就，是bug还是有其他的要求限制？

**Comment by LorisYounger** [comment]
可能是没更新, 老版本没这个统计

**Comment by rutu1924578939** [comment]
> 可能是没更新, 老版本没这个统计

更新完了，然后也触发了跳舞，但依旧还是解锁不了成就，应该不存在网络或者是存档上传问题，因为我在更好买里买了一些礼物成功解锁“花费100k买礼物”的成就

**Comment by LorisYounger** [comment]
记得触发后等一会,每隔15秒一次上传成就
