### ISSUE TITLE
部署这么麻烦直接搞个release算了

### ISSUE THREAD

**Issue by Fxxndxn** [LorisYounger/VPet#249]
部署这么麻烦直接搞个release算了（本人不用steam，并且只是一点点建议，不要生气哈

**Comment by LorisYounger** [comment]
使用github的话, 只有第一次部署需要点下安装,后续更新是不需要的
release打包起来比较麻烦, steam有个自动打包,会把非相关文件(例如存档,调试文件等)排除掉
但是github我不清楚有没有类似的功能, 每次打包我都得手动删特别麻烦
