### ISSUE TITLE
App crashes in another region

### ISSUE THREAD

**Issue by Afireal** [LorisYounger/VPet#25]
Seems like app just crashes on Core mod loading because of lack of a localization for system region. Setting it to `English (USA)` in Win settings fixes the issue but idk it's not really a nice way.
How about automaticlly setting localization to EN if there is no lang files for system language?

**Comment by LorisYounger** [comment]
In theory, it should automatically switch to English
And loading an empty language will not result in an error
I will add an automatic switch to English in the next update if the current language is empty

**Comment by LorisYounger** [comment]
I update a new version, can you open now?

**Comment by Afireal** [comment]
I managed to compile latest VPet-Simulator.Windows and that's what I got.
Localization is automaticlly switching to EN without latest changes (sorry). Fortunatly, I discovered why app crashes exactly on Core mod loading. There's an exception on food initializing.

[CoreMOD.cs:137](https://github.com/LorisYounger/VPet/blob/main/VPet-Simulator.Windows/Function/CoreMOD.cs)
```cs
case "food":
                        Tag.Add("food");
                        foreach (FileInfo fi in di.EnumerateFiles("*.lps"))
                        {
                            var tmp = new LpsDocument(File.ReadAllText(fi.FullName));
                            foreach (ILine li in tmp)
                            {
                                string tmps = li.Find("name").info;
                                mw.Foods.RemoveAll(x => x.Name == tmps);
                                mw.Foods.Add(LPSConvert.DeserializeObject<Food>(li));
                            }
                        }
                        break;
```
`System.FormatException: Format specifier was invalid.` on `mw.Foods.Add(LPSConvert.DeserializeObject<Food>(li));`
If I compile whole thing with american formats in Win settings, everything is fine. I don't really know much about dotnet, so no ideas.

**Comment by Afireal** [comment]
Stack trace. But I don't think it's really helpful now
```
System.FormatException
  HResult=0x80131537
  Message=Входная строка имела неверный формат. <-- Format specifier was invalid.
  Source=mscorlib
  StackTrace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at LinePutScript.Converter.LPSConvert.GetStringObject(String value, Type type, ConvertType convtype, LineAttribute att)
   at LinePutScript.Converter.LPSConvert.GetSubObject(ISub sub, Type type, ConvertType convtype, LineAttribute att)
   at LinePutScript.Converter.LPSConvert.DeserializeObject[T](ISub value)
   at VPet_Simulator.Windows.CoreMOD..ctor(DirectoryInfo directory, MainWindow mw) in E:\Git\VPet\VPet-Simulator.Windows\Function\CoreMOD.cs:line 137
   at VPet_Simulator.Windows.MainWindow.<GameLoad>d__107.MoveNext() in E:\Git\VPet\VPet-Simulator.Windows\MainWindow.xaml.cs:line 208```

**Comment by LorisYounger** [comment]
I think that's the real reason for the error report. I'll study how to solve it. Thank you for your feedback. It really helped a lot

**Comment by LorisYounger** [comment]
I'm sorry, I wrote this `LinePutScript`
I may find a solution and try to lock the language to en US
```
Convert.ChangeType(Sub.TextDeReplace(value), type, new CultureInfo("en-US"));
```
but I am not sure is that work, I will compile a beta version. Can you help me test it

**Comment by Afireal** [comment]
ok, no problem

**Comment by LorisYounger** [comment]
[LinePutScript.zip](https://github.com/LorisYounger/VPet/files/12337887/LinePutScript.zip)
rereplace it with `LinePutScript.dll`
is game working?

**Comment by Afireal** [comment]
Nope. Neither the steam version nor the compiled one

**Comment by LorisYounger** [comment]
Can you use visual studio Reference this DLL and run again?
I want to see is same error or different

**Comment by Afireal** [comment]
Different one, but still the same exception. I will now send details

**Comment by Afireal** [comment]
[VPet-Simulator.Core/Graph/FoodAnimation.cs:151](https://github.com/LorisYounger/VPet/blob/81ae01180092a80d1926d9e22fd773e38b73ec07/VPet-Simulator.Core/Graph/FoodAnimation.cs#L151)
```cs
                    if (strs.Length > 4)
                    {
                        Rotate = double.Parse(strs[4]);//Rotate
                        if (strs.Length > 5)
                            Opacity = double.Parse(strs[5]);//Opacity
                    }
```
Same `System.FormatException: Input string was not in a correct format.` on `double.Parse(strs[5])`

**Comment by Afireal** [comment]
System.InvalidOperationException on new line
It's says that it's read-only value

**Comment by Afireal** [comment]
No effect. Still the same error as [here](https://github.com/LorisYounger/VPet/issues/25#issuecomment-1677810423) but on line 149

**Comment by LorisYounger** [comment]
```
            LocalizeCore.StoreTranslation = true;
            CultureInfo.CurrentCulture = new CultureInfo(CultureInfo.CurrentCulture.Name);
            CultureInfo.CurrentCulture.NumberFormat = new CultureInfo("en-US").NumberFormat;
```

**Comment by Afireal** [comment]
It's works!

**Comment by LorisYounger** [comment]
Thanks for you help!

**Comment by Afireal** [comment]
Should I close this issue or it's just a temporary solution?

**Comment by LorisYounger** [comment]
Thank you again for your help, I will update fix to steam soon
I will close when the update is complete
