### ISSUE TITLE
建议和使用中出现的一些问题

### ISSUE THREAD

**Issue by ANYLNK** [LorisYounger/VPet#250]
问题：
1.
本地测试时出现了部分设置、宠物状态丢失的情况。目前测试结果是在关机/重启前十分钟（即设置的自动保存时间间隔）内更改的设置或宠物状态（如设置开机启动、投喂等）不会保存

请问能否加入在关机时自动保存游戏的功能？

2.
疑似死锁：一台Windows 11设备上在设置面板里开启“开机启动”后提示权限不足无法创建快捷方式，此后以管理员权限重新启动桌宠或者更新桌宠版本也无法设置成功此项无法开机启动
部分排查：在C盘根目录下有一个指向桌宠主程序的快捷方式，将其移动到Programdata目录下的启动文件夹问题解决（该设备到AppData下仍存在不能正常启动的情况）。目前怀疑桌宠的创建快捷方式到启动文件夹里的逻辑存在问题（也许没有考虑到过程中存在同名快捷方式的可能？）

可否修复一下这个问题？

**Comment by LorisYounger** [comment]
理论上关机会自动关闭游戏,关闭游戏的时候会自动保存
实际上会因为奇奇怪怪的问题导致游戏没保存上, 建议关机前手动退出下

我创建的快捷方式应该在 %appdata%\Microsoft\Windows\Start Menu\Programs\Startup\
如果实在没法设置开机启动,可以手动创建桌宠的快捷方式, 复制到上面的目录,就可以开机启动了
