### ISSUE TITLE
是否能增加"全屏模式下隐藏桌宠"的设置选项

### ISSUE THREAD

**Issue by yz1392946854** [LorisYounger/VPet#254]
开着桌宠玩全屏游戏会有一点阻碍，找了一圈没看到可以隐藏，想问下作者以后有没有计划出一个全屏模式下隐藏桌宠的选项😝😝，我也会试着自己开发，不过我现在还对C#一窍不通😓

**Comment by LorisYounger** [comment]
不会, 读全屏是监控玩意, 可能会涉及到管理员权限,不会做
而且桌宠本来就支持全屏隐藏, (目标)游戏设置的时候选择 全屏 而不是窗口化全屏, 自然就隐藏了
桌宠的置顶没有全屏的权限高
