### ISSUE TITLE
[疑似bug]“较好的麦克风”增加心情值过多

### ISSUE THREAD

**Issue by reflexit** [LorisYounger/VPet#256]
如图所示，“普通麦克风”与“好的麦克风”各增加心情值30，而“较好的麦克风”增加心情值160（红框内），可能是bug。

![捕获](https://github.com/LorisYounger/VPet/assets/19850021/0f3926b7-339b-4b57-bd3b-3a6994ed1339)

**Comment by LorisYounger** [comment]
数值填错了, 不过因为我是拿表算的,所以平衡性没问题,下版本修
