### ISSUE TITLE
一条建议

### ISSUE THREAD

**Issue by huifeideteji** [LorisYounger/VPet#257]
能否在某些条件下令桌宠可以与虚拟主播模拟器联动？
举个例子：桌宠直播可以和虚拟主播连麦，并且可以相互互动（狗头）

**Comment by LorisYounger** [comment]
桌宠原本就是虚拟主播模拟器里面的一个教程独立出来开发的小游戏
只是之前没想到会这么火, 才有后续一系列开发的
在虚拟主播模拟器中, 桌宠会作为教程和提示,以及花玩家的钱
