### ISSUE TITLE
在“尝试加载游戏存档”后直接闪退

### ISSUE THREAD

**Issue by taixuya** [LorisYounger/VPet#258]
验证过游戏文件了，重装过了，win10，windows最佳外观也设置了，但就是在“尝试加载游戏存档”后直接闪退

**Comment by dox987** [comment]
does it says loading:mod 0000_core and crashing? i have same problem on my intel desktop and ryzen laptop

**Comment by mrzhang1121** [comment]
刚刚(2023/10/4)我作为新玩家(new player)也遇到同样的错误。使用的是Win10 22H2。
用事件查看器得到报错如下:

> 应用程序: VPet-Simulator.Windows.exe
>Framework 版本: v4.0.30319
>说明: 由于未经处理的异常，进程终止。
>异常信息: System.InvalidOperationException
>   在 System.Linq.Enumerable.Last[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   在 VPet_Simulator.Windows.MainWindow.LoadLatestSave(System.String)
   在 VPet_Simulator.Windows.MainWindow+<GameLoad>d__128.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by taixuya** [comment]
> does it says loading:mod 0000_core and crashing? i have same problem on my intel desktop and ryzen laptop

I only have "mod 0000_cor"flicker，And then it keeps getting stuck and automatically flashes back after 'trying to load the game'

**Comment by happilygrowingup** [comment]
先退出Steam，再把游戏文件夹里面的Saves文件夹删掉（**Saves文件夹里面应该是没有存档的！！有存档的话千万不要轻易删除！！做好备份！！**），然后在不启动Steam的情况下打开游戏就可以了
可以看一下我刚发的PR #259

**Comment by LorisYounger** [comment]
唉,我的锅, steam会在存档文件夹创建个云同步用的文件, 我写存档系统的时候没考虑到这个
自己测试也没有触发成功, 我之前测试的时候特意关掉了云存档免得我的存档影响到了测试,把这个漏了

**Comment by LorisYounger** [comment]
my bad, steam creates a file in the archive folder for cloud sync, I didn't think of that when I wrote the saving system.
I didn't get this error when I tested it myself, because I had turned off the cloud archive when I tested it so that my archive wouldn't affect the test, and I missed it.
