### ISSUE TITLE
TextClick_V2.Ips vs Text2308 - same lines

### ISSUE THREAD

**Issue by AwesomeFart** [LorisYounger/VPet#266]
Hello, I am translating TextClick_V2 and  i see lot of same text in TextClick_V2 as in Text2308. I feel like im translating same things twice...

Should i only focus on TextClick_V2 ? Is it like new version for future update or something? Do i translate both?

Line 54: Text2308: 《我与主人的爱情故事》写好了！诶？不行吗
Line 52: TextClickV2 《我与主人的故事》写好了！诶？不行吗

**Comment by LorisYounger** [comment]
Both, Text2308 is TextClick first edition  (focus on functional chat), 
TextClick_V2 add more click text (focus on daily chat), 

in this case, you can remove `Line 54: Text2308: 《我与主人的爱情故事》写好了！诶？不行吗` in Text2308
This chat content has been optimized because I do not want to clarify the relationship between pets and their owners (Wife/Daughter)

**Comment by AwesomeFart** [comment]
So both files text2308 and texclickV2 are relevant for translation? 

Should i polish further Text2308 or just focus on TextClick_V2?

**Comment by LorisYounger** [comment]
All files are related to translation. I won't put translation files that haven't expired into the game.

However, there are indeed some translated content that may be discarded or no longer used in the game. In the future, I will take the time to reorganize the translated content.

**Comment by AwesomeFart** [comment]
OK I will just translate everything in TextClick_v2, Text2308, Text2307, TextSelect_v2,  maybe later Text 2309. 

You can delete stuff later.  Thank you for clarification.

**Comment by LorisYounger** [comment]
Thank you for translation

**Comment by AwesomeFart** [comment]
I am still not sure , If you should take my translation as official translation it will be better than the machine one though.
