### ISSUE TITLE
problem in Base2306

### ISSUE THREAD

**Issue by AwesomeFart** [LorisYounger/VPet#268]
problem in Base2306 
Cannot change translation for each - one should be "learn" and second one should be "learning" i cannot achieve this, because line 224 doesnt change anything and line 219 changes both
![image](https://github.com/LorisYounger/VPet/assets/59807858/dea1109f-54ef-4774-b6b0-0c357d0beff1)

_Originally posted by @AwesomeFart in https://github.com/LorisYounger/VPet/issues/267#issuecomment-1758108711_

**Comment by LorisYounger** [comment]
Because they are same in chinese, both are study.
I will make it different in next update, you can skip it
