### ISSUE TITLE
[Suggestion][Settings] Select Audio tracks/devices

### ISSUE THREAD

**Issue by szShiranya** [LorisYounger/VPet#269]
Hi, 
I have different Audio tracks, one for music, games, chat and so on.
Maybe you know the Software SteelsSeries GG wich helps for easy basic Audio mixing on your desktop.
Unfortunatly I can not select a Audio track where the cute little fellow should check for the playback volume. 
It would be nice to have a setting to select an Audio track/device for the Audio playback volume check.
Greetings

**Comment by LorisYounger** [comment]
I don't know how to catch/select an audio track/device. Unfortunately, I don't know these things.
The creative workshop has a method for fixing music recognition and detecting microphone music on various devices.
see workshop https://steamcommunity.com/sharedfiles/filedetails/?id=3022006959
github https://github.com/windofxy/VPet.Plugin.MultiChannelMusicFix
> Fix the issue of not being able to correctly detect music playback when using multi-channel devices (such as SteelSeries GG audio software)
> Added the function of detecting music through the microphone, allowing the table pet to start dancing while you sing. By default, it is turned off and needs to be turned on by itself
> (Opening method: Go to Settings>MOD Management, find my MOD, and there is a MOD setting button under the operation partition. After clicking on it, set it in a new window that pops up)

And I read the comments, it say And I read the comments will update soon.
This should meet your needs
