### ISSUE TITLE
桌宠模拟器在 Loading Game 时闪退

### ISSUE THREAD

**Issue by Moprst** [LorisYounger/VPet#272]
桌宠模拟器在 Loading Game 这一步自动闪退了，没有弹出报错消息。查看本地事件查看器发现记录了两个错误：
![image](https://github.com/LorisYounger/VPet/assets/82132165/b6ab9366-1fed-41ed-b17c-d21efd28e2b4)
![Screenshot_1](https://github.com/LorisYounger/VPet/assets/82132165/c5ffc86f-0420-4b0a-a176-b06efe85a354)

**Comment by LorisYounger** [comment]
可以参考这个 https://stackoverflow.com/questions/63510630/wpf-bitmapimage-exception-the-image-data-generated-an-overflow-during-processin/65111729#65111729
为了解决这个问题，我们确保颜色管理窗口中的所有设置都是“系统默认值”。在一个实例中，“设备配置文件”设置为“虚拟 SRGB”，导致了此问题。
![image](https://github.com/LorisYounger/VPet/assets/34806646/371e799e-e5ad-46e9-8adb-740e7d493fb1)
