### ISSUE TITLE
2023/10/20运行出现严重错误

### ISSUE THREAD

**Issue by zjq139134** [LorisYounger/VPet#274]
![image](https://github.com/LorisYounger/VPet/assets/49606046/79216f52-2b65-491b-87f4-857721a2d47d)
 2023/10/20 两次更新都出现了严重故障，无法启动
游戏版本:steam最新版+猫猫DLC
系统:WIN10家庭版 22H2 CPU:AMD 5800H 显卡:RTX3060LAPTOP 内存:光威 3200 16G*2

**Comment by zjq139134** [comment]
注：没有使用创意工坊

**Comment by m1rqin** [comment]
和你一样，重装完游戏还是不能进去，将创意工坊所有内容删除重装意识这个报错，，系统是Windows11

**Comment by 1582421598** [comment]
#275 该PR可以修复，托盘菜单近期经历了一些变更 #260 ，其中包括对鼠标点击穿透状态的调整。在用户激活鼠标穿透功能后，该函数会尝试更新托盘菜单的状态。但是，因为这个更新操作可能在桌宠程序刚启动、托盘菜单还未完成初始化的时候就被执行，这导致了null异常的出现。
