### ISSUE TITLE
[BUG]DLC双开桌宠后从桌面退出桌宠会报错

### ISSUE THREAD

**Issue by 3cxc** [LorisYounger/VPet#278]
使用 VPet - Pancake 猫猫 皮肤包DLC 后，双开桌宠，右键桌宠点击退出后，实际上桌宠没有退出
这时通过任务栏的程序退出会报异常
![错误截图](https://github.com/LorisYounger/VPet/assets/81449257/b894051b-5abc-48f5-b4aa-a7cdafb8316f)

附上模组列表(全都启用了)
![模组列表](https://github.com/LorisYounger/VPet/assets/81449257/84729b6d-30c3-4f51-9622-f21cf2bbfba2)

**Comment by 3cxc** [comment]
尝试过关闭其他mod，仅保留Core和DLC，仍然引发错误(从桌宠退出后，任务栏程序没有退出，此时只能强制关闭)

**Comment by qiuzilu** [comment]
> 尝试过关闭其他mod，仅保留Core和DLC，仍然引发错误(从桌宠退出后，任务栏程序没有退出，此时只能强制关闭)

![image](https://github.com/LorisYounger/VPet/assets/64822124/61373fb6-f6e2-4419-a2e9-584f4d9596c7)
![d0f25d1df1246eded36dc56c5c0c18d6](https://github.com/LorisYounger/VPet/assets/64822124/04215288-e67c-4b71-9bb5-c1ae41442ae9)

**Comment by qiuzilu** [comment]
应该在修了吧(应该)

**Comment by 3cxc** [comment]
已经躺床上刷手机，突然发现回复了(这反应速度是真的快)
希望能快点修(双开不能正常退出很难受呜呜)
