### ISSUE TITLE
桌宠多开出现Bug

### ISSUE THREAD

**Issue by InvalidUser10086** [LorisYounger/VPet#287]
![image](https://github.com/LorisYounger/VPet/assets/109017550/129db7c2-6aa4-407d-ad16-9684168369e0)
在出现以上错误提示时，正在执行多开操作。
重置存档桌宠后桌宠状态为全空，为生病状态，并非一开始的健康状态。
错误提示每次启动桌宠只出现一次，多开存档重新打开后不再出现，重启全部桌宠程序才重新出现。

**Comment by LorisYounger** [comment]
是MOD的问题, 并非桌宠的问题, 请联系mod作者
