### ISSUE TITLE
多显示屏时攀爬移动异常，且关闭移动后仍会移动

### ISSUE THREAD

**Issue by strange-qwq** [LorisYounger/VPet#29]
示例：把任务拖动到第二个显示器右下角后，过一会儿她会瞬移回第一个显示器右下角进行攀爬（已关闭移动）

![image](https://github.com/LorisYounger/VPet/assets/73089181/cf61e9d0-7171-4652-8655-710299a7931b)

**Comment by LorisYounger** [comment]
关闭移动的时候会有个初始动作,然后不会继续动, 不过多屏方面倒是没注意, 我回头研究下

**Comment by Despair21** [comment]
不是多屏的也会移动

**Comment by LorisYounger** [comment]
> 不是多屏的也会移动

是的, 会有个初始位移让桌宠看起来动了但是没动

**Comment by Despair21** [comment]
> > 不是多屏的也会移动
> 
> 是的, 会有个初始位移让桌宠看起来动了但是没动

但我之前出现过坐标位置会出现了偏移，原本人物是完全在屏幕范围可看见的，但过一段时间后只有一部分在屏幕范围可见了

**Comment by LorisYounger** [comment]
确实，如果你们觉得关闭桌宠移动时一定要一点也不动更好，我就删掉会动一下的功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Despair21 ***@***.***&gt;
发送时间: 2023年8月17日 19:00
收件人: LorisYounger/VPet ***@***.***&gt;
抄送: ZouJin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [LorisYounger/VPet] 多显示屏时攀爬移动异常，且关闭移动后仍会移动 (Issue #29)





    
不是多屏的也会移动
  
是的, 会有个初始位移让桌宠看起来动了但是没动
  
但我之前出现过坐标位置会出现了偏移，原本人物是完全在屏幕范围可看见的，但过一段时间后只有一部分在屏幕范围可见了
  
我上面说的问题原因我复现出来了，原因大概是攀爬后坐标位置造成了改变导致了位移，让部分身体处于不在屏幕范围之内
 
 
https://github.com/LorisYounger/VPet/assets/70837010/b55f9fa2-769e-433d-9215-0c035ba13f77

**Comment by LorisYounger** [comment]
我刚刚回顾看了下,这个bug好像在我之前的更新不知道啥时候随手修好了,还有复现过吗

**Comment by LorisYounger** [comment]
也可能是编译版修好了,steam版还没推,回头我写完了推上去看看

**Comment by iceriny** [comment]
好勒，刚准备git下来研究研究来着  （

**Comment by LorisYounger** [comment]
原来是我参数写错了,已经修复了在最新commit
