### ISSUE TITLE
多屏问题

### ISSUE THREAD

**Issue by kieli233** [LorisYounger/VPet#290]
双屏的情况下，貌似上爬会直接从副屏爬到主屏的边缘，不管在副屏如何角落，只要上爬就会触发

**Comment by kieli233** [comment]
https://www.bilibili.com/video/BV1R94y177ve/
这是录到的bug，看起来啊，有三个

**Comment by LorisYounger** [comment]
原来是这个, 这个不是bug, 和你的桌宠设置有关系
设置里可以设置桌宠活动范围,默认范围在主屏幕,你可以修改范围到副屏幕上
至于后面那些闪烁啥的, 动画点太快偶尔会抽风很正常,不要在意小细节
