### ISSUE TITLE
桌宠多开报错，使用p猫模组后多开桌宠依旧是默认

### ISSUE THREAD

**Issue by 0day404** [LorisYounger/VPet#293]
![屏幕截图 2023-12-03 034944](https://github.com/LorisYounger/VPet/assets/128878325/ac46a96f-155f-4473-9049-bbbc5c4c8755)
![屏幕截图 2023-12-03 034155](https://github.com/LorisYounger/VPet/assets/128878325/92dbefac-1fdb-4a6c-95f5-71a87689781e)

**Comment by LorisYounger** [comment]
是MOD问题,请找mod作者解决, 看上去是那个显示好感度的mod引起的
