### ISSUE TITLE
全屏的一些建议

### ISSUE THREAD

**Issue by KarisAya** [LorisYounger/VPet#294]
添加一个设置，
可以在网页视频全屏播放时，游戏全屏启动时隐藏。可以让玩家单独添加一些应用程序规则，比如在某些应用启动/全屏/成为焦点时隐藏/暂停/释放内存（类似 Wallpaper Engine 的应用程序规则）。
避免视频画面被遮挡显示，打扰游戏操作。照顾到其他场景。

**Comment by LorisYounger** [comment]
那些检查都需要管理员权限, 不会做的
桌宠的置顶会在 真全屏时隐藏 (eg:游戏全屏, 全屏独占输出), 其他时候显示
可以桌宠设置中打开桌宠小标快速切换, 左键小标鼠标穿透,右键小标置顶
