### ISSUE TITLE
重复运行会导致多开

### ISSUE THREAD

**Issue by Bluemangoo** [LorisYounger/VPet#296]
运行两次，会出现两只。是不是少了进程锁。

commit `537d5ad`
build from source
`release` `x64`

**Comment by LorisYounger** [comment]
游戏特性,目前不打算锁, 支持使用启动指令启动不同的宠物
例如 `prefix#存档后缀:|` 打开时以该存档后缀新建多开

**Comment by Bluemangoo** [comment]
那你应该在存档上写个锁，防止同时开了两只出现问题。

**Comment by LorisYounger** [comment]
> 那你应该在存档上写个锁，防止同时开了两只出现问题。

懒得整,也没必要, 一般很少情况会误触多开同一个存档, 以及方便整活的人同时开多个桌宠玩
