### ISSUE TITLE
过度投喂会导致抽搐

### ISSUE THREAD

**Issue by Bluemangoo** [LorisYounger/VPet#298]
如题，通过某种手段把计算间隔调得很小且开自动喂食也会持续抽搐（更容易看因为一直在）。

视频：

<summary>
<details>

https://github.com/LorisYounger/VPet/assets/63218454/5b6c66e9-682a-41b5-b8a3-04cf3b7fa4c7

</details>
</summary>

**Comment by YuMingC233** [comment]
Loris购买后动画的时间应该大部分都是一致的，可以将“购买”按钮加个时间长于购买后动画的时间防抖事件，就能临时解决这个问题 😂

**Comment by LorisYounger** [comment]
UIBUG, 一般管不了, 不过视频里的这个感觉可以处理下,我研究研究看看

**Comment by LorisYounger** [comment]
> Loris购买后动画的时间应该大部分都是一致的，可以将“购买”按钮加个时间长于购买后动画的时间防抖事件，就能临时解决这个问题 😂

之前有加过禁止短时间多次喂食,不过反响不好(如果要一次性喂很多东西对玩家来说好麻烦) 后面改成多次喂食不显示动画

视频里的bug应该是夹层动画没有完全停止的原因, 我回头加个等待应该就能解决

**Comment by YuMingC233** [comment]
"要一次性喂很多东西"这个功能，可以在购买的按钮旁整一个 number input 作为可选的购买数量，默认为1。
还可以根据物品的数量对物品的贴图做一些修改（比如2瓶水可以是2张水帖图叠加，也可以重绘成套装水的样式）
一个不错的小细节😋😋

**Comment by Bluemangoo** [comment]
> "要一次性喂很多东西"这个功能，可以在购买的按钮旁整一个 number input 作为可选的购买数量，默认为1。 还可以根据物品的数量对物品的贴图做一些修改（比如2瓶水可以是2张水帖图叠加，也可以重绘成套装水的样式） 一个不错的小细节😋😋

其实买多了有效度会下降所以也不会同一个东西买很多的吧。

**Comment by Bluemangoo** [comment]
另外一段视频。

https://github.com/LorisYounger/VPet/assets/63218454/271c2c43-847c-472f-8264-2375b772281d

**Comment by LorisYounger** [comment]
应该已经修好了大概
