### ISSUE TITLE
Bug: System.Net.WebException while try to say something

### ISSUE THREAD

**Issue by richardscull** [LorisYounger/VPet#30]
Screenshot of the problem: 
![NVIDIA_Share_EX0V6NGGf7](https://github.com/LorisYounger/VPet/assets/106016833/bd996873-d7ec-4af5-897d-d7938e6e4974)

Don't really know what more data I can give on this problem, just happens sometimes.

**Comment by LorisYounger** [comment]
Don't worry about the error, it's because the service I provide is full and the VPET is not connected to the service.
