### ISSUE TITLE
内存占用暴涨且十分离谱

### ISSUE THREAD

**Issue by Sywyar** [LorisYounger/VPet#302]
以开机自启动的方式启动
迟迟不能完成加载
查看任务管理器发现内存爆炸
![image](https://github.com/LorisYounger/VPet/assets/83223374/6f71188f-258c-417e-adc2-fb4f0941dffc)

**Comment by LorisYounger** [comment]
第一次启动会生成缓存文件, 是正常现象, 耐心等待即可
性能差点的电脑可能需要等待更多时间, 内存可能也会多占用点 (生成慢导致缓存还在内存里没消化掉)
如果等待超过10分钟,可以掐掉重新启动下看看

**Comment by Sywyar** [comment]
这并不是第一次启动，之前的正常启动也不会出现这种内存爆炸的情况，我的CPU是i5-9400F，我觉得加载这个不会需要这么多内存及时间

**Comment by LorisYounger** [comment]
> 这并不是第一次启动，之前的正常启动也不会出现这种内存爆炸的情况，我的CPU是i5-9400F，我觉得加载这个不会需要这么多内存及时间

确实, 不过生成缓存的时候就是这个反应, 如果你分辨率拉特别高,例如1000以上, 也会要很久,是正常的

我电脑i913+4090生成1000以上的分辨率,也要半分钟左右

**Comment by padoru233** [comment]
同样的问题。。一看内存占用3G

**Comment by LorisYounger** [comment]
> 同样的问题。。一看内存占用3G

是因为你用桌宠打开浏览器例如Chrome的时候,会被任务管理器归类到桌宠分类下,非常离谱

**Comment by LorisYounger** [comment]
![image](https://github.com/LorisYounger/VPet/assets/34806646/eaf1a7c8-a81a-4b84-9cd7-393560e63591)
例如

**Comment by padoru233** [comment]
> ![image](https://private-user-images.githubusercontent.com/34806646/297432102-eaf1a7c8-a81a-4b84-9cd7-393560e63591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTE2NTAsIm5iZiI6MTcwNTU1MTM1MCwicGF0aCI6Ii8zNDgwNjY0Ni8yOTc0MzIxMDItZWFmMWE3YzgtYTgxYS00Yjg0LTljZDctMzkzNTYwZTYzNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA0MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzkyZWFjOWExNzVjZDEwY2I5MTI4MzlmOWVmMTY2Yjg4ZDRmOWE3ODdhZGU0MTJmZDRjYTgyYTkxNjU5YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SmYEfOKZBOcRtn1a1uSppbp3lU7KEnKmjI-2pVyunyw) 例如

这点很奇怪，我没有使用浏览器
<img width="585" alt="Snipaste_2024-01-17_12-49-58" src="https://github.com/LorisYounger/VPet/assets/99017826/8f512424-882f-4d8f-8570-f692ff7b435a">
