### ISSUE TITLE
添加备份设置的功能

### ISSUE THREAD

**Issue by lkyu-ly** [LorisYounger/VPet#304]
<img width="763" alt="图片_169" src="https://github.com/LorisYounger/VPet/assets/67578466/a0193d3e-f5e2-4eda-b670-a3485f3727af">

桌宠于今日早晨自动更新后，失去了所有设置，包括但不限于设置面板里的全部设置项。得益于steam云存档 ，游戏数据得以恢复，但是桌宠设置和mod启用情况等全部丢失，请问如何解决此类问题

**Comment by LorisYounger** [comment]
最近我没有更新过游戏,应该是你长时间没从steam启动过, 是steam云存档自己同步的问题,估计是之前的云存档是没有setting.lps的,所以被steam云同步删了说不定
设置都不影响, 按记忆中的设置还原下就行
未来应该会整个设置备份相关的功能

**Comment by lkyu-ly** [comment]
游戏确实是每天都启动的，我自己也感觉steam云存档同步存在一些问题，时常因为开机时网络不稳定导致游戏启动失败。
感谢，辛苦作者！
