### ISSUE TITLE
我在mod制作器中找到了一些没能理解的地方（状态类的参数？我不会写程序所以不知道怎么说）

### ISSUE THREAD

**Issue by PhoenixQAQLee** [LorisYounger/VPet#305]
1.点击文本中的行动状态中的Travel和Empty是什么？
2.低状态文本中的状态、饥渴状态和好感度需求的选项那几个字母，状态H和L，饥渴状态L和M和S，好感度需求的和S和M和L分别代表什么？
3.工作中的超模指什么？
4.StateOne和Two的触发机制是什么？
5.动画Say_self和Serious和Shining和Shy的触发机制是什么？
6.我想给摸摸头在一个状态下，比如高兴时，做多种动画随机触发可以做到吗？怎么做呢？
感谢👏

**Comment by LorisYounger** [comment]
1. Travel和Empty是预留给程序和以后用的参数,可以忽略
2. 状态模式
H: 开心/普通
L: 低状态/生病
好感度需求
N: 无需求
S: 低需求
M: 中需求
L: 高需求
饥渴需求
L: 一般口渴/饥饿
M: 有点口渴/饥饿
S: 非常口渴/饥饿
3. 超模指的是游戏数据参数填的太大了,不符合游戏性
4. 随机触发动画的时候会触发到StateOne(和Idel一样), 在StateOne的时候会有概率切换到StageTWO, 具体动画可以去桌宠的开发者控制台播放下看看
5. 随机,以前打算做不同文本下选用不同的说话动画,后面咕了
6. 可以, 摸头动画类型是 TouchHead, 直接用mod制作器做就行, 如果要随机,多添加几个动画就行
![image](https://github.com/LorisYounger/VPet/assets/34806646/8b113e76-9b72-4c84-8503-c8d4d3214f6e)

MOD制作器教程 https://github.com/LorisYounger/VPet.ModMaker/wiki/
