### ISSUE TITLE
mklink 执行是不是有问题   echo “%~dp0” 会把当前目录输出两次，所以管理员执行mklink没办法创建链接

### ISSUE THREAD

**Issue by thomswang** [LorisYounger/VPet#306]
![image](https://github.com/LorisYounger/VPet/assets/15908342/0f7dbaab-d4ae-454a-a7f8-aee27a509edd)

**Comment by LorisYounger** [comment]
![image](https://github.com/LorisYounger/VPet/assets/34806646/fcfe58e5-2e52-4a83-9877-05c15015cfb2)
我测试了下,`mklink.bat`是正常可用的
`echo` 本身就是打印指令, 是给你们看的, 并不会实际操作什么东西
