### ISSUE TITLE
載入報錯

### ISSUE THREAD

**Issue by Yodinsn** [LorisYounger/VPet#307]
載入報錯(如下圖)

![image](https://github.com/LorisYounger/VPet/assets/92985237/9957b0a5-b6d6-4b88-b449-4ff32c313d59)

**Comment by LorisYounger** [comment]
看描述感觉像是FIPS的问题
可以参考下这里的FIPS解决方案 
https://steamcommunity.com/games/1920960/announcements/detail/3681184905256253203?snr=2_9_100003_

**Comment by LorisYounger** [comment]
> 嘗試加載動畫和生成緩存就卡住然後關掉了， 之前有成功進去的說QQ

那可以试试删除换成文件夹再试试?

**Comment by Yodinsn** [comment]
我重新下載後還是不行@@

**Comment by LorisYounger** [comment]
我感觉还是FIPS问题,如果你有时间的话,可以试试编译下代码跑下看看报错
编译教程也在这
https://steamcommunity.com/games/1920960/announcements/detail/3681184905256253203?snr=2_9_100003_
