### ISSUE TITLE
关于统计总结生成数据异常的问题

### ISSUE THREAD

**Issue by MeRcyRaion** [LorisYounger/VPet#308]
之前的问题 (统计总结生成卡死) 在等待更长时间 (>5min) 后已经解决，可以忽略，已修改。

在统计总结数据生成后，其中部分数据异常，包含：
- 时长超过的比例
![3](https://github.com/LorisYounger/VPet/assets/88695827/60772c1a-8877-40ac-9ce4-9438a0cd1737)
- 单次学习经验超过的比例
![4](https://github.com/LorisYounger/VPet/assets/88695827/e486a0a3-60ea-449c-8624-18309ef67d57)
- 工作总时间超过的比例
![5](https://github.com/LorisYounger/VPet/assets/88695827/67aad176-e766-4d4b-8af6-a7d0b561fee5)
- 单次工作金钱超过的比例
![6](https://github.com/LorisYounger/VPet/assets/88695827/ab29063d-e61c-42a6-a7a6-189ee7be2805)
- 累计花费
![7](https://github.com/LorisYounger/VPet/assets/88695827/014fbb0f-be52-4df0-8f9e-325c151982dd)
- 自动购买次数超过的比例
![8](https://github.com/LorisYounger/VPet/assets/88695827/2e1d2729-484f-441d-8e1d-25a50a1c3fe7)
- 订阅mod数超过的比例
![9](https://github.com/LorisYounger/VPet/assets/88695827/581dbf54-9dbc-4739-9094-31b4d129c9c6)
- 好感度超过的比例
![10](https://github.com/LorisYounger/VPet/assets/88695827/26bd1604-6af0-441c-b877-02e9f6b15f95)

同时，页面上的选项“未使用过作弊模组和修改游戏数据”和“同意上传统计数据至Steam排行榜”处于灰色状态无法被选中，即使没有修改过存档或使用超模mod，且“是没有修改过存档/使用超模mod的玩家专属标志”仍存在。
![11](https://github.com/LorisYounger/VPet/assets/88695827/0540ce17-78f1-4c19-b08f-2c59eb9f4c0a)
![12](https://github.com/LorisYounger/VPet/assets/88695827/d8bee0a1-cebc-42b9-91dc-16f90c4c1779)

如果需要更多日志文件或存档文件以诊断问题，请告诉我文件存放路径，我会上传。

**Comment by LorisYounger** [comment]
你的钱和经验数量超过排行榜统计的最大限位了(int.MaxValue = 2147483647),所以不会上传统计数据
而且你看你这钱和经验,像是没用超模mod的样子吗, 只是小标没去掉(没被我检测出来)而已

**Comment by MeRcyRaion** [comment]
> 你的钱和经验数量超过排行榜统计的最大限位了(int.MaxValue = [2147483647](tel:2147483647)),所以不会上传统计数据 而且你看你这钱和经验,像是没用超模mod的样子吗, 只是小标没去掉(没被我检测出来)而已

明白了 感谢回复 我以为用了以后小标没掉的mod都不算超模 创意工坊里找的mod自己改的
