### ISSUE TITLE
how to change language

### ISSUE THREAD

**Issue by sefinek24** [LorisYounger/VPet#311]
how to change language in this chineese spyware, idk why but i have default chineese in this
![](https://cdn.sefinek.net/static/04.01.2024/explorer_iX5kFSepUa7t.png)

**Comment by MeRcyRaion** [comment]
Two steps:
Step 1:
![4](https://github.com/LorisYounger/VPet/assets/88695827/e22af375-29a2-4d33-abc0-dfa23787d863)
Step 2:
![5](https://github.com/LorisYounger/VPet/assets/88695827/fcbd86ce-b692-495d-9962-953773c51485)
Then done:)

**Comment by sefinek24** [comment]
Okay, i had null here xd
![](https://cdn.sefinek.net/static/07.01.2024/VPet-Simulator.Windows_NS0iAKuBUeUU.png)

**Comment by MeRcyRaion** [comment]
Try en then. I guess en for English.

**Comment by sefinek24** [comment]
i ve changed, it works normal
![](https://cdn.sefinek.net/static/07.01.2024/VPet-Simulator.Windows_uVoWW3snvOHT.png)
