### ISSUE TITLE
基于文本触发的数值问题

### ISSUE THREAD

**Issue by PhoenixQAQLee** [LorisYounger/VPet#312]
新年好，我又来找事了。（不是。）
我写了一些文本，然后发现了一下不太明白的地方……然后那个模组制作器 WIKI里没有写。（大概，反正我没有找到，也可能是我的问题……）

1.为什么那些数值范围最大是2147483647？我看大部分在状态面板上上限是100，超过的部分有用吗？
2.面板上没有写上限的，比如等级和好感度和钱，上限是2147483647吗？
3.以及我发现更新之后mod编辑器不能打开core来查看里面的内容的，之后会修复吗？（不然会很难抄作业（不是））
4.我发现core里面的一些.lps里（我用记事本打开看的……）格式和我自己用mod编辑器写下的生成的.lps里的格式不太一样mm。然后注意到core里面点击对话有触发增减好感度和经验什么的，但是编辑器里没有？之后会加吗？

感谢大佬百忙之中抽空回答我的问题。（跪下）

**Comment by PhoenixQAQLee** [comment]
在第2点中补充，等级、好感度、钱还有健康度的上限。健康度！！！漏掉了（……

**Comment by PhoenixQAQLee** [comment]
以及追加
5.开心、普通状态和心情是什么样的数值关系？

**Comment by LorisYounger** [comment]
1. 在1.10版本会提高体力心情等上限
2. 因为不作弊正常玩基本上不会超过这个数值,而且这个limit是int值,最大上限就是2147483647
3. 已经修复了
4. 是不一样,core里的lps是我自己编写的,可以用更多高级的技术, mod制作器更加面向大众化
    至于以后会不会加, 看情况比较随缘(反作弊比较难做检查), 你也可以自己写lps
