### ISSUE TITLE
发现一个模组编辑器里关于【移动】的bug

### ISSUE THREAD

**Issue by PhoenixQAQLee** [LorisYounger/VPet#314]
移动设置里的状态类型右边选项里面是移动定位类型不是宠物状态。
![屏幕截图 2024-01-13 172812](https://github.com/LorisYounger/VPet/assets/154623784/c8f64b08-e8fd-4a6f-a666-f4f984629e22)

**Comment by Hakoyu** [comment]
已在 https://github.com/LorisYounger/VPet.ModMaker/commit/1b1f52d912bae53e1693590fab0c88ed40112bcf 中修复
