### ISSUE TITLE
我们能开一家服装店吗？

### ISSUE THREAD

**Issue by powerdoll** [LorisYounger/VPet#315]
![4w_sanz-video-C0RRiRBR8w3-1703547968 mp4_snapshot_00 06_ 2023 12 26_01 29 33](https://github.com/LorisYounger/VPet/assets/105698999/429bed07-db9e-4c27-a422-bb648ccb9b52)

**Comment by LorisYounger** [comment]
服装啥的相当于新画一个皮肤了, 比较复杂,以后可能会出, 目前不会
