### ISSUE TITLE
生病送礼物动画有问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#316]
![QQ截图20240123231437](https://github.com/LorisYounger/VPet/assets/49329934/34023824-0863-4b1e-810f-543cfc190bf0)
生病送礼物的动作，多了一只手

**Comment by LorisYounger** [comment]
偶尔会有的UIbug,不用在意这些细节,一般只有偶尔会出现

**Comment by CCCCCCHARA** [comment]
> 偶尔会有的UIbug,不用在意这些细节,一般只有偶尔会出现
但我这里显示这个动作一直都有问题，是我这边的问题吗

**Comment by LorisYounger** [comment]
那我回头看看,可能是我编写的有问题

**Comment by CCCCCCHARA** [comment]
> 那我回头看看,可能是我编写的有问题

好的，谢谢

**Comment by LorisYounger** [comment]
画师画的有问题,已经督促画师画了
