### ISSUE TITLE
点击输入框没有聚焦，手动设置聚焦之后，在输入的时候会失焦（必现有时候输入4个字符，有时候输入两个字符就出现失焦情况）

### ISSUE THREAD

**Issue by thomswang** [LorisYounger/VPet#317]
https://github.com/LorisYounger/VPet/assets/15908342/c19b7af5-c69e-4740-a324-3277a24fbc02

**Comment by LorisYounger** [comment]
这种更多是WPF和UI控件的锅,桌宠不背
我把这个案例分享给做UI控件的人,看他们能不能解决 @Mochengvia

**Comment by thomswang** [comment]
你在其它地方有处理聚焦失焦情况吗？ 我发现TextBox本身没有问题的，但是刚好放到这里有有问题了
