### ISSUE TITLE
点击文本可以排除萝莉斯的自带文本吗？

### ISSUE THREAD

**Issue by hatrd** [LorisYounger/VPet#318]
似乎 core 自带的点击文本，对所有宠物都生效。比如 P 猫是不带 Clicktext 的，点击会说萝莉斯的台词。这在做 mod 的时候可能会出戏。
在 mod 制作中，有什么去掉 core 里的点击文本的方法吗？

**Comment by hatrd** [comment]
更确切的说，我在mod里加的点击文本，也会影响到多开的其他桌宠。如何让点击文本在不同桌宠之间隔离？

**Comment by LorisYounger** [comment]
> 似乎 core 自带的点击文本，对所有宠物都生效。比如 P 猫是不带 Clicktext 的，点击会说萝莉斯的台词。这在做 mod 的时候可能会出戏。 在 mod 制作中，有什么去掉 core 里的点击文本的方法吗？

目前没有,未来会整个支持对应宠物的文本功能

**Comment by LorisYounger** [comment]
> 更确切的说，我在mod里加的点击文本，也会影响到多开的其他桌宠。如何让点击文本在不同桌宠之间隔离？

多开的宠物, MOD设置等设置均是分开的, 所以你可以在多开的其他宠物哪里进行设置, 设置停用MOD即可

**Comment by LorisYounger** [comment]
新增 Tag, 支持区分不同皮肤和说话内容
tag满足任意一个即可触发
