### ISSUE TITLE
I have a problem with chatgpt text translation

### ISSUE THREAD

**Issue by hyper-fan** [LorisYounger/VPet#319]
if I ask Vpet to write in English, then everything works well, but if in Russian, it bends words and sometimes writes different characters like: смилося, милынга or твоу любайшь про лабму жляковам (there are no such words, they are distorted)
![изображение_2024-01-28_005002971](https://github.com/LorisYounger/VPet/assets/136522867/fd0509b6-e6a6-4a76-993c-687e32818a17)
![изображение_2024-01-28_005125836](https://github.com/LorisYounger/VPet/assets/136522867/bdf6b78e-b258-4261-95bf-61fd8ca2f3ba)

I tried to use other models but it didn't help
I also tried to translate the initialization text for chatgpt but it didn't help

**Comment by LorisYounger** [comment]
it will fix in future version, as long as the **font** function is implemented

**Comment by LorisYounger** [comment]
The latest version v1.10 has added font function, which can change game fonts and will not have this problem again
Note: Currently, v1.10 is still in the testing branch on steam
