### ISSUE TITLE
[建议]通过分离音乐的高低频达到准确识别节拍

### ISSUE THREAD

**Issue by Siltal** [LorisYounger/VPet#320]
建议通过分离音乐的高低频达到准确识别节拍，让萝莉斯卡点

**Comment by LorisYounger** [comment]
不会这么做, 一个是好麻烦, 一个是没法对应, 一个是那样要监控用户输出和进行分析, 不过总的来说还是懒得整(
如果你会写代码的话, 也欢迎整个MOD上传创意工坊, 有啥不会的可以问我
