### ISSUE TITLE
关于AI的

### ISSUE THREAD

**Issue by MisZang** [LorisYounger/VPet#323]
我希望添加一个功能能够通过API进行调用不同牌子的AI给罗丽丝进行自定义聊天对话，且mod chatgpt for 用不了其他的apiurl

**Comment by LorisYounger** [comment]
需要使用自己的ChatGPTAPI, 自定义URL和KEY的, 请使用 聊天API: ChatGPT 支持
 https://steamcommunity.com/sharedfiles/filedetails/?id=3030831682
