### ISSUE TITLE
关于 Chat GPT 的问题

### ISSUE THREAD

**Issue by MisZang** [LorisYounger/VPet#324]
我在使用自定义 API 和密钥时 时常404与，API调用失败，我使用的是One-API的APIUrl和密钥，在其它的例如自己写的小网页上测试可以正常使用这个API和密钥，但是在使用插件 ChatGPT 时无法使用我读了代码但是找不到插件源代码一些代码我读的脑袋有些昏昏沉沉的，找问题，找的有些一头雾水，所以来反馈一下，并虚心请教。

**Comment by LorisYounger** [comment]
桌宠ChatGPT插件兼容的是ChatGPT格式的API, 用其他提供方提供的如果格式不一样会报错自然整不了
