### ISSUE TITLE
VPet.Solution build error

### ISSUE THREAD

**Issue by luanon404** [LorisYounger/VPet#325]
![image](https://github.com/LorisYounger/VPet/assets/71830807/b9c4e4d0-e123-42b6-b396-4c48aead108b)

// I really don't know how to fix this since tried everything i know.

**Comment by luanon404** [comment]
everything works fine in debug mode

**Comment by LorisYounger** [comment]
There are some things that may cause you to encounter this kind of problem
1. You have used an old version of Visual Studio and need to use Visual Studio 2022
2. Your visual studio does not have the required plugins installed, (.net Desktop development & Universal Windows development) See https://store.steampowered.com/news/app/1920960/view/7950611950256749982
3. Package reference invalid, try execute the following instruct in the Package Manager Console
`Update-Package -reinstall`

**Comment by luanon404** [comment]
# 1/ using Visual Studio 2022
# 2/ installed (.net Desktop development & Universal Windows development) with latest version

// first error, fix by add references

![image](https://github.com/LorisYounger/VPet/assets/71830807/ee8e2acb-9059-45fb-8b0d-96be17cd62d1)

// second error, tried `Update-Package -reinstall`

![image](https://github.com/LorisYounger/VPet/assets/71830807/aee8fd7e-ad19-4175-a4ee-76667f9ed060)

**Comment by luanon404** [comment]
// Panuon.WPF.UI properties
// Looks like it was not installed or broken

![image](https://github.com/LorisYounger/VPet/assets/71830807/6388aff1-37f8-4d2f-9bd7-af3c9aeca479)

**Comment by luanon404** [comment]
// fixed by removing broken Panuon.WPF.UI and adding it by browsing

**Comment by luanon404** [comment]
I don't know, but there are two reasons that need to be addressed before a successful build can be made.

1/ add VPet.Solution reference to VPet-Simulator.Windows

// Right click on VPet-Simulator.Windows

![image](https://github.com/LorisYounger/VPet/assets/71830807/a910833d-962b-47a0-ba75-1697152dd821)

// Tick on VPet.Solution, then press OK

![image](https://github.com/LorisYounger/VPet/assets/71830807/014c5f03-c6ad-4f33-9f1d-a8b1b1a98626)

2/ remove broken Panuon.WPF.UI packages in VPet.Solution, then add it by browsing.

// In solution explorer, click on VPet,Solution > References > Right click on Panuon.WPF.UI, then press remove

![image](https://github.com/LorisYounger/VPet/assets/71830807/838c05fc-1f40-4c89-a757-fd04795a520c)

// Then right click on References > Add reference...

![image](https://github.com/LorisYounger/VPet/assets/71830807/1958d710-27c8-4e41-a49b-b3cf319775ab)

// Then click on browse, browse to `F:\VPet\packages\Panuon.WPF.UI.1.1.16.8\lib\net462\Panuon.WPF.UI.dll`
// My case i put project on `F:\VPet`

![image](https://github.com/LorisYounger/VPet/assets/71830807/960de299-dfb7-4184-8eac-0575410f6d6c)

// Then setup like this and press run button

![image](https://github.com/LorisYounger/VPet/assets/71830807/3f605b46-b271-42a9-98d2-eb84492326c0)

Then, build successfully

**Comment by luanon404** [comment]
For core error, just copy & paste mod from `F:\VPet\VPet-Simulator.Windows\bin\x64\Release\net462\mod` to `D:\VPet-Simulator\mod` if you want put it in another disk

**Comment by LorisYounger** [comment]
The original problem was this, which I intentionally removed. The reason for referencing it in Release is that the reference will automatically copy a generated result to the output directory, which is convenient for me to upload to Steam
https://github.com/LorisYounger/VPet/blob/12364348ed93009801c5bafc95a35a1013e5f342/VPet-Simulator.Windows/MainWindow.cs#L37-L39
I will remove the Release Tag in the following commit

For Fixing Reference, I think some computers may not support this referencing method (which is usable on both my computer and the developer's computer, but some players may display an error message) I am trying to change the reference method to be consistent with other projects to ensure compatibility

**Comment by luanon404** [comment]
> The original problem was this, which I intentionally removed. The reason for referencing it in Release is that the reference will automatically copy a generated result to the output directory, which is convenient for me to upload to Steam
> 
> https://github.com/LorisYounger/VPet/blob/12364348ed93009801c5bafc95a35a1013e5f342/VPet-Simulator.Windows/MainWindow.cs#L37-L39
> 
> I will remove the Release Tag in the following commit
> 
> For Fixing Reference, I think some computers may not support this referencing method (which is usable on both my computer and the developer's computer, but some players may display an error message) I am trying to change the reference method to be consistent with other projects to ensure compatibility

I mean the Panuon.WPF.UI version is wrong, so the package is broken, 1.1.16.8 not 1.1.16.5.

**Comment by luanon404** [comment]
It's really bad because it took me 2 days to find it without having any knowledge.

**Comment by LorisYounger** [comment]
> It's really bad because it took me 2 days to find it without having any knowledge.

I'm sorry for the bad experience. I believe it was caused by a bug in Visual Studio
I don't have this problem on my end, and my programmers haven't encountered this problem before, so I couldn't find it

It has been fixed now. Thank you for your debugging

**Comment by LorisYounger** [comment]
> For core error, just copy & paste core mod from `F:\VPet\VPet-Simulator.Windows\bin\x64\Release\net462\mod` to `D:\VPet-Simulator\mod` if you want put it in another disk
> 
> ![image](https://private-user-images.githubusercontent.com/71830807/305682637-6688d028-e632-4f26-811e-b62a64bad0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTY3MzYsIm5iZiI6MTcwODI1NjQzNiwicGF0aCI6Ii83MTgzMDgwNy8zMDU2ODI2MzctNjY4OGQwMjgtZTYzMi00ZjI2LTgxMWUtYjYyYTY0YmFkMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjhmNjJmYjc4NzJjNWU1NTNiZGFjYzYxMTRiODZhYzFmM2U5NDEyNWZkMmUwYTc4ZjhiODdjNGIzYTMzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhW60lwj-26gb7VEmGOBVxjdUxzucviL5OHHxmiH2zQ)

For Core Error, Run Vpet-Simulator.Windows/mklink.bat as administrator. This links the mod folder to the build folder.
https://github.com/LorisYounger/VPet/blob/main/README_en.md#how-to-deploy-vpet-simulatorwindows

**Comment by luanon404** [comment]
> > For core error, just copy & paste core mod from `F:\VPet\VPet-Simulator.Windows\bin\x64\Release\net462\mod` to `D:\VPet-Simulator\mod` if you want put it in another disk
> > ![image](https://private-user-images.githubusercontent.com/71830807/305682637-6688d028-e632-4f26-811e-b62a64bad0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTY3MzYsIm5iZiI6MTcwODI1NjQzNiwicGF0aCI6Ii83MTgzMDgwNy8zMDU2ODI2MzctNjY4OGQwMjgtZTYzMi00ZjI2LTgxMWUtYjYyYTY0YmFkMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjhmNjJmYjc4NzJjNWU1NTNiZGFjYzYxMTRiODZhYzFmM2U5NDEyNWZkMmUwYTc4ZjhiODdjNGIzYTMzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhW60lwj-26gb7VEmGOBVxjdUxzucviL5OHHxmiH2zQ)
> 
> For Core Error, Run Vpet-Simulator.Windows/mklink.bat as administrator. This links the mod folder to the build folder. https://github.com/LorisYounger/VPet/blob/main/README_en.md#how-to-deploy-vpet-simulatorwindows

i wonder why you dont add it as default, the 0000_core mod folder

**Comment by LorisYounger** [comment]
> > > For core error, just copy & paste core mod from `F:\VPet\VPet-Simulator.Windows\bin\x64\Release\net462\mod` to `D:\VPet-Simulator\mod` if you want put it in another disk
> > > ![image](https://private-user-images.githubusercontent.com/71830807/305682637-6688d028-e632-4f26-811e-b62a64bad0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTY3MzYsIm5iZiI6MTcwODI1NjQzNiwicGF0aCI6Ii83MTgzMDgwNy8zMDU2ODI2MzctNjY4OGQwMjgtZTYzMi00ZjI2LTgxMWUtYjYyYTY0YmFkMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjhmNjJmYjc4NzJjNWU1NTNiZGFjYzYxMTRiODZhYzFmM2U5NDEyNWZkMmUwYTc4ZjhiODdjNGIzYTMzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhW60lwj-26gb7VEmGOBVxjdUxzucviL5OHHxmiH2zQ)
> > 
> > 
> > For Core Error, Run Vpet-Simulator.Windows/mklink.bat as administrator. This links the mod folder to the build folder. https://github.com/LorisYounger/VPet/blob/main/README_en.md#how-to-deploy-vpet-simulatorwindows
> 
> i wonder why you dont add it as default, the 0000_core mod folder

Because the mod folder is too big, if you set it to auto-copy, it will be copied 4 times for people who are developing 4 versions. #281
Use a script to set it as a link, it will save a lot of space.

**Comment by luanon404** [comment]
> > > > For core error, just copy & paste core mod from `F:\VPet\VPet-Simulator.Windows\bin\x64\Release\net462\mod` to `D:\VPet-Simulator\mod` if you want put it in another disk
> > > > ![image](https://private-user-images.githubusercontent.com/71830807/305682637-6688d028-e632-4f26-811e-b62a64bad0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTY3MzYsIm5iZiI6MTcwODI1NjQzNiwicGF0aCI6Ii83MTgzMDgwNy8zMDU2ODI2MzctNjY4OGQwMjgtZTYzMi00ZjI2LTgxMWUtYjYyYTY0YmFkMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjhmNjJmYjc4NzJjNWU1NTNiZGFjYzYxMTRiODZhYzFmM2U5NDEyNWZkMmUwYTc4ZjhiODdjNGIzYTMzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhW60lwj-26gb7VEmGOBVxjdUxzucviL5OHHxmiH2zQ)
> > > 
> > > 
> > > For Core Error, Run Vpet-Simulator.Windows/mklink.bat as administrator. This links the mod folder to the build folder. https://github.com/LorisYounger/VPet/blob/main/README_en.md#how-to-deploy-vpet-simulatorwindows
> > 
> > 
> > i wonder why you dont add it as default, the 0000_core mod folder
> 
> Because the mod folder is too big, if you set it to auto-copy, it will be copied 4 times for people who are developing 4 versions. #281 Use a script to set it as a link, it will save a lot of space.

Ahh okay, thank you for your response. All problems have been solved. Have a nice day!

**Comment by LorisYounger** [comment]
Thanks again for catching this issue. When I was testing the bug for other players, I thought it was an installation problem.
