### ISSUE TITLE
关于运行 ChatGPT for 创意工坊作者 (x64) 代码插件时的错误

### ISSUE THREAD

**Issue by Guo-Jiachang** [LorisYounger/VPet#327]
https://github.com/LorisYounger/VPet/assets/124495577/0bd6860b-0861-45e1-856f-e63ad3faa383

可以透过此录制查看错误信息。
希望这对你有帮助。

**Comment by LorisYounger** [comment]
这个报错很怪, StartDate 和 UtcNow 不可能是NULL, 不可能报错这个

**Comment by LorisYounger** [comment]
修不了, 不过我改了下结构, 后续更新上去看看还有没有, 更新了我发个评论给你

**Comment by LorisYounger** [comment]
已经更新, 你看看还有BUG吗

**Comment by LorisYounger** [comment]
> 是的，错误同样发生了。不过这次似乎有了新的错误信息，可以透过此录制查看错误信息。
> 
>  default.mp4 
> 希望这对你有帮助。

需要使用最新版本VPET (v1.9 24/02/19), 你需要更新下游戏代码

**Comment by LorisYounger** [comment]
这次应该修好了, 是steam反馈的时候有时候会给null, 现已修复
