### ISSUE TITLE
关于移动范围选择的反选功能添加

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#329]
由于有时候不希望桌宠爬到特定范围（比如在写文档的时候进入到文档窗口的范围），同时也不希望桌宠只能在一个小角落爬，因此希望能够有一个反选范围的功能。因为感觉这个功能可能意义不大，所以打算通过写插件MOD实现该功能，但官方没有提供对应的接口。
反选功能在本人经过测试，有以下实现思路：
![无标题](https://github.com/LorisYounger/VPet/assets/49329934/3bd58426-31dc-423e-8eb0-b4809c86e7fb)

比如判断桌宠是否能向左走，即GetWindowsDistanceLeft方法：
```
            //反选情况
            int realLeftBorder = 0; //记录真正的边界是哪一个，初始是屏幕左侧
            int upRange = Math.Max(0, ScreenBorder.Y); //超出屏幕的部分不需要了
            int downRange = (int)Math.Min(System.Windows.SystemParameters.PrimaryScreenWidth, ScreenBorder.Y);
            //判断桌宠当前位置向左移动是否可能会被反选框的右边界挡住
            if (mw.Top + mw.Height >= upRange && mw.Top <= downRange)
                //判断桌宠的右边界在反选框右边界的右边 && 反选框右边没有超出屏幕
                if (mw.Left + mw.Width > ScreenBorder.X + ScreenBorder.Width
                && ScreenBorder.X + ScreenBorder.Width < System.Windows.SystemParameters.PrimaryScreenWidth)
                    realLeftBorder = ScreenBorder.X + ScreenBorder.Width; //真正的边界更新为反选框的右边界
            return mw.Left - realLeftBorder;
```

其余方向类似，不过由于原版范围移动的代码扩展性一般，如只用了IsPrimaryScreen一个bool型属性判断移动是否是主屏幕移动。
如果官方有意向添加该功能，该思路是否可取？如果暂时不考虑支持该功能，我是否可以PR一个修改后的版本？

**Comment by LorisYounger** [comment]
我目前没有计划做反选功能, 担心有bug, 毕竟目前的桌宠边缘距离判断塞了太多东西, 以及后面还有许多改动, 一些并不是我写的

如果你想做MOD, 其实可以直接 继承 `IController` 写个新的判断程序, 然后在`Load`里面替换给 `MW.Core.Controller = new YOUController(...);` 就行

如果需要代码插件MOD参考, 可以参见 https://github.com/LorisYounger/VPet.Plugin.Demo

**Comment by CCCCCCHARA** [comment]
明白了，谢谢回复
