### ISSUE TITLE
希望ChatGPT自定义api支持代理

### ISSUE THREAD

**Issue by liugodg** [LorisYounger/VPet#33]

**Comment by LorisYounger** [comment]
代理啥的做起来感觉很麻烦,我也没有相关经验,以后有空了可以研究下

**Comment by HarukaB** [comment]
可以考虑用Clash的TUN模式之类的东西，并在软件里面设置规则代理，对所有应用都有效

**Comment by LorisYounger** [comment]
> 可以考虑用Clash的TUN模式之类的东西，并在软件里面设置规则代理，对所有应用都有效

解决方案/|\
这个先不优先整,以后再看吧

**Comment by shiquda** [comment]
还是希望作者可以做个自定义代理，比如说走本地指定端口。我这边官方api开了全局代理都不行，用上proxifier才可以，但是这样对系统环境影响太大了

**Comment by CaliInn-Li** [comment]
同希望添加代理功能，网络非常麻烦qaq
