### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by johnisaway285** [LorisYounger/VPet#330]
Good day, just wondering if you are willing to add support for linux users? When I run the program, it doesn't seem to run pretty well on linux becuase of Wine and Proton.

Thank you.

**Comment by LorisYounger** [comment]
Sorry, I don't have any plans to make a Linux version recently because I don't know how to write Linux UI
Recently, VPet v1.10 version is being migrated to .Net 8. VPet v1.20 will separate display and logic, making it easier to develop multiple platforms

**Comment by olivertzeng** [comment]
> Sorry, I don't have any plans to make a Linux version recently because I don't know how to write Linux UI
> Recently, VPet v1.10 version is being migrated to .Net 8. VPet v1.20 will separate display and logic, making it easier to develop multiple platforms

How about now? Or is it at least able to run on wine?
