### ISSUE TITLE
上传 mod 文件可不可以排除 .git 文件夹

### ISSUE THREAD

**Issue by hatrd** [LorisYounger/VPet#342]
现在的上传把整个文件夹传上去了，要是排除 .git 的话会舒服一点

https://github.com/LorisYounger/VPet/blob/b9ce792a6cfc3522d408b0ca015c5b44f2220b16/VPet-Simulator.Windows/WinDesign/winGameSetting.xaml.cs#L687

**Comment by LorisYounger** [comment]
MOD文件夹只放MOD用的内容就行, 你可以把git啥的放外面, 可以参考下我这边也是放在外面的
https://github.com/LorisYounger/VPet.Plugin.Demo/tree/main/VPet.Plugin.ChatGPT
