### ISSUE TITLE
卡巴斯基对桌宠启动程序报毒

### ISSUE THREAD

**Issue by jaykserks** [LorisYounger/VPet#343]
# 卡巴斯基安全软件对启动程序报毒
2024年4月3日启动桌宠时,卡巴斯基对其启动程序报毒.
报毒类型为" **UDS:DangerousObject.Multi.Generic** ", 并强制删除相关启动程序.
    
问题环境
-  Windows 11 23H2
-  Steam端下载启动
-  卡巴斯基版本: 21.3.14.434
-  卡巴斯基病毒特征库: 2024/4/1 12:05:00

**Comment by LorisYounger** [comment]
> # 卡巴斯基安全软件对启动程序报毒
> 2024年4月3日启动桌宠时,卡巴斯基对其启动程序报毒. 报毒类型为" **UDS:DangerousObject.Multi.Generic** ", 并强制删除相关启动程序.
> 
> 问题环境
> 
> * Windows 11 23H2
> * Steam端下载启动
> * 卡巴斯基版本: 21.3.14.434
> * 卡巴斯基病毒特征库: 2024/4/1 12:05:00

看了下并不是, 我看的时候没签名是因为我也用了卡巴斯基,我关掉卡巴斯基后就能看到软件签名了
估计是纯纯的误报, 我拿steam文件到 www.virustotal.com 上查了下没问题
![image](https://github.com/LorisYounger/VPet/assets/34806646/538fa153-ca73-4582-88ae-3e73fe91a09d)
也不知道是撞了啥病毒特征,希望这次生成能好

**Comment by LorisYounger** [comment]
v1.10.03生成版本已经没有误报问题了, 不过因为v1.10.02被卡巴斯基误报导致文件被锁定,可能没法升级v1.10.03. 我这边正在和卡巴斯基工作人员bettle, 后面解除误报应该就没啥事了

**Comment by LorisYounger** [comment]
为了方便大家看到,还是先打开这个issue

**Comment by LorisYounger** [comment]
![image](https://github.com/LorisYounger/VPet/assets/34806646/7d8c7d82-5615-4aba-913f-e351cfdab644)
尊敬的用户您好！

感谢等候

专家已回复，反馈是误报问题，会在下次数据库更新修复，预计24小时内修复好还请耐心等候

谢谢

Jack
