### ISSUE TITLE
卡巴斯基对程序依赖文件报毒

### ISSUE THREAD

**Issue by TomSteve1102** [LorisYounger/VPet#344]
事件: 检测到恶意对象
用户: ***************
用户类型: 活动用户
应用程序名称: CompatTelRunner.exe
应用程序路径: C:\Windows\System32
组件: 文件反病毒
结果说明: 检测到
名称: UDS:DangerousObject.Multi.Generic
精确度: 确切
威胁级别: 高
对象类型: 文件
对象名称: VPet-Simulator.Windows.exe
对象路径: E:\game\steamapps\steamapps\common\VPet
MD5: 72D8BC30E87ADF31A6F53A0F0BCA33D6
原因: 云保护

![avpui_ehCR064h1h](https://github.com/LorisYounger/VPet/assets/26663350/d99c9ade-21d2-4db3-baa7-1929b63615c7)

**Comment by LorisYounger** [comment]
![image](https://github.com/LorisYounger/VPet/assets/34806646/781bce92-1dce-4a2d-84e5-9c6b3477ba06)
桌宠没这个文件吧

**Comment by LorisYounger** [comment]
如果是  VPet-Simulator.Windows.exe , 那就是 1.10.3又被卡巴斯基误报了, 今天卡巴斯基清明节休假, 没回复
我已经滚回到v1.10.02 之前被卡巴斯基验证过的版本了

**Comment by TomSteve1102** [comment]
> 如果是 VPet-Simulator.Windows.exe , 那就是 1.10.3又被卡巴斯基误报了, 今天卡巴斯基清明节休假, 没回复 我已经滚回到v1.10.02 之前被卡巴斯基验证过的版本了

这个问题出现在 test_branch 测试分支里，回到正式版就正常了
