### ISSUE TITLE
[Suggestion] Create support for Linux Distributions

### ISSUE THREAD

**Issue by floofyneko69** [LorisYounger/VPet#345]
Because VPet is C# based, as noted by the extensions of most of the files, it's worth mentioning that C# has support towards developing and running applications on Linux based distributions.

I'm suggesting this as both WineHQ and Steam Proton both cause a minor issue where the transparent background of the window renders as black, and this issue looks to have persisted for a long time. I'm assuming WineHQ and/or Steam aren't planning to fix this issue for one reason or another, so I'm making this suggestion since it would probably be easier to do thanks to C# support for Linux.

**Comment by LorisYounger** [comment]
The main problem is that I am not familiar with Linux UI development, I only know WPF
For the support of migrating to multiple systems, in version 1.10, I migrated the project from .net462 to .net8. 
However, the UI and code-related content have not been separated. In version 1.20, I will completely separate the code and UI in the project.
Although it is said so, in the current version, it is very convenient to develop a version for a cross-platform. If anyone encounters any problems in developing VPet for different platforms, please feel free to contact me.
