### ISSUE TITLE
[Suggestions] Automatic language for first start

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#348]
The steam store page of the game is in english for none chinese users.
If you have installed the game and then start it the first time, the game is always in chinese language.
To change the language the user needs to guess the correct menu and that will be a huge turn off to many people trying this game out.

So much suggestion:
On first start, please check if the user is from china. If not, use the english language for first start.

Maybe you can check the user's language for example with:
- steam language
- system language

**Comment by LorisYounger** [comment]
The default language for the game should be English. I will check again
