### ISSUE TITLE
Mod description text can not be translated in some cases

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#349]
### file: info.lps

If you use a special symbol (most frequently the , ) it will geht changed to "/com" after uplading the mod.
**Text with "/com" inside can not be translated.**

For example:
=========================================
vupmod#modname:|author#creator:|gamever#11000:|ver#301:|
intro#great mod/com i guess.:|
itemid#0000000000:|
lang#en:|modname#modname:|modname#modname:|
lang#zh-Hans:|模组名称#模组名称:|modname#模组名称:|
lang#zh-Hant:|模组名称#模组名称:|modname#模组名称:|
=========================================

**Comment by LorisYounger** [comment]
I checked and found that it's because in the name, the translation file needs to be displayed in a non-escaped way. In your example, the translation is
```
lang#en:|great mod, i guess#great mod/com i guess:|
```

**Comment by LorisYounger** [comment]
Is this a problem caused by the MOD maker?
