### ISSUE TITLE
一些建议 - 动画分层

### ISSUE THREAD

**Issue by Byelliot** [LorisYounger/VPet#35]
互动中的动画可以采用投喂里的方式-分层 
直接使用png即可实现内容的替换
![T_5}W6C~VZBKXQ%Q{0(ETTT](https://github.com/LorisYounger/VPet/assets/39994633/03cc92f8-f236-4a95-adf7-cedbe2d6b43b)

如 玩游戏可以替换书本等png图标以达到内容替换的效果代码实现
只需要对图片进行位移即可或简单的两三帧动画
![NYZ6EQA(QOH9NGL 0%P K{T](https://github.com/LorisYounger/VPet/assets/39994633/994bae10-d477-4d05-810f-5bd8d5ef28a1)

拓展
对所有动画进行分层有利于降低mod的制作的难度和提高制作的效率降低门槛
![%_MISL5$SGX_ 8@5Y@E)`$2](https://github.com/LorisYounger/VPet/assets/39994633/ddec1a75-018d-4133-9475-d87d697f2369)

当然就可以多个皮肤系统 背景系统 桌子系统等等换皮功能 
其他动画序列的制作可以写个程序来可视化操作直接读取即可播放序列动画

发现里面的动画都是写死的，对于不会绘画的人来说有点难以去制作动画
但是现在有很多ai绘图工具，绘画来说是十分便利的，这就很方便了

**Comment by LorisYounger** [comment]
分层后面还是没做了, 看上去加个帽子啥的很简单,但是桌宠脑袋位置其实并不确定,不是简单p个帽子之类的能解决的, 而且做起来也麻烦,就取消掉了
