### ISSUE TITLE
联机动画同步播放建议

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#353]
由于移动动画触发概率较大，且持续时间较长，建议同步该类型的动画(可以不同步位置)
同时，当他人桌宠播放坐下动画或侧躺动画时，在本机显示效果为这两个动画快速反复切换

**Comment by LorisYounger** [comment]
概率应该都是一样差不多的, 不过持续时间是长一些

**Comment by CCCCCCHARA** [comment]
> 概率应该都是一样差不多的, 不过持续时间是长一些

时间比较长，如果不同步显示的话很多时候就是待机动画不动了

**Comment by CCCCCCHARA** [comment]
“同时，当他人桌宠播放坐下动画或侧躺动画时，在本机显示效果为这两个动画快速反复切换”这一点仍然没有修复
