### ISSUE TITLE
模组修改版本号，保存报错。

### ISSUE THREAD

**Issue by CAI220** [LorisYounger/VPet#355]
![163276383553ec79020cfd836bf8e50](https://github.com/LorisYounger/VPet/assets/115921597/f1d612e0-b453-436e-bc23-c479d3a6244f)
部分模组在修改版本保存之后报错。不知为何？

**Comment by LorisYounger** [comment]
游戏里先不要启用自己的模组, 是文件占用的问题
后续会让mod制作器遇到报错时跳过
