### ISSUE TITLE
范围设为“当前屏幕”时桌宠移动出界问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#360]
范围设置为当前屏幕时，如果系统调整过缩放，该范围窗口范围会不正确，如：
![20240418120027](https://github.com/LorisYounger/VPet/assets/49329934/032e30cb-ad2e-46ce-9bdd-8f07a34d7c0b)
很明显看到该窗口已经超出当前屏幕的大小

希望能够修改BtnSetMoveArea_DetectScreen_Click方法，使其符合当前显示

**Comment by LorisYounger** [comment]
Assignees @YukkuriC
