### ISSUE TITLE
自动喂食逻辑问题与建议

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#365]
这是一位玩家的存档数据
![QQ图片20240423145052](https://github.com/LorisYounger/VPet/assets/49329934/fc9d3315-8ea4-4c6d-9cbe-eac8c7266d8f)

可以看到该玩家的饱腹度最大值为485(图片标注有误，不过不影响最终结果)，未正确触发自动喂食
原因如下：
![QQ图片20240423145107](https://github.com/LorisYounger/VPet/assets/49329934/16670cd7-e85b-404e-a1c2-c0fb8af4eb3c)
![QQ图片20240423145112](https://github.com/LorisYounger/VPet/assets/49329934/07e2e6db-2eb1-427f-a804-6d7ec1bf6324)

在此建议修改自动喂食的逻辑，不再限定最大值，而是按照**数值增加/花费金钱比值大小**或其它更加好的方式解决该问题

附上原版比较明显的选择问题：
当心情上限较高的时候，只会选择+50的零食，但实际上+40的零食更加实惠，但不会被选择到
![QQ截图20240423145455](https://github.com/LorisYounger/VPet/assets/49329934/79b84d0f-8e95-4bb7-a1aa-be37cb6dda62)
![QQ截图20240423145647](https://github.com/LorisYounger/VPet/assets/49329934/0986037e-7c39-406b-bc4c-dcc78ec25372)

**Comment by YIYuNCU** [comment]
建议增加食物倍率，以改善该问题和高等级工作下食物喜好度消耗过快问题
