### ISSUE TITLE
商品喜好度相关问题

### ISSUE THREAD

**Issue by YIYuNCU** [LorisYounger/VPet#366]
商品喜好度本意是鼓励玩家选择更多种商品，但在当下高等级饱腹度，口渴度，心情上限较高，工作消耗较快的情况下，反而对使用自动投喂的玩家产生了负面影响，使不加mod的玩家很快就全商品50喜好度
基于以上情况，希望自动购买的时候喜好度不和商品属性挂钩，而是和选择商品概率挂钩，通过以喜好度设置权重，加权随机来选择商品，以此来在自动投喂时选择多样化商品，在手动购买时喜好度还与商品属性挂钩来鼓励选择多样化商品

**Comment by LorisYounger** [comment]
喜好度已经进行过调整了, 好吃的食物甚至基本上不掉喜好度, 自动投喂的系统也调整过
参见 #356 请更新至最新版
