### ISSUE TITLE
建议：提供设置备份功能

### ISSUE THREAD

**Issue by Leo204-LKY** [LorisYounger/VPet#367]
已经多次出现打开桌宠时设置全部重置的问题，每次都需要重新调整设置并启用 Mod，非常麻烦
之前有看到过相关的 Issue，但似乎并没有解决问题，作为替代能否提供设置备份功能，供用户在出现问题的同时快速恢复至原来的设置

**Comment by YIYuNCU** [comment]
你可以自己复制一份setting.lps，发现设置清空了以后再粘贴回去

**Comment by LorisYounger** [comment]
其实有的，就是setting.bkp,也会在设置清空时读取



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Evian ***@***.***&gt;
发送时间: 2024年4月30日 12:37
收件人: LorisYounger/VPet ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LorisYounger/VPet] 建议：提供设置备份功能 (Issue #367)





 
你可以自己复制一份setting.lps，发现设置清空了以后再粘贴回去

**Comment by Leo204-LKY** [comment]
> 其实有的，就是setting.bkp,也会在设置清空时读取 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Evian ***@***.***&gt; 发送时间: 2024年4月30日 12:37 收件人: LorisYounger/VPet ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [LorisYounger/VPet] 建议：提供设置备份功能 (Issue #367) 你可以自己复制一份setting.lps，发现设置清空了以后再粘贴回去 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

有备份设置的情况下那为什么还会出现读取设置失败的问题，失败后的情况就跟第一次启动一样会弹出教程网页
总之我自己也备份一下吧，感谢帮助
