### ISSUE TITLE
关于口渴文本的疑惑

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#368]
![QQ截图20240430121526](https://github.com/LorisYounger/VPet/assets/49329934/e8aa00a0-2c42-4ef7-ae14-ed3b3d6a38ae)
以上为桌宠自动触发口渴时的文本
为什么在桌宠口渴的时候，桌宠会对玩家说“玩家渴了就喝水，别扒拉桌宠的腿”
而且多人反映该文本可能具有不良暗示

**Comment by LorisYounger** [comment]
我们会回去讨论有关于这个以及其他台词的正确性，感谢你的反馈
