### ISSUE TITLE
关于动画的一些小问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#369]
1.从侧躺的动画变成坐下的动画时衔接不自然
![动画](https://github.com/LorisYounger/VPet/assets/49329934/5d8dafb0-c191-43b0-9607-bc3e3f39d834)
2.口渴提示动画没有不同心情的差分，不清楚原本设计是否有差分
![QQ截图20240502115452](https://github.com/LorisYounger/VPet/assets/49329934/8aa9a361-2e27-4cae-aa5a-c496eb400b78)
3.在窗口上方爬行的结束动作帧是否放反了？(将其反过来之后似乎更自然一些)
![20240502172648](https://github.com/LorisYounger/VPet/assets/49329934/bc20cc04-8733-46fd-949b-d135fe219195)

小问题:
![kouke_003_500](https://github.com/LorisYounger/VPet/assets/49329934/0f660937-b5b4-49a2-8b79-54933b4caed7)
(口渴动画，有点超出边界)
![_003_125](https://github.com/LorisYounger/VPet/assets/49329934/5f5cf5e8-75e0-4608-be91-3468b2a8a5d4)
(walk.right.faster\B_Happy\_003_125.png，一个青色的点)

**Comment by LorisYounger** [comment]
最后这个应该修过才对, 我回头看看

**Comment by LorisYounger** [comment]
3: 我感觉目前的更自然一些, 这个动画结束后可能会回归正常占位或直接向下飞或从右侧屏幕趴下去

**Comment by CCCCCCHARA** [comment]
> 3: 我感觉目前的更自然一些, 这个动画结束后可能会回归正常占位或直接向下飞或从右侧屏幕趴下去

实际上我觉得这个结束动画不管是怎么个排列顺序都不是很自然，理由如下:
如果按照原顺序，符合图片逻辑(第一帧一只手脱手，第二帧两只手脱手)，但第二帧结束回到正常站立姿态很突兀(实际看动画的时候我觉得就是一闪回到站立姿态的，我不清楚在那种姿势下如何回到站立姿态)
不过我觉得应该交给玩家评判，比如向群里询问

**Comment by LorisYounger** [comment]
1.从侧躺的动画变成坐下的动画时衔接不自然
已在 https://github.com/LorisYounger/VPet/commit/7a91411184b10e519091493dccd617fb8f1e6bbd 修复

2.口渴提示动画没有不同心情的差分，不清楚原本设计是否有差分
小问题2

已在 链接待补充 修复

**Comment by LorisYounger** [comment]
还差小问题
已在 链接待补充 修复

**Comment by CCCCCCHARA** [comment]
最近commit的部分也有一点问题

**Comment by CCCCCCHARA** [comment]
> 最近commit的部分也有一点问题

在comment写了，这里就不写了

**Comment by LorisYounger** [comment]
已在 https://github.com/LorisYounger/VPet/commit/31bed95a434aad3fa8b5aa4545ac29f3822e62fc 全部修复
