### ISSUE TITLE
关于桌宠置顶显示问题

### ISSUE THREAD

**Issue by YIYuNCU** [LorisYounger/VPet#370]
能否添加判断，使桌宠在游戏（全屏）模式下不置顶显示，在其他情况下置顶显示

**Comment by LorisYounger** [comment]
桌宠本来在 真全屏 的时候不显示(独占显示器) 
在其他情况下显示
一些游戏使用的是虚假的全屏, 并不是真全屏, 你可以通过菜单栏小标手动关下置顶
![image](https://github.com/LorisYounger/VPet/assets/34806646/4982cfe5-8193-454d-9f09-f7d86a1ee0bc)
