### ISSUE TITLE
关于桌宠缩放问题

### ISSUE THREAD

**Issue by YIYuNCU** [LorisYounger/VPet#371]
能否在缩放桌宠的同时保持桌宠显示文本的字体大小不变（允许自己设置显示文本的字体大小）

**Comment by LorisYounger** [comment]
做不到, 桌宠用的是viewbox固定缩放定位, 没法改单独修改显示字体大小. 如果有需求并且自己会代码的话,可以自己改一个版本做成创意工坊发
