### ISSUE TITLE
一个屏幕缩放小问题

### ISSUE THREAD

**Issue by kieli233** [LorisYounger/VPet#372]
我的笔记本比较特殊，属于二合一这类产品，所以屏幕尺寸也就12寸左右，屏幕分辨率是2560*1600，缩放150%。有时桌宠乱跑，总跑到一些奇奇怪怪的地方(屏幕显示之外)。把缩放调回100%又可以看见。

**Comment by CCCCCCHARA** [comment]
你选择的屏幕范围是主屏幕还是设为当前屏幕？

**Comment by kieli233** [comment]
![屏幕截图 2024-05-04 113751](https://github.com/LorisYounger/VPet/assets/75947378/27585bfc-161d-41d7-bdc6-df1519a0c38e)
默认

**Comment by CCCCCCHARA** [comment]
你缩放在150%时点一下设为当前屏幕看看

**Comment by kieli233** [comment]
![屏幕截图 2024-05-04 114700](https://github.com/LorisYounger/VPet/assets/75947378/6e81c574-8b0b-4dea-8c67-f14082c6746f)
笔记本上的移动范围设置基本没动过，台式机倒是设置在副屏

**Comment by CCCCCCHARA** [comment]
所以你现在这个移动有问题的屏幕，缩放在150%的情况下，点击设为当前屏幕，移动区域有没有变化

**Comment by kieli233** [comment]
这不清楚了，设置之后只显示`主屏幕`，而不是以往的坐标

**Comment by CCCCCCHARA** [comment]
我说的是点“设为当前屏幕”

**Comment by kieli233** [comment]
当前不就是图片内容吗？我还特地截图

**Comment by CCCCCCHARA** [comment]
那既然设置完了，这个数字应该就对得上，你用开发控制台-距离查看器去移动桌宠看看

**Comment by kieli233** [comment]
没什么问题了

**Comment by LorisYounger** [comment]
没问题我就关闭了
