### ISSUE TITLE
Page number does not reset when changing categories in betterbuy [BUG]

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#376]
When a page in a certain category is selected, it does not reset to page 1 when changing categories.
Expected was page 1.

![VPet-Simulator Windows_zH8PLl3xwa](https://github.com/LorisYounger/VPet/assets/155199582/b76fb459-cec7-4459-b5dd-c21108196dad)

**Comment by LorisYounger** [comment]
I deliberately left this out because when switching varieties, it can retain the sorting part.
This is very useful for observing price and other sorting.
I think so. If you think there are other problems with this function, please continue to discuss.
