### ISSUE TITLE
捏脸结算问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#377]
捏脸只会结算一次加心情(心情未满)，而且如果在捏的时候鼠标离开窗口，仍然会播放捏脸动画（似乎以前修过，但现在又出现了）

**Comment by LorisYounger** [comment]
捏脸只会结算一次加心情: 确实有,
而且如果在捏的时候鼠标离开窗口，仍然会播放捏脸动画 没修过,修不了,反正不是大问题,算了

**Comment by CCCCCCHARA** [comment]
![QQ截图20240514094240](https://github.com/LorisYounger/VPet/assets/49329934/2568aac5-1664-465d-bcf5-541069565d41)
确实说不上什么大问题，不过修过

**Comment by LorisYounger** [comment]
看了下commit,修的好像不是捏脸移出,而是挥动时如果在长按则不显示, 我也不知道当初咋想的
