### ISSUE TITLE
Changing the language does not take full effect until game restart [SUGGESTION]

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#378]
When changing the language in the settings many translations will be loaded but not all. A game restart is required to load all translations.

Even when a loading time is needed, i would prefer the full translation to be visible on change without restarting the game.

Is this possible?

**Comment by LorisYounger** [comment]
It's impossible, because the content is added in text (string). The part that can display the translation in real time is the UI (WPF) part
However, I will add a button `try to restart`, so that players know that only by restarting can they see the fully translation
