### ISSUE TITLE
开启开机自启提示创建快捷方式失败，权限不足

### ISSUE THREAD

**Issue by ytdttj** [LorisYounger/VPet#38]
![image](https://github.com/LorisYounger/VPet/assets/13082302/2006057f-40d5-42f9-9a36-d41eaba2d83f)
程序已经使用管理员身份启动

**Comment by LorisYounger** [comment]
可能是杀软之类的拦截了,或者其他啥原因, 桌宠自身没法处理,你可能需要手动让桌宠开机自启
[如何设置让软件开机自启动？三步搞定！](https://zhuanlan.zhihu.com/p/265076894)
