### ISSUE TITLE
判断设置是否损坏而读取设置备份

### ISSUE THREAD

**Issue by iduee** [LorisYounger/VPet#385]
有时候电脑蓝屏，桌宠会丢失设置，已设置过的选项被重置，MOD恢复成未开启状态

**Comment by LorisYounger** [comment]
在1.15版本中, 有备份设置的功能. 如果没有设置文件,则会读取备份, 经过测试, 这个功能是正常的.
我猜测你的问题是正好在写入设置的时候关机/蓝屏, 导致设置写了一半损坏了.
后续加载设置的时候加载的是损坏的设置, 而并非设置备份
以后可以整个判断设置是否损坏的功能
