### ISSUE TITLE
Window size for translation needs (Please!)

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#387]
Hey there!

While translating the game sometimes the windows are too small to fit all text in it. In some languages the words or texts are longer.

Inside the settings window it was possible to use some of this:
SettingWidth#1040:|
SettingHeight#800:|
SettingMenuWidth#1:|
SettingMenuHeight#800:|

In version 11020 i looks like this variables are not longer working for height anymore. For me its always 550px height in settings window.
(might be a bug?)

### But the real question is:
**Can we get an width and hight for every window of the game?**

1. betterbuy
2. statistics
4. interactions
5. guest list
6. settings
7. feedback
8. console
9. mod maker start window
10. mod maker main window

**Comment by LorisYounger** [comment]
for mod maker, I will update it later. Welcome to reopen the issue to [ModMaker](https://github.com/LorisYounger/VPet.ModMaker) or PR
By the way, all enhancement and bug issues can be PR, no need to ask me separately
