### ISSUE TITLE
Missing level (muti adjust) of current working/ learning/playing and schedules

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#388]
Hey there!

When using the "Muti adjust" and start the working/ learning/playing or schedules process, you can not tell what level (muti adjust) is currently used.
This would be a good thing to know!

(By the way is "Muti adjust" the correct spelling?)

![grafik](https://github.com/LorisYounger/VPet/assets/155199582/63f75f79-20e1-40d5-9e46-b9cb583bd845)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/f92cc8ff-dcb5-48b4-9ea2-17e46df904d0)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/465395a8-b72b-4477-8546-e0e6819380ae)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/ce5e33f0-aac6-430a-99bc-b3949bf5015e)

**Comment by LorisYounger** [comment]
Full name is `Multiplication adjustment`
Used to double the work of the game and improve efficiency
The doubling equation is `(level+10)*doube_value`
so you can see the first double is from `0` to `(0+10)*2=30`. This is normal

**Comment by LorisYounger** [comment]
That magnification only takes effect when it starts working, and it cannot be adjusted in real time during work. 
I didn't add the magnification to the work timer box because I didn't think it was a crucial parameter that needed to be displayed immediately
