### ISSUE TITLE
Starting a favorite is always using "Start Working" string

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#389]
Hey there!

There is a different string for every type of activity:
Start Working
Start Learning
Start Playing

but in the "Favorites" menu inside the work panel "Start working" is always used, regardless of the selected entry.

![grafik](https://github.com/LorisYounger/VPet/assets/155199582/7037af9f-4e90-4c42-a19f-9c25eff39e68)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/8afb88e9-ce03-4555-adb4-5abc90543a01)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/6888f3c8-0c35-4309-a492-34488da50b67)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/fd826fdd-911c-4510-bf3d-5f07d968728a)

suggestion:
1. change the button text when selecting the type of work content (work, learn, play)

or

2.  create a new string for starting activity (or something like that)

**Comment by LorisYounger** [comment]
Because I was lazy and didn't write targeted texts for Favorites.
`starting activity` is cool, I will update for next time
