### ISSUE TITLE
Schedule is in wrong status after game restart (bug)

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#391]
Hey there!

I have started a schedule and closed the game. After starting the game again my VPet was in idle but when i wanted to start my schedule again, the button got "Stop Schedule" label.
This is wrong because the Schedule was not active at this point.

Screenshot after game restart while schedule was started:
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/39adc62d-9a65-4615-9f32-c916cf519c03)

**Comment by LorisYounger** [comment]
In fact, it is already on the schedule. By default, every time it is launched, it will determine whether it is on the schedule based on the last enabled state.
Your current schedule is on break, so it doesn't seem to have started yet.
