### ISSUE TITLE
希望能出一份关于制作新的桌宠动画的教程

### ISSUE THREAD

**Issue by LittleFish-233** [LorisYounger/VPet#40]
今天被群友安利了这个桌宠模拟器，感觉很有意思，想自己做一个全新人物的桌宠动画。

但是目前遇到了一些问题，我看了一下core的模组里面的文件，对vup.lps里面有一些参数不太理解，还有Drink文件夹下的info.lps里是怎么实现分图层动画的，是不是其他动作也可以这样实现分图层动画？还有这些文件夹的命名有什么要求吗？

希望大佬能出一份关于制作新的桌宠动画的教程，非常感谢！

**Comment by LorisYounger** [comment]
正在做相关工具ing

**Comment by LorisYounger** [comment]
Mod工具(未完成) 见
https://github.com/LorisYounger/VPet.ModMaker
