### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by kt030415** [LorisYounger/VPet#402]
在检测到游戏或者视频全屏时自动取消置顶，添加主屏副屏之间穿梭的功能（有动画就更好了）

**Comment by LorisYounger** [comment]
**在检测到游戏或者视频全屏时自动取消置顶**
桌宠本来在 真全屏 的时候不显示(独占显示器) #370
在其他情况下显示
一些游戏使用的是虚假的全屏, 并不是真全屏, 你可以通过菜单栏小标手动关下置顶
![image](https://github.com/LorisYounger/VPet/assets/34806646/4982cfe5-8193-454d-9f09-f7d86a1ee0bc)
**添加主屏副屏之间穿梭的功能（有动画就更好了）**
做起来非常麻烦,而且受用面小. 目前没有相关计划

**Comment by LorisYounger** [comment]
**在检测到游戏或者视频全屏时自动取消置顶**
那些检查都需要管理员权限, 不会做的 #294
桌宠的置顶会在 真全屏时隐藏 (eg:游戏全屏, 全屏独占输出), 其他时候显示
可以桌宠设置中打开桌宠小标快速切换, 左键小标鼠标穿透,右键小标置顶
