### ISSUE TITLE
Missing translation strings?

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#407]
Hey there!

I have found a problem when translating this items. I could not find the original text (language strings).

This is in game options -> system -> game operation
数据修复
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/799528bf-d111-4212-bebd-5a2b11d1bf6e)

Window when clicked on the button. Here a window title is missing also.
当前游戏时间已经大于Steam服务器记录时间,无需修复
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/bb517289-0144-4993-a62d-bdaa90df728f)

Window when clicked on the button (other response):
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/13e24995-a4f9-46a7-924c-11b88edb1424)

Also missing translateable text:
校准玩家游玩时间数据 为失去超模计算(Hash检查)小标玩家重新获得小标

**Comment by LorisYounger** [comment]
Yes, these are new features that I forgot to translate. I will add them in the next update
