### ISSUE TITLE
哥們 版本控制好像出點問題

### ISSUE THREAD

**Issue by DragonTaki** [LorisYounger/VPet#410]
本來我這邊固定要按update更新到最新版本（它會說落後幾個版），然後我翻譯，再pull request給你（你接受之後才會寄信過來通知更新了）

但是現在更新的按鈕沒了，變成#1（原本#1的位置是更新）
![image](https://github.com/user-attachments/assets/9af80fc5-a77f-40c6-9b38-37e834b10315)
然後每次更新都會寄信過來我這

我要怎麼弄（還是你那邊要按什麼）

**Comment by LorisYounger** [comment]
你可以試試看把你的翻譯先拷貝出來, 然後刪掉項目重新拉取, 然後貼上覆蓋你的翻譯
確保工作內容不遺失就行

**Comment by LorisYounger** [comment]
如果你不确定, 也可以让我去你的branch拉PR看看, 我也不是很清楚这个
