### ISSUE TITLE
GameSave_VPet内imw成员未初始化

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#414]
![C73F1A94865689B655794359B8DABBA8](https://github.com/user-attachments/assets/5897e0f9-1f05-4355-8e44-bd0d112651d5)

这个构造方法没有被调用过，imw也没有被赋值过，新建的GameSave_VPet对象imw成员为空，导致调用升级动画报错

**Comment by CCCCCCHARA** [comment]
说真的，以后可不可以先测试一下再推送到steam

**Comment by LorisYounger** [comment]
> 说真的，以后可不可以先测试一下再推送到steam

半夜加班是这样的, 我写的时候特意写了个方法,以为会有报错,等报错再修
结果忘记了
