### ISSUE TITLE
建议去除游戏版本较高标红，游戏版本较低标红，和mod设置左侧列表mod名字标红

### ISSUE THREAD

**Issue by YIYuNCU** [LorisYounger/VPet#419]
如题

**Comment by CCCCCCHARA** [comment]
建议注明版本低和能否正常使用的关系

**Comment by LorisYounger** [comment]
> 建议注明版本低和能否正常使用的关系

+1 要不你们帮忙想个描述, 关于版本低, 游戏版本解释啥的, 一句话 我加到描述里

**Comment by CCCCCCHARA** [comment]
> > 建议注明版本低和能否正常使用的关系
> 
> +1 要不你们帮忙想个描述, 关于版本低, 游戏版本解释啥的, 一句话 我加到描述里

我不了解官方标明非代码MOD版本低的意图是什么

**Comment by CCCCCCHARA** [comment]
> 版本更新肯定有不兼容的地方, 所有游戏包括 RimWorld, 群星等等都是用这套MOD机制 最简单的举个例子, 1.10版本修了个图片只会读取根目录的bug, 所以老MOD如果图片存的不规范, 图片都会变成三明治

我更建议如果该MOD是旧版本的，在MOD管理页面空余页面增加对版本低的描述
至少我不会用一句话把这些事情解释清楚

**Comment by YIYuNCU** [comment]
> > 建议注明版本低和能否正常使用的关系
> 
> +1 要不你们帮忙想个描述, 关于版本低, 游戏版本解释啥的, 一句话 我加到描述里

除了代码类mod都不标红，只有代码类mod标红，然后如果图片显示异常的话，使用者会去找mod作者的
