### ISSUE TITLE
mod hover info icon behaviour [bug]

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#423]
Hey there!
In settings -> Mod was an info icon with hover information implemented.
The icon behaviour is kind of strange. Initially the icon is not visible.
When selecting a mod for an older game version the icon gets visible and functional.
But when selecting a mod for the current game version (again) it does not vanish.

I think the icon visibility check should be everytime a mod is selected.

You can see it in the screenshots. I have selected an outdated mod, then the core mod again:
**In this test case the current game version was **11025**

![grafik](https://github.com/user-attachments/assets/468b1084-8abd-4773-82e7-23e77558ad39)
![grafik](https://github.com/user-attachments/assets/e12bfdeb-60c5-4ec3-ace0-c1c5d3f391fb)
![grafik](https://github.com/user-attachments/assets/27449cb5-d120-4d3a-97f1-cfd3ec80826b)

**Comment by LorisYounger** [comment]
fix in 1bca3a5ba025eabe9cb407867faa12f7145d3778
I haven't pushed it to the official version yet, because I plan to wait for the CG system together
