### ISSUE TITLE
Module Core plug-in damage

### ISSUE THREAD

**Issue by fhctyw** [LorisYounger/VPet#425]
Hi!
I’m trying to open VPet, but I keep getting an error saying that `String '04/30' was not recognized as a valid DateOnly`.

![image](https://github.com/user-attachments/assets/f5211a24-0623-4bf4-9ef4-32299cdd99ba)

I'm runnung VPet on Windows 11 10.0.22631, locale: uk-UA. 
Game version: 1.10.30
Mod version: 1.10.00
It seems like the issue might be related to how the game handles dates or fillter DateOnly.. idk) I couldn't click on Workshop Page link so I'm writing here.

**Comment by LorisYounger** [comment]
fix in b326d8e06cbfce0c2f9c42b348e8ff1d58f9878a
