### ISSUE TITLE
Photo gallery details text is too long [Bug]

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#426]
Hey there!
There is one picture with a very long text. If the text reaches a certain lenght, the picture is not displayed anymore.
Also the buttons are not visible anymore.

See here:
![grafik](https://github.com/user-attachments/assets/50613e20-1f10-4361-b79b-4b6f00424415)
![grafik](https://github.com/user-attachments/assets/ec87f793-86e6-487d-a263-9cea05d013e0)

**Comment by Mochengvia** [comment]
bug has been fixed in https://github.com/LorisYounger/VPet/pull/434
