### ISSUE TITLE
photo gallery opening gif pictures can take a long time

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#428]
Hello there!
If a GIF picture is a bit lager, it takes very long to open the picture details.
In this example the small GIF is opened fast but the large one takes several seconds.

![VPet-Simulator Windows_gFoC9QSK1C](https://github.com/user-attachments/assets/4d29534b-b5b9-4ab7-81ad-7010aebc1a73)

**Comment by LorisYounger** [comment]
Subsequently, loading sequences and waiting animations will be added here
