### ISSUE TITLE
photo gallery not unlocking for past achvements

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#429]
Helllo there!
I have noticed, that i am missing unlocked elements inside the gallery.
You can see my VPET ist Level 104 but i have not got the Level 1 unlock.

I have tried to repair the savegame and restarted my game but it does not help.

![grafik](https://github.com/user-attachments/assets/3f886740-a506-45fb-ab92-be5c1064f99a)

**Comment by LorisYounger** [comment]
TranslateError, is mean Level Brake: 1

**Comment by LorisYounger** [comment]
After checking, there is no translation issue here. Please check if there have made any modifications in mod translation file
```
等级突破要求: {0}#Level Breakthrough: {0}:|
```
