### ISSUE TITLE
[Bug] 无法打开`操作教程`

### ISSUE THREAD

**Issue by kitUIN** [LorisYounger/VPet#43]
右键->系统->操作教程
然后就直接弹出来我的VScode
VScode是我html文件的默认打开方式
![image](https://github.com/LorisYounger/VPet/assets/68675068/5b01f33a-d992-46d1-b0f7-55400eb9ec34)

**Comment by LorisYounger** [comment]
你也可以来这里看 https://github.com/LorisYounger/VPet/blob/main/Tutorial.md
