### ISSUE TITLE
Missing translation in photo gallery

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#430]
Hello there!

I have noticed a missing english translation for the new photo gallery.
Also can you clearify what does that things mean:
好感度要求
CG
OOZ
LinH

![grafik](https://github.com/user-attachments/assets/365782f3-500d-4be5-a058-c642e2bf83d2)

**Comment by LorisYounger** [comment]
OOZ/LinH is Painter's name
好感度需求 is Likability requirement
CG is CG Computer Graph

**Comment by LorisYounger** [comment]
After checking, there is no translation issue here. Please check if there have made any modifications in mod translation file
```
等级突破要求: {0}#Level Breakthrough: {0}:|
```
