### ISSUE TITLE
[建议]增加图库图片解锁要求

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#435]
有的图片需要等级突破解锁，按当前版本(1.10.31)计算，从1级升级到等级突破2(1000+1100)级预计需要约900小时(以学习效率25min/级计算，5s/tick)。
![QQ20240920-201711](https://github.com/user-attachments/assets/816309a5-6ddf-4cfc-90f4-ba9720f9cad8)
（先不论这个奇怪的显示方式）

实际情况会更长，这使得大部分玩家很难得到对应的图片（大部分玩家不会一直学习，当前游戏系统也不支持玩家只采取学习互动）

建议增加“游戏时长”要求，使得时长条件能够与等级条件互为替代

**Comment by LorisYounger** [comment]
有其他 “游戏时长” 解锁的内容. 有部分图片难解锁是正常的, 总会有几个的

**Comment by CCCCCCHARA** [comment]
既然等级的升级一定和时长挂钩，我认为添加游戏时长的解锁方式是对于游戏时长很久但没有一直升级的老玩家的补偿

**Comment by LorisYounger** [comment]
老玩家有其他补偿, 例如CHATVPET点数

**Comment by CCCCCCHARA** [comment]
有什么用？
