### ISSUE TITLE
[bug]图片解锁文本问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#436]
![QQ20240920-201711](https://github.com/user-attachments/assets/8475962e-51a0-42d4-bd0e-37506cc8a6d7)
如图

**Comment by LorisYounger** [comment]
多个等级要求已在之前更新修复
1100级是这是给未突破的玩家写的兼容性描述

**Comment by CCCCCCHARA** [comment]
![QQ20241009-162741](https://github.com/user-attachments/assets/110acb48-e8a5-4b72-9433-1ea7afa8d207)
并未修复，这些图片不仅需要“等级”，还需要“等级上限”
如“趴着”这个图片的要求是：photo:|zip#Thumbnail:|path#13.png:|type#Thumbnail:|name#趴着:|tags#小图,叶书文,姿势:|desc#我会一直明着地视奸你.永远永远。:|lsellprice#300000:|llevel#300:|llevelmax#3:|
实际等级是1000+1100+1200+300

**Comment by CCCCCCHARA** [comment]
那请问一下3突破300级等于1200级吗

**Comment by LorisYounger** [comment]
不等于, 这里显示的等级要求只是为了方便玩家理解而已. 等你突破后显示的就是正常的突破需求和等级需求了

**Comment by CCCCCCHARA** [comment]
令人费解，为什么要增加一个完全不正确的描述

**Comment by LorisYounger** [comment]
为了方便玩家理解 突破 的含义

**Comment by CCCCCCHARA** [comment]
并不能，因为玩家在看到“1200”级的时候，只会理解为升级到1200级，没有任何描述有涉及到“突破”
