### ISSUE TITLE
[Bug]点击对话触发不了

### ISSUE THREAD

**Issue by ColorfulChen** [LorisYounger/VPet#437]
点击loris本体大多数时候都只会触发摸头动画，而不是点击对话。

**Comment by LorisYounger** [comment]
要看点击位置
具体可以参考这个教程
https://github.com/LorisYounger/VPet/blob/main/Tutorial.md

**Comment by ColorfulChen** [comment]
我按照教程的位置点击触发的是摸身子的动画，而不是点击对话啊
![20241008130936_Snake](https://github.com/user-attachments/assets/91d3ef43-7c84-4bed-83c1-677e42575e3a)

**Comment by ColorfulChen** [comment]
我关闭了所有模组，重装了也是这样。
我之前制作了一个点击对话的模组，也有很多人跟我反馈说现在用不了了，我自己试了一下发现原本的点击对话也触发不了，不知道怎么回事。

**Comment by LorisYounger** [comment]
因为这个就是点身体, 你点击范围在身体部分, 这个是后面更新增加的功能. 你可以点旁边点, 就是说话了

**Comment by ColorfulChen** [comment]
服了，Tutorial点的明明就是这个位置。
https://github.com/LorisYounger/VPet/blob/main/Tutorial.md

但是我试着点了裙子旁边的空白，也不是总是能触发点击对话的，可能点20次才能触发一次。

**Comment by LorisYounger** [comment]
因为点击说话有20秒CD, 总不能老是说
Tut有计划在更新为 wiki

**Comment by ColorfulChen** [comment]
了解了
