### ISSUE TITLE
[BUG] When invited via steam to an other game, VPET reacts

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#447]
Hey there!
When VPET is running and i get an invite to another game, VPET reacts to the invite but of course it does not work.

solution:
VPET should only react to invites, coming from VPET lobbys

**Comment by LorisYounger** [comment]
![image](https://github.com/user-attachments/assets/728df8b3-55e5-476c-9710-e9fd31c0cba9)
Your friend {0} invites you to play games, go and respond to he/she!

fix this error and Support invitation game reminder
