### ISSUE TITLE
Missing english translations

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#448]
Hey there!

I have found missing translations.

(is missing entirely: 次购买)

![grafik](https://github.com/user-attachments/assets/09324afe-2d87-4fc5-b2fe-8f3328d0a44d)

![grafik](https://github.com/user-attachments/assets/11c87ed0-e8f6-4caa-80af-569e3b5b9607)

![grafik](https://github.com/user-attachments/assets/655ac91d-e7cb-4a45-9c9d-7f44405fa273)

![grafik](https://github.com/user-attachments/assets/e3f1f8c5-2934-4782-a8d6-202fccff3372)

![grafik](https://github.com/user-attachments/assets/7f51f6ae-4653-4b4b-92f9-ab97328f3d36)

![grafik](https://github.com/user-attachments/assets/2ecf3da4-2f48-4d14-bf4b-ff156c6e50f6)

![grafik](https://github.com/user-attachments/assets/f1a532a2-6ce3-4620-94c8-6b87f88f2fb9)

**Comment by LorisYounger** [comment]
It's possible that I accidentally put the translations in other mod files and I didn't realize they were missing.
I'll fix this before the Christmas update.
