### ISSUE TITLE
关于加载动画的问题

### ISSUE THREAD

**Issue by CCCCCCHARA** [LorisYounger/VPet#452]
https://github.com/LorisYounger/VPet/commit/831d3767e80f8a924cbc757985a77d7ed59a1fd8
改过的图产生了如图所示的问题
![image](https://github.com/user-attachments/assets/da8beaf5-8a29-40a5-91d2-ec5ab571acf9)
![image](https://github.com/user-attachments/assets/7000341a-e032-4846-8397-3d14e23e50e2)

另外是能否减少加载动画生成占用内存，如果内存占用过高会无法加载部分动画，需要反复重启加载才能加载完全
![image](https://github.com/user-attachments/assets/8ad2bdd6-49c9-4fe4-b635-32c5fc94b9ab)

**Comment by LorisYounger** [comment]
反馈中心里面的内容能否给我看看?

**Comment by CCCCCCHARA** [comment]
![image](https://github.com/user-attachments/assets/b2f331c8-9402-4117-8e01-1f733ef8f432)

--PNGAnimation--[levelup]Common_HS]--
Path: E:\git_clone\VPet-1.10\VPet\VPet\VPet-Simulator.Windows\bin\x64\Debug\net8.0-windows\mod\0000_core\pet\vup\LevelUP\Happy
Unable to allocate pixels for the bitmap.
------
--PNGAnimation--[levelup]Common_NS]--
Path: E:\git_clone\VPet-1.10\VPet\VPet\VPet-Simulator.Windows\bin\x64\Debug\net8.0-windows\mod\0000_core\pet\vup\LevelUP\Nomal
Unable to allocate pixels for the bitmap.

**Comment by CCCCCCHARA** [comment]
不能加载的动画是随机的

**Comment by LorisYounger** [comment]
是内存不足导致的吗? 我试试看能不能通过检测内存占用来限制. 我目前没遇到过这种问题, 的确不清楚

**Comment by CCCCCCHARA** [comment]
是内存不足，启动桌宠时已经是内存几乎满的状态了

**Comment by LorisYounger** [comment]
话说你内存是多大的?

**Comment by CCCCCCHARA** [comment]
16G，但我开东西多

**Comment by LorisYounger** [comment]
我更新了下, 加载限制现在改成 2G(x86) 和 4G(x64). 虽然说理论上占用会比这个高, 不过应该不会占满了

**Comment by CCCCCCHARA** [comment]
我在内存占用80%的时候启动桌宠
![image](https://github.com/user-attachments/assets/06dfc3c8-56f1-445c-aa5b-f8a6bd3b0ce5)

**Comment by LorisYounger** [comment]
那就改成反方向? 剩余内存不足500mb的时候停止加载?

**Comment by CCCCCCHARA** [comment]
剩余内存50%如何

**Comment by LorisYounger** [comment]
我感觉16G占用80%还是太极端了,
我最后改成 占用限制为剩余内存的一半,, 不足512按512MB计算

**Comment by CCCCCCHARA** [comment]
占那么大内存本质上空间换时间，我觉得比起加载多快，让加载尽量少影响正常使用更好
而且在大众认知上，一个桌宠不会占用好几个G的内存

**Comment by LorisYounger** [comment]
也就第一次启动的时候会用这些内存, 又不是持续性的

**Comment by CCCCCCHARA** [comment]
只要遇到一次就够恼人了，一般玩家不一定知道怎么解决

**Comment by LorisYounger** [comment]
用剩余内存的一半加载不会影响到使用的.
之前我用全部内存加载, 在我性能差的服务器上测试过, 都是没问题的. 缺内存小概率事件

**Comment by CCCCCCHARA** [comment]
这是我的观点

> 剩余内存50%如何
