### ISSUE TITLE
请问在安装完 Edge-TTS如何使用

### ISSUE THREAD

**Issue by Polaristime2026** [LorisYounger/VPet#46]
我看到最新的更新里面说更新了语音功能所以从steam中下载了 Edge-TTS，可惜本人比较愚钝不会用。在线求大佬解答

**Comment by surftillend** [comment]
系统→设置面板→mod管理里面，选中edgetts，右下角操作里面“启用该模组”，然后在系统→mod设置→edgetts，第一个开关“启用edgetts”，打开应该就可以用了

**Comment by LorisYounger** [comment]
> 系统→设置面板→mod管理里面，选中edgetts，右下角操作里面“启用该模组”，然后在系统→mod设置→edgetts，第一个开关“启用edgetts”，打开应该就可以用了
