### ISSUE TITLE
ChatGPT API支持自定义模型，以及流式响应

### ISSUE THREAD

**Issue by HarukaB** [LorisYounger/VPet#47]
目前的chatgpt集成是API完全返回结果后才有响应，给用户一种卡顿的感觉，希望能够添加流式接受响应的模式，在[此处](https://platform.openai.com/docs/api-reference/chat/create)
有说明，另外对于富哥用户，GPT4也用的起的那种，不如就给个模型选项（逃

**Comment by LorisYounger** [comment]
接受响应很难整, 而且配合edgetts之类的mod时候说话会断断续续, 还是算了
