### ISSUE TITLE
列表项目过多或文本过长时无法全部显示

### ISSUE THREAD

**Issue by SAFEluren** [LorisYounger/VPet#48]
如题，列表项目过多或文本过长时无法全部显示
![image](https://github.com/LorisYounger/VPet/assets/79032826/d57ecab1-e179-46be-9d2c-094788760f38)

**Comment by LorisYounger** [comment]
你们mod是真能整活

**Comment by LorisYounger** [comment]
修好了 https://github.com/LorisYounger/VPet/commit/cbe8ddf8913862011fb970e41e5e67716221a00a
