### ISSUE TITLE
使用第三方api供给出现错误信息

### ISSUE THREAD

**Issue by 100pangci** [LorisYounger/VPet#49]
![image](https://github.com/LorisYounger/VPet/assets/63954871/fbba3c89-69a9-42d5-be0c-6d4e92bd0cb3)
![image](https://github.com/LorisYounger/VPet/assets/63954871/4eb91285-2b00-40d7-a79b-1d14dfef5d32)

**Comment by HarukaB** [comment]
你填入的URL不完整，我看了文档，应该是https://api.aikey.one/v1/chat/completions

**Comment by LorisYounger** [comment]
> 你填入的URL不完整，我看了文档，应该是https://api.aikey.one/v1/chat/completions

**Comment by 001-person** [comment]
> https://api.aikey.one/v1/chat/completions
有人成功吗？我试了完整的url也不行

**Comment by 100pangci** [comment]
> > https://api.aikey.one/v1/chat/completions
> > 有人成功吗？我试了完整的url也不行

这个试了一下，成功了，得在开发文档里找
