### ISSUE TITLE
运行报错，有几个库找不到

### ISSUE THREAD

**Issue by dashenxian** [LorisYounger/VPet#5]
![image](https://user-images.githubusercontent.com/18696614/235043828-ea120ef8-f9be-4e95-a1d8-2b424a369032.png)
有几个库找不到

**Comment by lierlin** [comment]
同问

**Comment by vince0823** [comment]
同问

**Comment by dashenxian** [comment]
迁移到项目引用可以找到了，或者删了重新引用一下

**Comment by LorisYounger** [comment]
在 nuget 控制台中 输入 `Update-Package -reinstall` 重新装下 
![image](https://user-images.githubusercontent.com/34806646/235066014-c8985772-5a9a-488b-b04d-aead7405aaf9.png)
![image](https://user-images.githubusercontent.com/34806646/235066574-89e68dd4-1b0e-4231-b612-98cd74640c5a.png)
注意,旧版本VS的nuget管理可能有所不同,虚拟桌宠模拟器在VS2022上开发的

**Comment by SingerStone95** [comment]
> 在 nuget 控制台中 输入 `Update-Package -reinstall` 重新装下 ![image](https://user-images.githubusercontent.com/34806646/235066014-c8985772-5a9a-488b-b04d-aead7405aaf9.png) ![image](https://user-images.githubusercontent.com/34806646/235066574-89e68dd4-1b0e-4231-b612-98cd74640c5a.png) 注意,旧版本VS的nuget管理可能有所不同,虚拟桌宠模拟器在VS2022上开发的

VS 2019 上 Update-Package -reinstall 后还是不得行 
![image](https://user-images.githubusercontent.com/28226184/235100577-264d6598-928b-450d-bc22-778a8c87a850.png)

**Comment by LorisYounger** [comment]
> > 在 nuget 控制台中 输入 `Update-Package -reinstall` 重新装下 注意,旧版本VS的nuget管理可能有所不同,虚拟桌宠模拟器在VS2022上开发的
> 
> VS 2019 上 Update-Package -reinstall 后还是不得行 

我知道了,你是不是动nuget模式了, 在nuget管理页面弹出了个更新什么新nuget架构,你点了那个
那个不能点,因为桌宠32位和64位引用的是不同的nuget包
解决方法: 从github重下`VPet-Simulator.Windows.csproj`然后覆盖下即可

**Comment by TDRookie** [comment]
我这有一个解决方案，不知道可不可以帮助你们启动，如下图操作即可
![image](https://user-images.githubusercontent.com/104550505/236140865-819a2f26-a8ef-45a6-ad7d-1dc7b82edc24.png)
![Uploading image.png…]()
先切换成x86，在引用的库里看不到黄色标记后，再切回x64就可以正常运行了
