### ISSUE TITLE
Some suggest

### ISSUE THREAD

**Issue by Ljtyxhc** [LorisYounger/VPet#53]

**Comment by Ljtyxhc** [comment]
1. 建议可以支持一个内置的聊天内容
如在学习的时候点击会根据用户提供的文档（比如单词本，公式记录，显示）

**Comment by Ljtyxhc** [comment]
2.建议提供透明度较低的自定义背景（静态即可/减少资源占用）
增加画布后读取一个本地文件夹，用其中图片来制定一个背景，透明度可调

**Comment by Ljtyxhc** [comment]
3.丰富互动内容

可以参考mod，因为目前的几个互动还是太单调了

**Comment by LorisYounger** [comment]
1. 之后会整个点击的聊天
2. 感觉没啥用, 代码插件可以实现这样的功能,可以等创意工坊
3. 这些东西创意工坊整就行,桌宠会有几个大方向的互动,例如学习/娱乐/工作
