### ISSUE TITLE
多屏情况下使用`更好卖`投食后会放大倍率异常

### ISSUE THREAD

**Issue by yymydyy** [LorisYounger/VPet#55]
主屏2560x1600 16:10 放大倍率125%
副屏1920x1080 16:9 放大倍率150%

主屏拖拽到副屏无问题，但在副屏打开更好卖，购买东西投喂时会显著放大桌宠，且下方菜单的子菜单与菜单错位。
<img width="231" alt="image" src="https://github.com/LorisYounger/VPet/assets/59475922/e4fa9e98-2bda-4882-b959-0bb62a631cc3">

**Comment by yymydyy** [comment]
另补充，更好卖页面在主屏放置，桌宠界面在副屏放置。

**Comment by LorisYounger** [comment]
这个修不了，是微软的问题，缩放比例不一样造成的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yymydyy ***@***.***&gt;
发送时间: 2023年8月18日 02:50
收件人: LorisYounger/VPet ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LorisYounger/VPet] 多屏情况下使用`更好卖`投食后会放大倍率异常 (Issue #55)





 
主屏2560x1600 16:10 放大倍率125%
 副屏1920x1080 16:9 放大倍率150%
 
主屏拖拽到副屏无问题，但在副屏打开更好卖，购买东西投喂时会显著放大桌宠，且下方菜单的子菜单与菜单错位。

**Comment by yymydyy** [comment]
> 这个修不了，是微软的问题，缩放比例不一样造成的
> 
> 
> 
> 发自我的iPhone
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: yymydyy ***@***.***&gt;
> 发送时间: 2023年8月18日 02:50
> 收件人: LorisYounger/VPet ***@***.***&gt;
> 抄送: Subscribed ***@***.***&gt;
> 主题: Re: [LorisYounger/VPet] 多屏情况下使用`更好卖`投食后会放大倍率异常 (Issue #55)
> 
> 
> 
> 
> 
>  
> 主屏2560x1600 16:10 放大倍率125%
>  副屏1920x1080 16:9 放大倍率150%
>  
> 主屏拖拽到副屏无问题，但在副屏打开更好卖，购买东西投喂时会显著放大桌宠，且下方菜单的子菜单与菜单错位。
>  
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我觉得你可以看一下我刚发的评论。

如果是屏幕间分辨率的问题，那应该在主屏移动到副屏后立即发生，而不是点击喂食后发生。

**Comment by LorisYounger** [comment]
没有立即发生是因为windows没聚焦的时候没检查缩放倍率, 你不用更好买,你用设置,也会造成同样的效果, 这个不是我代码方面能简单解决的
