### ISSUE TITLE
Steam更新后会导致位置与更新前退出的位置不一样

### ISSUE THREAD

**Issue by Despair21** [LorisYounger/VPet#56]
在steam更新后启动位置与更新前退出的位置不一样
![JQW2)%$Q_V{}4)INU`}Z~C0](https://github.com/LorisYounger/VPet/assets/70837010/8a56577c-4aa1-4639-b517-68730dee6652)

**Comment by LorisYounger** [comment]
有一点点位移是正常现象,是误差或者屏幕改变有关系,具体我也没法校准,大致位置是对的就行

**Comment by Despair21** [comment]
> 有一点点位移是正常现象,是误差或者屏幕改变有关系,具体我也没法校准,大致位置是对的就行

那应该不是一点点位移了，初始位置是在左上角的，但我习惯放在右上角的位置
我等更新的时候再看一下是不是被初始化了

**Comment by Despair21** [comment]
更新后位置被初始化了

**Comment by LorisYounger** [comment]
是桌宠更新吗,我看看,我记得位置是储存在设置里的

**Comment by Despair21** [comment]
> 是桌宠更新吗,我看看,我记得位置是储存在设置里的

是的，还有时更新后设置会被改动

**Comment by Despair21** [comment]
对了，我想问一下设置面板的数据能用配置文件存储吗

**Comment by Despair21** [comment]
@LorisYounger 那个你看一下 **启动位置** 和 **开机启动** 的按钮，比如我启动位置和开机启动的按钮都是关闭状态下，打开VPet看设置会发现其中有一个是开的另一个是关的，重新再打开VPet是反过来的

**Comment by LorisYounger** [comment]
> 对了，我想问一下设置面板的数据能用配置文件存储吗

没听懂,设置的数据全是Setting.lps储存的

**Comment by LorisYounger** [comment]
这个bug修好了, 因为忘记保存退出位置了

**Comment by Despair21** [comment]
> 这个bug修好了, 因为忘记保存退出位置了

这两个按钮还是没修好，关闭VPet前两个都是关闭的，再打开VPet后有其中一个是打开的
![F)AX% N{1RGT$MP5ASZUSD6](https://github.com/LorisYounger/VPet/assets/70837010/a3b7809d-1b25-4ada-8b6d-1123487a659e)
