### ISSUE TITLE
想请问一下你们的开机自启是怎么实现的，卸载了你游，都还会开机启动steam帮我下载

### ISSUE THREAD

**Issue by lantz39** [LorisYounger/VPet#57]
昨天整理steam时候把游戏删了，结果今天开电脑的时候，电脑自动启动steam，然后如图就打算帮我下你游了（第一次发issue，如果不合规见谅）
![QQ截图20230818110236](https://github.com/LorisYounger/VPet/assets/142526365/e1cd51c6-2b23-420c-b8d2-c9c3c7417535)
现在打算重新下载进游戏关了启动项再试试

额，看到了你们在设置备注的卸载要关闭自启，但卸载的时候一般真不会想着这个

**Comment by LorisYounger** [comment]
重新下载进游戏关了启动项就行
方法是创建快捷方式，不是注册表，更健康，所以游戏卸了也不知道
