### ISSUE TITLE
建议不要在alt+tab菜单中显示

### ISSUE THREAD

**Issue by strange-qwq** [LorisYounger/VPet#60]

**Comment by LorisYounger** [comment]
简单研究了下,比较麻烦, https://stackoverflow.com/questions/357076/best-way-to-hide-a-window-from-the-alt-tab-program-switcher/551847#551847
而且由于目前桌宠已经加了鼠标穿透,和这个设置项目是一样的,加这个容易出错,保险起见就不做了, 代码插件支持修改这项内容,可以等创意工坊
