### ISSUE TITLE
[建议]在设置中的拉条右侧增加文本框用于设置具体数值

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [LorisYounger/VPet#61]
设置中的拉条有时候在想设置一个整数(例如100)时相当的折磨

**Comment by LorisYounger** [comment]
加文本框工作量老大了,你说说看是啥想设置整数,我看看改个间隔
另外设置框可以拉大,改起来更精细

**Comment by 0O0o0oOoO00** [comment]
![image](https://github.com/LorisYounger/VPet/assets/11174151/cf38394b-e55e-45ae-919d-8382aafa8617)
比如这些，我的设想是可以点击拉条后面的数字就能变成一个类似文本框的东西直接输入具体的值

**Comment by lWaterLite** [comment]
我浅显地研究了一下，如果要改成文本框接收用户输入的话主要要做的就是修正用户的输入内容，对于数值而言因为和slider绑定在一起了所以不在数值范围内的会自动修正到最大最小值，但是接收整数的地方不会自动修正小数(互动周期)，另外就是不合法的文字输入无法修正，需要写代码。再一个就是输入之后的逻辑，需要调用slider的valueChanged，还有一些用户友好体验比如enter确认输入。我自己浅显地写过一些wpf，不知道大佬对于代码有无比较严格的要求，我愿意在这个建议上尝试一下进行修改。

**Comment by lWaterLite** [comment]
> 加文本框工作量老大了,你说说看是啥想设置整数,我看看改个间隔 另外设置框可以拉大,改起来更精细

我浅显地研究了一下，如果要改成文本框接收用户输入的话主要要做的就是修正用户的输入内容，对于数值而言因为和slider绑定在一起了所以不在数值范围内的会自动修正到最大最小值，但是接收整数的地方不会自动修正小数(互动周期)，另外就是不合法的文字输入无法修正，需要写代码。再一个就是输入之后的逻辑，需要调用slider的valueChanged，还有一些用户友好体验比如enter确认输入。我自己浅显地写过一些wpf，不知道大佬对于代码有无比较严格的要求，我愿意在这个建议上尝试一下进行修改。 @LorisYounger

**Comment by LorisYounger** [comment]
我的设想是点击文字的时候再变成文本框
不过我觉得加文本框还是很麻烦, 我给你加个tick吧, 至少保证是整数,晚点加了推上来
