### ISSUE TITLE
When using a dual monitor setup, she can disappear! (Kind of)

### ISSUE THREAD

**Issue by ploonyplane** [LorisYounger/VPet#65]
I have 2 monitors, one that is a 21:9 Aspect Ratio ULTRAWIDE monitor, and the other is a 16:9 standard Aspect Ratio. The ULTRAWIDE monitor (21:9) is the bottom one. On top is the standard monitor. She seems to walk off my 16:9 standard monitor as if it were an ULTRAWIDE as well.

**Comment by LorisYounger** [comment]
This is indeed possible, as this type of problem is difficult to trigger and fix.
I have tried to fix this issue before, but it has not been successful (it work, but still)
You can right-click and select Reset in the taskbar to reset the current position of the desk pet and center it
![image](https://github.com/LorisYounger/VPet/assets/34806646/262c1e8c-9781-48d7-818d-328adfa82f07)

**Comment by ploonyplane** [comment]
Thank you, this is a great temporary fix for the problem!! <3 Your work is amazing.
