### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by DerFuzeler** [LorisYounger/VPet#66]
It's not really a Issue but i wanted to translate the game to German. Found the files but how do i pack them to a Mod an upload it to the Workshop?

**Comment by lWaterLite** [comment]
In the workshop there is already a sample mod of japanese trans. You can do your trans in the lps then move the mod folder into game folder (\steamapps\common\VPet\mod\). Then edit the info.lps and icon.png for your own mod, mind you that the authorid and itemid in info.lps must be empty. After doing these you may open the game setting window,finding your own mod in the mod manage page. There will be a button can simply let you simply publish your mod on the workshop

**Comment by DerFuzeler** [comment]
Thanks for the fast answer! But as soon as i delete the itemid the app crashes at loading my Mod.

**Comment by Pvictox** [comment]
I believe that this itemid refers the id of the mod in the workshop.

**Comment by DerFuzeler** [comment]
Thanks for the fast answer! It worked.

**Comment by Pvictox** [comment]
By the way @DerFuzeler, have you got the template for the icon.png? It looks like the translate mods follow all the same figure.

**Comment by DerFuzeler** [comment]
You mean this one? 
![icon](https://github.com/LorisYounger/VPet/assets/91015130/42a45a19-9613-4443-89b5-2aab50c531e7)

**Comment by Pvictox** [comment]
Thank you!

**Comment by DerFuzeler** [comment]
> Thank you!

NP! Are you familiar with gimp/photoshop?

**Comment by Pvictox** [comment]
No. Sorry. You asked because you're planning on doing something with that cover?

**Comment by DerFuzeler** [comment]
I would have asked nicely if you could made me a cheap made cover image for the workshop since i have zero knowledge with picture editing. But thanks anyway!

**Comment by Pvictox** [comment]
@DerFuzeler, I actually used Canva to edit the cover for the PT-BR translation. It was pretty simple to use. I

**Comment by LorisYounger** [comment]
I see that yours communication is ended, and I close the issue for yours
The Mod Maker supports multilingual functionality, but is currently under development.
