### ISSUE TITLE
【建议】关于创意工坊

### ISSUE THREAD

**Issue by CERN391** [LorisYounger/VPet#67]
能不能不让steam启动然后模拟器也能显示mod 每次加载mod都需要打开steam 这很麻烦 希望作者能够改进一下

**Comment by LingShi991123** [comment]
可以试试把mod从 [.Steam\steamapps\workshop\content\1920960\] 复制到 [.\Steam\steamapps\common\VPet\mod\] 里

**Comment by LorisYounger** [comment]
已添加缓存功能,之后更新推上去
