### ISSUE TITLE
重新安装依赖后出现这样

### ISSUE THREAD

**Issue by NOeSIS-yu** [LorisYounger/VPet#7]
[](![image](https://user-images.githubusercontent.com/116642879/236585535-b232ff4d-250b-4d59-ba41-96d41d7b48a1.png)

**Comment by NOeSIS-yu** [comment]
[](![image](https://user-images.githubusercontent.com/116642879/236585677-e7bb1355-d938-4d7c-a8dd-348086a539a9.png))

**Comment by LorisYounger** [comment]
你是不是动nuget模式了, 在nuget管理页面弹出了个更新什么新nuget架构,你点了那个
那个不能点,因为桌宠32位和64位引用的是不同的nuget包
解决方法: 从github重下`VPet-Simulator.Windows.csproj`然后覆盖下即可

**Comment by NOeSIS-yu** [comment]
没有啊，我重新试试看吧
