### ISSUE TITLE
关闭桌宠时的bug

### ISSUE THREAD

**Issue by LingShi991123** [LorisYounger/VPet#71]
关闭桌宠时如果桌宠刚好说话了，关闭会失败
不过复现有些难

复现成功了

用控制台复现：
https://github.com/LorisYounger/VPet/assets/96658974/4059720f-4f48-498e-a397-dfa276d8cd04

非控制台复现（分卷压缩）：
[非控制台复现.zip](https://github.com/LorisYounger/VPet/files/12385719/default.zip)
[非控制台复现.z01.zip](https://github.com/LorisYounger/VPet/files/12385720/z01.zip)
[非控制台复现.z02.zip](https://github.com/LorisYounger/VPet/files/12385721/z02.zip)
（先解压z01和z02两个文件，再把他们放在一起，最后解压.zip）

**Comment by LorisYounger** [comment]
这个的确会有,不过不会修
关闭并不是立即执行的, 是先播放关闭动画再关闭
被打断了自然不会关闭.
就当做彩蛋,桌宠想和你多玩会(
