### ISSUE TITLE
【建議】更改抓取移動桌寵方式

### ISSUE THREAD

**Issue by scott306lr** [LorisYounger/VPet#72]
目前左鍵長按頭部抓取移動桌寵對我來說不太直覺，而且跟動畫也不太契合(動畫是抓衣服)。

我認為不限定頭部，長按滑鼠中鍵或滑鼠右鍵是抓取會更好。
可以的話，希望作者可以提供一個更改抓取方式的選項。

**Comment by LorisYounger** [comment]
桌寵框選的範圍是脖子周圍那一圈，按頭部自然也是可以的
之所以有限定，是因為總不能因為長按腿部也能提起來
