### ISSUE TITLE
如何开放  自定义聊天接口

### ISSUE THREAD

**Issue by KingDoum** [LorisYounger/VPet#73]
国外的gtp 有点贵，而且不好充值，我准备弄个国内的api接口，所以期待一下自定义聊天接口

**Comment by LorisYounger** [comment]
在做了ing, 见 #14

**Comment by KingDoum** [comment]
如果在做了 ，希望 在 自定义接口那里 写 （敬请期待 ）
你不写 在研发中，我都以为这个接口都已经能用了，只是我不知道开启的办法哈哈

**Comment by KingDoum** [comment]
@LorisYounger
