### ISSUE TITLE
【建议】可以给桌宠划定可移动范围，不然满屏幕爬有点乱，不爬还无聊！

### ISSUE THREAD

**Issue by GaoN0801** [LorisYounger/VPet#74]

**Comment by LorisYounger** [comment]
其实爬了也无聊,乱动并没有影响心情,心情是按互动间隔持续掉的

**Comment by GaoN0801** [comment]
我指的是我的心情！哈哈！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月20日 14:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LorisYounger/VPet] 【建议】可以给桌宠划定可移动范围，不然满屏幕爬有点乱，不爬还无聊！ (Issue #74) |

其实爬了也无聊,乱动并没有影响心情,心情是按互动间隔持续掉的
