### ISSUE TITLE
API调用失败:System.NullReferenceException:未将对象引用设置导对象的实例 System TalkBoxAPI.OP(String content)

### ISSUE THREAD

**Issue by Knonoa** [LorisYounger/VPet#79]
![image](https://github.com/LorisYounger/VPet/assets/59334058/56b48898-3677-41ac-9c0c-14ab0c42128c)
我是用ChatGLM中的openapi.py进行部署，并在桌宠中设置了请求链接，在服务端能看到请求的信息和返回的值，但是在桌宠这里没有得到正确的返回
![image](https://github.com/LorisYounger/VPet/assets/59334058/9993bc41-66d1-487b-8406-e506e73e5239)

**Comment by Knonoa** [comment]
![image](https://github.com/LorisYounger/VPet/assets/59334058/a421d8b2-fa38-4f89-afe4-c80994c23031)
在历史记录中也能看到这一轮对话，我看报错信息可能是对话的box没有实例化？

**Comment by LorisYounger** [comment]
因为这个只支持chatgpt的api,而且项目要一模一样

**Comment by LorisYounger** [comment]
我写的那个只支持一次性生成

**Comment by zkz098** [comment]
破案了，和流式传输没关系，chatglm2的webdemo缺了usage部分导致的花费token算不出来，把usage补上就一切正常了
整了一个本地测试可以运行的版本，放在google colab上了 @Knonoa 
https://colab.research.google.com/drive/1xDddH-r16RL-N1yql4sSRtr_C_b27o7H?usp=sharing

**Comment by Knonoa** [comment]
牛逼牛逼
