### ISSUE TITLE
按照步骤操作还是报错，why?

### ISSUE THREAD

**Issue by PeaceInDream** [LorisYounger/VPet#8]
![图片](https://user-images.githubusercontent.com/42854227/236741484-b678a090-13de-4133-9fd8-cde9509a8a53.png)

**Comment by LorisYounger** [comment]
使用 https://github.com/LorisYounger/VPet/issues/5#issuecomment-1527031002 方法即可解决这个问题
不过这个治标不治本,经过我研究发现,是nuget版本号不统一导致的,这个bug只有新项目才会触发
我已经将所有nuget更新到最新版本解决了这个问题,已修复并推送
