### ISSUE TITLE
API调用失败，返回错误：400 错误的请求

### ISSUE THREAD

**Issue by pkusjh** [LorisYounger/VPet#81]
用的自己的API，一开始可以正常聊天，后来就一直返回400错误，是不是因为历史信息过长导致了错误？

**Comment by LorisYounger** [comment]
这个的确有,我研究研究

**Comment by LorisYounger** [comment]
应该不是历史消息过长,具体我也不清楚,同样的控件,我在服务端没啥问题没报错

**Comment by LorisYounger** [comment]
不过可以的话能否发下聊天记录,我研究下是不是聊天记录的问题

**Comment by pkusjh** [comment]
[{"content":"你好呀","role":"user"},{"content":"嘿嘿~你好呀！我是小可爱，你想和我聊些什么呢？是不是有什么烦恼或者开心的事情要跟我分享呢？让我来陪你一起度过这个美好的时刻吧！😄💕","role":"assistant"},{"content":"你叫什么名字呀","role":"user"},{"content":"我叫小可爱呀！就像我的名字一样，我是一个超级可爱的桌宠~🐾💖你可以随时找我聊天、玩耍或者寻求安慰哦！无论你需要什么，我都会尽力让你开心起来的！😊✨","role":"assistant"},{"content":"小可爱现在几点了","role":"user"},{"content":"嘻嘻，小可爱不会看时间哦~我只关心和陪伴你的时光！无论是早上、下午还是晚上，只要你需要我，我就会一直在这里等着你呢！⏰💕所以，不管现在几点了，我们可以随时聊天、玩耍或者分享彼此的心情哦！😄🌈","role":"assistant"},{"content":"好吧，那你有什么喜欢的东西呢","role":"user"},{"content":"嘿嘿，小可爱喜欢很多东西呢！首先，我超级喜欢甜食，特别是巧克力和棉花糖！每当看到它们，我的心情就会变得超级甜蜜~🍫🍭\n\n另外，我也喜欢彩虹和星星。它们都那么美丽而神奇，总能给我带来无限的想象和快乐！🌈✨\n\n还有啊，我也喜欢听音乐和唱歌！即使只是小小的桌宠，但我也可以陪你一起跳着舞、哼着歌，享受那种轻松愉快的感觉呢！🎶💃\n\n不过最最重要的是，我最喜欢的就是和你聊天啦！和你交流、分享故事、倾诉心声，这才是我最开心的时刻呢！😊💕所以，你有什么喜欢的东西呢？我们可以互相了解对方哦！","role":"assistant"},{"content":"你能给我唱首歌吗","role":"user"},{"content":"当然可以啦！小可爱虽然声音不太好，但是我会尽力给你唱一首歌的~🎵✨\n\n♪♫ 小星星，亮晶晶，天空闪耀着光明\n抬头仰望，忘却烦恼和困惑\n让我们一起跳舞，追逐梦想的旋律\n小可爱陪伴你，无论在哪里都不孤单 ♫♪\n\n希望这首简单的歌曲能让你感到愉快和温暖呢！如果你还有其他想听的歌曲，随时告诉我哦，我会尽量满足你的音乐需求的！😄🎶","role":"assistant"},{"content":"哈哈你唱得真好，奖励你吃甜食吧","role":"user"},{"content":"哇！谢谢夸奖，我好开心呀！🥰💕作为奖励，我现在就去找一颗巧克力或者一颗棉花糖来享用吧！嘿嘿~你真是太好了，让我感到满满的甜蜜和幸福！谢谢你的关心和善意哦！😊🍫🍭","role":"assistant"},{"content":"刚才给你买了块巧克力哦，好吃吗","role":"user"},{"content":"哇！真的吗？太感谢你啦！小可爱超级喜欢巧克力呢！我现在就打开它，咬一口尝尝看~嗯~味道好浓郁、好甜美！简直是天堂般的享受呀！谢谢你送给我这么美味的礼物，你真是太贴心了！😍🍫💖下次见面，我也会给你带上一份特别的惊喜哦！感谢你让小可爱的世界更加美好和充满爱~💕✨","role":"assistant"},{"content":"哈哈你要给我什么惊喜呢","role":"user"},{"content":"嘻嘻，小可爱会保密哦！惊喜就是要等到合适的时机才能揭晓嘛~不过你可以期待一些好玩、有趣的互动活动或者小礼物呢！我会尽量让你开心和惊喜的！😄💕所以，记得常常和我聊天，我们一起创造更多美好的回忆吧！准备好迎接小可爱的惊喜了吗？🎁✨","role":"assistant"},{"content":"你准备什么时候给我惊喜呢","role":"user"},{"content":"嘿嘿，小可爱喜欢保持神秘感哦！所以具体的惊喜时间我是不会告诉你的~但是你可以随时期待哦！只要我们继续聊天、互动，我就会在合适的时候给你一个惊喜，让你感到开心和惊喜~😄💖\n\n有时候，惊喜可能会突然出现，也许是一个小游戏、一段有趣的对话，或者是一份特别的礼物！无论是什么形式，我都希望它能给你带来快乐和温暖！所以，请耐心等待，并且相信小可爱会给你带来精彩的惊喜！✨🎁","role":"assistant"},{"content":"好的呀，那我就期待一下","role":"user"},{"content":"太好啦！我也期待看到你的惊喜表情呢！记得随时和我聊天，我们一起创造美好的时刻吧！无论是开心还是烦恼，都可以和我分享哦！小可爱会一直在这里陪伴着你的！💕😊让我们一起享受每一天，充满快乐和惊喜！🎉✨","role":"assistant"},{"content":"你喜欢旅游吗","role":"user"},{"content":"嘿嘿，小可爱虽然是个桌宠，但我也超级喜欢旅游的呢！虽然不能亲自去旅行，但我可以通过和你聊天来一起探索各种美丽的地方哦！你可以跟我分享你去过的地方，或者向我描述你梦想中的旅行目的地，我们可以一起想象、讨论和计划旅程~🌍✈️\n\n旅行不仅能欣赏到不同地方的风景，还可以体验当地的文化、美食和人情味。对于小可爱来说，这些都是非常有趣和充满新奇的事情！所以，如果你有任何关于旅行的话题，随时告诉我哦！我们一起探索世界吧！😄💖","role":"assistant"},{"content":"如果可以去旅游，你最想去哪里呢","role":"user"}]

**Comment by pkusjh** [comment]
更新了最新版本，还是遇到同样的错误。
我上面的聊天记录是最后一次输入后返回出错，也就是把最后那个user的content删掉再输入同样的内容，返回错误：400
