### ISSUE TITLE
关于配置问题

### ISSUE THREAD

**Issue by Elyon9612** [LorisYounger/VPet#82]
When following the step: mklink.bat for running the program

**C:\Users\Desktop\VPet\VPet-Simulator.Windows>mklink /d "C:\Users\Desktop\VPet\VPet-Simulator.Windows\\bin\x64\Release\mod" "C:\Users\Desktop\VPet\VPet-Simulator.Windows\\mod"
The system cannot find the path specified.**

请问怎么解决下？感谢

**Comment by LorisYounger** [comment]
见 Readme https://github.com/LorisYounger/VPet#%E6%A1%8C%E9%9D%A2%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95
