### ISSUE TITLE
更好买更改筛选条件时重置页码

### ISSUE THREAD

**Issue by A2uria** [LorisYounger/VPet#87]
目前的实现是这样的：

https://github.com/LorisYounger/VPet/blob/198d1a9155094285b7ffb921f7abc1d3127c99f5/VPet-Simulator.Windows/WinDesign/winBetterBuy.xaml.cs#L157-L162

更改筛选条件的时候页码不会重置。

看了一下翻页的调用链是 `pagination_CurrentPageChanged -> Search -> OrderItemSource`。

页码更改仅在 `OrderItemSource` 里实现且没有外部引用，可以考虑添加一个参数（比如 `reset_current_page` 或者 `reason` 之类的）并在调用的时候指明是否需要重置页码这样。

但是缩放窗口也用的相似实现（`AutoUniformGrid_Changed -> Search -> OrderItemSource`），所以可能要内联一下此处 `Search` 或者重构一下 `OrderItemSource`。

**Comment by LorisYounger** [comment]
并不打算在更改筛选条件的时候重置页码
因为这个感觉会更加方便使用
例如: 当前我正在看最便宜的食物 (食物正序最后一页)
我现在想看最便宜的饮料, 切换后正好就是最便宜的饮料 (最后一页类似这样的)
感觉会比较方便, 就懒得加个当前页数=0了
