### ISSUE TITLE
拖动后快速点击摸头有几率无CD高速摸

### ISSUE THREAD

**Issue by wzqvip** [LorisYounger/VPet#88]
大概是拖拽之后，快速点击，可以连续快速摸头，消耗几十点体力值。
<img width="615" alt="image" src="https://github.com/LorisYounger/VPet/assets/30136639/227da060-ce68-4ac0-aece-c2118233decc">

不是特别会触发。 触发过两次。 比摸身子多的四十多次就是这个bug触发的。 后续可能会传复现方法。

**Comment by LorisYounger** [comment]
看上去是无关痛痒的bug( 就懒得修了
就当做小彩蛋好了,这种小彩蛋游戏里还蛮多的(
感谢你的反馈

**Comment by wzqvip** [comment]
<img width="214" alt="image" src="https://github.com/LorisYounger/VPet/assets/30136639/408bfb72-c198-4b1f-aaf7-945e99522ee1">

很难复现。 最后体力没消耗完也点不动了。 我没看源码不知道摸头cd怎么计算的，但事实感觉很像是把挂机这么久的头一起摸掉了x

**Comment by LorisYounger** [comment]
我估计可能是计算了你没开steam时候的统计
