### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by start-is-a-city** [LorisYounger/VPet#9]
在vs里面打开，调整好包过后，出现类似这种错误。
错误	CS0006	未能找到元数据文件“VPet-main\VPet-Simulator.Windows.Interface\bin\Debug\VPet-Simulator.Windows.Interface.dll”

**Comment by LorisYounger** [comment]
跑一边就好了,项目内是互相引用的,出现这个问题是没生成
如果跑了后还有这错误,就是其他原因导致`VPet-Simulator.Windows.Interface`没生成,具体可以看错误日志
