### ISSUE TITLE
Feature Idea - Random Name

### ISSUE THREAD

**Issue by pietru2004** [LorisYounger/VPet#90]
I think it could be cool to have button that randomizes VPet Name, also it could be randomized on game first launch/when there are no save/setting files.
It could be 1 giant list of random names or system like adding 2 strings 
ex. String1 = Lo, String2 = li
String1 + String2  = Loli

**Comment by LorisYounger** [comment]
The default pet name is It is decided by the animator (mod author etc)
When you switch skins, if you keep the default name, it will switch to the different name from new skin.
