### ISSUE TITLE
关于VPet在WPF程序中的运行

### ISSUE THREAD

**Issue by ElleAutumn** [LorisYounger/VPet#93]
我正在尝试使用WPF制作VPet的模组制作工具以方便制作Mod,并尝试使用Vpet.Core在模组制作工具中实时加载MOD,但我现在仍然找不到正确的方法使VPET在WPF运行，请问是有什么公开的方法可以在WPF后台或者前台中运行VPET吗?

**Comment by LorisYounger** [comment]
本项目 VPet-Simulator.Windows , 顺带一提模组制作工具正在做, 在 https://github.com/LorisYounger/VPet.Plugin.Demo
