### ISSUE TITLE
steam上游戏无法启动，从源代码启动也不行

### ISSUE THREAD

**Issue by againwq** [LorisYounger/VPet#94]
我尝试将代码下载到本地运行，安装说明做好后仍然保存，我调试后发现是在加载Core mod时解析lps文件报错了，抛出System.IO.FileNotFound的异常，System.IO.FileNotFoundException:“未能加载文件或程序集“Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。”是在CoreMod.cs文件的public CoreMOD(DirectoryInfo directory, MainWindow mw)方法中执行Name = modlps.FindLine("vupmod").Info;这一行抛出异常.

系统为win10， vs2022， netframework版本4.8

**Comment by againwq** [comment]
也尝试了以管理员身份启动，也检查了Microsoft.CSharp的引用和版本，但是都没有解决

**Comment by LorisYounger** [comment]
https://stackoverflow.com/questions/11078404/could-not-load-file-or-assembly-microsoft-csharp-when-logged-in-with-user-whic

如果从属性中设置以管理员身份启动呢?
说实话这种错误基本上都是系统的问题, 和桌宠无关, 可能是你系统有问题或者缺了啥,我建议重装系统解决.
因为就算不跑桌宠,也会遇到其他软件的兼容性问题
至少目前看起来你的配置是没有问题的,vs都装了
