### ISSUE TITLE
`Nomal` typo -> `Normal`

### ISSUE THREAD

**Issue by gottyduke** [LorisYounger/VPet#95]
代码中包含翻译文本, 所有涉及`Normal`的部分都被命名为`Nomal`, 个人猜测是typo?
[搜索结果](https://github.com/search?q=repo%3ALorisYounger%2FVPet+Nomal&type=code)

**Comment by LorisYounger** [comment]
是的,但是这个不会修,因为已经写死在mod里了, 改了后之前的mod全坏
