### ISSUE TITLE
对话返回错误400依然存在

### ISSUE THREAD

**Issue by jhshen95** [LorisYounger/VPet#98]
更新了最新版本，还是遇到同样的错误。
之前issue中聊天记录是最后一次输入后返回出错，也就是把最后那个user的content删掉再输入同样的内容，返回错误：400

_Originally posted by @pkusjh in https://github.com/LorisYounger/VPet/issues/81#issuecomment-1688285911_

**Comment by pkusjh** [comment]
不会，删掉所有content没有报错，只有到最后那一步才会报错

**Comment by pkusjh** [comment]
https://github.com/LorisYounger/VPet/issues/81#issuecomment-1686356846

**Comment by Kaki-Liu** [comment]
我用的自己chatgpt api，第一次输入就直接提示400错误，也是8月22日的版本。

**Comment by Kaki-Liu** [comment]
> 我用的自己chatgpt api，第一次输入就直接提示400错误，也是8月22日的版本。

talkbox里显示的报错是：``API调用失败,请检查设置和网络连接System.Net.WebException: 远程服务器返回错误：(400)错误的请求。在System.Net HttpWebRequest.GetResponse()在ChatGPT.API。Framework.Completions.G(String APIUrl, String APIKey)
在
ChatGPT.API.Framework.ChatGPTClien (String id, String usermessage)在VPet_Simulator.Windows.TalkBoxAPI.OP(String content)``

**Comment by LorisYounger** [comment]
经查证,是聊天历史太长导致的,现在应该已经修好了

**Comment by Kaki-Liu** [comment]
谢谢！已经可以正常使用了。



在 2023-09-04 23:27:09，"ZouJin" ***@***.***> 写道：

经查证,是聊天历史太长导致的,现在应该已经修好了
