### ISSUE TITLE
奇怪的bug

### ISSUE THREAD

**Issue by LingShi991123** [LorisYounger/VPet#99]
1.心情值明明已经是100了，但播放的动画仍然是不开心的状态
2.在不开心的状态下直播，所播放的动画是写文案时的动画

https://github.com/LorisYounger/VPet/assets/96658974/c33c4fb5-5fd5-442d-be6a-691978932d3c

**Comment by LorisYounger** [comment]
错误动画修好了

**Comment by LorisYounger** [comment]
心情对应不上应该是没有计算新状态的原因, 之前计算状态只在每计算周期进行.
现已修复
